### ISSUE TITLE
Código repetido em 'VALORUTILIZACAOATUAL'

### ISSUE THREAD

**Issue by aureliopires** [dgterritorio/RECART#10]
Na pág 117 do CartTop-V1.0 (28.06.2019), para o 'VALORUTILIZACAOATUAL', o código 7.2 está repetido: "Serviços de utilização coletiva" e "Outros - Serviços".
No Dicionário de objetos em http://www.dgterritorio.gov.pt/recart/ , estes valores estão diferentes do indicado no CartTop-V1.0: o 7.1 "Serviço Público" e 7.2 "Outros - Serviços".

**Comment by aserronha** [comment]
Boa tarde,

É claramente um erro do documento das Especificações Técnicas e será substituído o valor 7.2 por 7.3 em "Outros - Serviços" numa próxima versão 1.x do CartTop-V1.0 (28.06.2019). 

Haviam algumas incongruências (do valor 7 ao 7.3) no github e no dicionário de objetos, que já foram resolvidas. Na base de dados não houve necessidade de corrigir porque estava tudo bem.

Cumprimentos e obrigado.
