### ISSUE TITLE
Dúvida: Árvores classificadas

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#101]
Podem-me esclarecer se o objecto **Ponto de Interesse**, do tipo **Árvore Classificada**, se refere a exemplares arbóreos classificados e não a toda uma espécie de interesse ambiental?

Exemplo:

Azinheira Centenária vs todas as azinheira

No primeiro caso estaríamos a falar de exemplares de árvores contidos no seguinte catálogo:

https://sig.icnf.pt/portal/home/webmap/viewer.html?useExisting=1&layers=6a1e91d4fb1e4347a3447d84dcaffa10

E só se representariam, por exemplo Sobreiros, enquanto Árvore isolada (fora de zonas agricolas, florestais, etc...)

**Comment by aserronha** [comment]
Boa tarde,

Refere-se a exemplares arbóreos classificados individualmente de acordo com esse portal do ICNF. 
Antes de se começar a produzir também deve ser tida em conta, a consulta prévia, a informação já existente do respetivo município.
