### ISSUE TITLE
Dúvida: Representação de valas / canais de transporte de água e conexão 3D

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#102]
Segundo o documento das normas e o dicionário de objectos, valas e canais, para transporte de água, com largura igual ou superior a 1 m, devem ser representado enquanto Curso de Água - área e curso de água - eixo (eixo ficticio).

Dúvida 1: No momento do levantamento deste tipo de estruturas, deve levantar-se os limites da área pelo caudal existente, ou pelo topo do talude das valas ou canais.

Dúvida 2: Na representação do eixo fictício dessas áreas, representa-se o Z pela superficies do caudal existente, ou pelo estimado como cota máxima das áreas (ao mesmo nível que o topo dos taludes)

Dúvida 3: Quando um desses canais ou valas, passa a passagem hidráulica, subterrânea (e eventualmente com percurso desconhecido), deve o Z do eixo ser representado ao nível o eixo fictício dos canais adjacentes ou pela sua cota real abaixo da superfície do solo.

**Comment by aserronha** [comment]
Boa tarde,

Obrigado pela perspicácia das questões!

Dúvida 1 - resposta: Deve levantar-se os limites da área pelo caudal existente. Se não houver água no momento de avaliar a representação do objeto (parâmetros de largura mínima consoante o NdD), deve ser considerada a menor base do terreno entre margens/taludes/paredes.

Dúvida 2 - resposta: De grosso modo, pode dizer-se que se representa o Z pela superfície do caudal existente. Quando não existe água, deve ser considerada a menor base do terreno entre margens/taludes/paredes.

Dúvida 3 - resposta: A monotonia do eixo deve ser garantida através da interpolação entre os pontos de entrada e saída do 'Curso de água - eixo' quando atravessa a 'Obra de arte - Passagem hidráulica'. De grosso modo e por uma questão de simplificação, basta a altitude ser representada ao nível da superfície dos "cursos de água" adjacentes já que por vezes não é possível saber a cota (no mundo real) da passagem hidráulica.

Ver esquema: https://www.dgterritorio.gov.pt/recart/imagens/eCursoDeAguaArea5.jpg
