### ISSUE TITLE
Divergência das Toponimias de Ruas (CatalogoViasRodov-Parte2) e Placas de Rua

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#103]
Bom dia, 

Quando nos deparamos com divergências na escrita de nomes de ruas entre o que vemos nas Placas de Rua e a Listagem fornecida, maioria das situações erros de ortografia, como devemos proceder?

A) associar mesmo assim o registo da listagem aos seg_via_rodov
ou
B) criar um registo novo com a correção do nome e associar esse registo ao seg_via_rodov

**Alguns exemplos ilustrativos destas situações:**
_Exemplo 1_ – Rua Albertino Urbano
![image](https://user-images.githubusercontent.com/60113889/141956612-2f3c3a03-814b-4ab1-9328-0ff506d3b6ab.png)

_Exemplo 2_ - Rua Professor José Vale Petronilho - A placa de rua está ilegivel.
![image](https://user-images.githubusercontent.com/60113889/141956689-b1b3a4dc-03d3-4f2e-b0dc-0bbe2af3853b.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Exemplo 1: Já verificámos. Vamos corrigir o catálogo mas podemos já adiantar que mantém o código. O nome correto a constar é **R ALBERTINO URBANO**

Exemplo 2: Vamos corrigir o catálogo mas podemos já adiantar que mantém o código. O nome correto a constar é **R PROF JOSÉ DO VALE PATRONILO**:

![imagem](https://user-images.githubusercontent.com/46351849/143066357-89b4918b-29b6-44ea-a013-8efd69a7a56f.png)

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Querem que reportemos este tipo de situação para corrigirem as listagens?

Obrigado,

**Comment by aserronha** [comment]
Sim.

Como já repararam, este é um trabalho que está a ser agilizado e corrigido em conjunto com o INE. Este tipo de trabalho é muito profícuo também para o INE no confronto com os resultados dos Censos 2021. A harmonização dos dados é fundamental.

Obrigado!
