### ISSUE TITLE
Classificação de Adega - NdD2

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#104]
Bom dia,

Gostaríamos de saber como classificamos uma Adega no NdD2, nomeadamente quanto ao valorUtilizacaoAtual e à atribuição de uma relação à Instalação de Produção.

Obrigada

**Comment by aserronha** [comment]
Boa tarde,

O edifício da Adega deve ser recolhido (caso tenha dimensões de acordo com as Especificações Técnicas) e quanto ao valorUtilizacaoAtual deve assumir o valor 3 = Indústria.

A sua relação com a Instalação de produção, para o NdD2, não é obrigatória.

Na próxima versão das Especificações Técnicas voltará a ser analisada a introdução de obrigatoriedade nesta classificação.
