### ISSUE TITLE
Diferença entre Túnel e Passagem Inferior

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#105]
Bom Dia, 

Agradecíamos uma clarificação sobre o que devemos considerar como túnel e passagem inferior.

No nosso entendimento consideramos **túnel** quando existe uma perfuração do terreno. Dito de uma forma mais rudimentar é quando sobre a obra de arte está coberta com terra/vegetação e não se consegue “retirar” o tabuleiro.
Enquanto que consideramos **Passagem Inferior** quando não existe perfuração do terreno. Dito de forma mais rudimentar é quando o tabuleiro está “suspenso” e não assente no terreno e conseguimos “retirar” o tabuleiro.

**Exemplo de situações ilustrativas:**
![image](https://user-images.githubusercontent.com/60113889/141964541-93cbb816-866c-4f4b-ad68-1bc585125e1b.png)

![image](https://user-images.githubusercontent.com/60113889/141964854-b39fd1cc-6837-4e39-ae78-03c8bfab31c9.png)

Nota: Na identificação de passagem inferior temos em conta a hierarquia das estradas.

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

De forma concisa, parece que os exemplos ilustram bem a diferença entre 'Passagem inferior' e 'Túnel'. É isso mesmo que se pretende.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento
