### ISSUE TITLE
Classificação de Passadiço

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#106]
Boa Tarde, 

Estamos perante o Passadiço do Alburrica.

A)	Questionamos se podemos classificar todas a extensão do passadiço quanto ao atributo “valor_tipo_troco” com o valor 7- Passadiço ou se nos troços que efetivamente não são passadiços (exemplo troço A e troço B), temos obrigatoriamente de atribuir outro valor?

B)	Tendo de atribuir outro valor nos troços A e B. Qual seria o valor mais correto? Trilho?
![image](https://user-images.githubusercontent.com/60113889/142045741-f69cac7a-e49e-4fc9-848d-655013076077.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

A opção mais adequada é considerar Trilho (via urbana).

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento,
