### ISSUE TITLE
Dúvida: Nó ferroviário - Passagem de nível

### ISSUE THREAD

**Issue by fmarleitao** [dgterritorio/RECART#107]
Relativamente às passagens de nível, nomeadamente no metro de superfície, nas rotundas, o nó de passagem de nível deve estar inserido no centróide da rotunda ou em cada interceção eixo ferroviário / eixo rodoviário.

No caso de multiplas interceções com eixos rodoviários (ver imagem), devemos considerar um único nó de passagem de nível ou um em cada interceção eixo ferroviário / eixo rodoviário.

![Capturar](https://user-images.githubusercontent.com/94842401/142862462-ba53892d-d342-4da0-bff4-1449d3cd23fe.PNG)

**Comment by aserronha** [comment]
Viva,

Resposta: Devem existir nós rodoviários (valorTipoNoTransRodov -> Passagem de nível) coincidentes com nós ferroviários (valorTipoNoTransFerrov -> Passagem de nível) **em cada interceção** de segmentos (eixo ferroviário / eixo rodoviário). Ver especificações técnicas.
