### ISSUE TITLE
Representação de Áreas Infraestruturas vs Infraestrutura e Nós Rodoviarios

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#108]
Boa Tarde, 

Como devemos representar situações como as ilustradas nas imagens abaixo?

**1. Representação da área de infraestrutura vs Ponto de infraestrutura (imagem da esquerda):**
_**Opção A -**_ Apenas deve ser representada uma única área onde se incluiu a praça de táxis, terminal rodoviário e a área de estacionamento (linha a amarela) e no tipo de serviço da infraestrutura colocado os valores de “Estacionamento” e “Estacionamento para veículos pesados”
**_Opção B -_** Ou devemos representar 3 áreas em separado e classificar a infraestrutura quanto ao tipo de serviço em separado

**2. Representação dos Nós rodoviários**
a.	Onde deve ser colocado o nó ou nós rodoviários referentes às infraestruturas? 

![image](https://user-images.githubusercontent.com/60113889/142901297-05cf749d-5c9e-471a-9fee-f8f583b7f540.png)

Nota: Estas situações também acontecem nos Postos de Combustíveis das grandes superfícies comerciais. 

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

1. Da forma que a situação é descrita parece-nos mais razoável a **_Opção B_** em que cada área é bem delimitada e representativa de cada infraestrutura que é passível de ser caracterizada individualmente no atributo valorTipoInfraTransRodov. Ver: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html#go_up_valorTipoInfraTransRodov

2. O nó rodoviário (infraestrutura) deve ser colocado, sempre que possível, de acordo com a regra específica 5.5.9. Há situações particulares em que os nós podem também ser colocados de acordo com a seguinte figura: https://www.dgterritorio.gov.pt/recart/imagens/eInfraTransRodov-valorTipoInfraTransRodov4-3.jpg 

Relativamente às áreas bem delimitadas das grandes superfícies comerciais em que não é bem identificável a zona reservada ao **Parque de estacionamento** nem ao **Posto de abastecimento de combustíveis**, pode-se caracterizar a delimitação bem definida (da área global onde estão todas as infraestruturas inseridas) no objeto **Área artificializada** (4. Equipamentos comerciais ou de carácter geral) e colocar os respetivos pontos das Infraestruturas dentro dessa área comercial, no local que melhor caracterize cada infraestrutura. Os respetivos nós podem ser colocados como descritos em 2.

**Comment by CatarinaGaspar** [comment]
> 2\. O nó rodoviário (infraestrutura) deve ser colocado, sempre que possível, de acordo com a regra específica 5.5.9. Há situações particulares em que os nós podem também ser colocados de acordo com a seguinte figura: https://www.dgterritorio.gov.pt/recart/imagens/eInfraTransRodov-valorTipoInfraTransRodov4-3.jpg

Nós sabemos que sempre quando existe mais do que uma entrada temos de colocar tantos nós quantas entradas existirem. No entanto nesta situação do terminal rodoviário ficamos na dúvida se teríamos que colocar vários nós rodov, um nó por cada "entrada" ou se apenas bastava apenas um nó.
![image](https://user-images.githubusercontent.com/60113889/145644927-90be83e0-47f7-411a-9bf8-32a7e06c6970.png)

**Comment by aserronha** [comment]
Relativamente ao primeiro comentário basta apenas colocar um nó para as várias entradas porque as entradas efetuam-se todas pela mesmo arruamento. Os exemplos de vários nós para a mesma infraestrutura são mais aplicados a várias entradas em diferentes arruamentos.

Relativamente ao segundo comentário, sim, basta colocar os pontos das infraestruturas. Nestes casos particulares a área pode ser apenas aplicada como "Área artificializada" (4. Equipamentos comerciais ou de carácter geral).

**Comment by CatarinaGaspar** [comment]
Entendido. Obrigado pelo esclarecimento.
