### ISSUE TITLE
Representação da Geometria Horizontal dos Edifícios

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#109]
Bom dia, 

As imagens seguintes expõem a nossa interpretação relativamente a este assunto. Podem confirmar se está correta?

**Situação A –   Alpendres/Telheiros inseridos no edifício**
![image](https://user-images.githubusercontent.com/60113889/143005338-b7af9df3-d996-4c01-b9ed-80ddfac29a21.png)
NdD1 | Os alpendres vs   telheiros, não são retirados da área do edificios. Apenas é descontado a área   do beirado.
NdD2 | Não são retirados   da área do edificio, o beirado fica incluido na área do edificio

**Situação B – Alpendres/Telheiros não inseridos no edifício**
![image](https://user-images.githubusercontent.com/60113889/143005466-8d6cda22-f0fe-4388-92ae-62ee656ecefb.png)
  
-   Alpendres/Telheiros **com área minim**a de representação
![image](https://user-images.githubusercontent.com/60113889/143006823-288752cc-8326-4d47-96fa-4792b9443fb5.png)
NdD1 | Os alpendres vs telheiros são representados. Apenas é descontado a área do beirado.       
NdD2 | Os alpendres vs telheiros são representados. O beirado fica incluído na área do edifício.

- Alpendres/Telheiros **sem área minim**a de representação
![image](https://user-images.githubusercontent.com/60113889/143007219-a5b0d220-5063-4a3e-a133-dab6382f784f.png)
NdD1 | Os alpendres vs telheiros não são representados.        
NdD2 | Os alpendres vs telheiros não são representados.

**Situação C – Edifícios sem área mínima de representação (NdD1 e NdD2)**
![image](https://user-images.githubusercontent.com/60113889/143007414-d8a2da27-cbf2-454e-8fba-cc89ce1de4bb.png)
Não tendo área minima e com a mesma utilização. Nestes casos junta-se ou elimina-se dado que pertencem a propriedades diferentes?

Obrigado,

**Comment by aserronha** [comment]
Situação A – Alpendres/Telheiros inseridos no edifício
https://user-images.githubusercontent.com/60113889/143005338-b7af9df3-d996-4c01-b9ed-80ddfac29a21.png
NdD1 | Os alpendres vs telheiros, não são retirados da área do edificios. Apenas é descontado a área do beirado.
NdD2 | Não são retirados da área do edificio, o beirado fica incluido na área do edificio 
**Resposta: Soluções bem interpretadas para o NdD1 e NdD2.** 

Situação B – Alpendres/Telheiros não inseridos no edifício
https://user-images.githubusercontent.com/60113889/143005466-8d6cda22-f0fe-4388-92ae-62ee656ecefb.png 
**Resposta: Quando dizem que no NdD1 se apaga o Alpendre/Telheiro não percebemos o porquê dessa interpretação. Estão a referir-se às 3 imagens ou apenas à imagem 3?**

Alpendres/Telheiros com área minima de representação
https://user-images.githubusercontent.com/60113889/143006823-288752cc-8326-4d47-96fa-4792b9443fb5.png  
NdD1 | Os alpendres / telheiros são representados. Apenas é descontado a área do beirado.
**Resposta: Não conseguimos interpretar se estão a referir-se ao beirado do Edifício ('Habitação') ou do Edifício ('Associado à residência').**
NdD2 | Os alpendres / telheiros são representados. O beirado fica incluído na área do edifício.
**Resposta: Não conseguimos interpretar se estão a referir-se ao beirado do Edifício ('Habitação') ou do Edifício ('Associado à residência').**

Alpendres/Telheiros sem área minima de representação
https://user-images.githubusercontent.com/60113889/143007219-a5b0d220-5063-4a3e-a133-dab6382f784f.png 
NdD1 | Os alpendres / telheiros não são representados.
NdD2 | Os alpendres / telheiros não são representados.
**Resposta: Soluções bem interpretadas para o NdD1 e NdD2.**
https://www.dgterritorio.gov.pt/recart/imagens/eEdificio1.jpg 

Situação C – Edifícios sem área mínima de representação (NdD1 e NdD2)
https://user-images.githubusercontent.com/60113889/143007414-d8a2da27-cbf2-454e-8fba-cc89ce1de4bb.png
Não tendo área minima e com a mesma utilização. Nestes casos junta-se ou elimina-se dado que pertencem a propriedades diferentes?
**Resposta: Caso seja possível identificar que os edifícios pertencem a propriedades diferentes, não devem ser representados.**

**Comment by CatarinaGaspar** [comment]
> Situação B – Alpendres/Telheiros não inseridos no edifício https://user-images.githubusercontent.com/60113889/143005466-8d6cda22-f0fe-4388-92ae-62ee656ecefb.png 
Resposta: Quando dizem que no NdD1 se apaga o Alpendre/Telheiro não percebemos o porquê dessa interpretação. Estão a referir-se às 3 imagens ou apenas à imagem 3?
> @aserronha **R:. Estamos a referir-nos apenas à imagem 3**

> Alpendres/Telheiros com área minima de representação https://user-images.githubusercontent.com/60113889/143006823-288752cc-8326-4d47-96fa-4792b9443fb5.png NdD1 | Os alpendres / telheiros são representados. Apenas é descontado a área do beirado. Resposta: Não conseguimos interpretar se estão a referir-se ao beirado do Edifício ('Habitação') ou do Edifício ('Associado à residência'). NdD2 | Os alpendres / telheiros são representados. O beirado fica incluído na área do edifício. Resposta: Não conseguimos interpretar se estão a referir-se ao beirado do Edifício ('Habitação') ou do Edifício ('Associado à residência').
@aserronha **R:. Em ambos os casos estamos a referir-nos ao beirado dos Edifícios ('Associado à residência')**

**Provavelmente esta nova imagem é mais clara quanto às questões da situação B:**
![image](https://user-images.githubusercontent.com/60113889/146218948-358a1928-f507-4bf3-8557-86de1b2c7843.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Está tudo bem interpretado!

Não esquecer que o Telheiro é identificado também no atributo "da forma".

Nota: Numa próxima versão das especificações está a ser equacionado deixar a cargo do produtor poder representar-se ora pela 'Implantação' ora pela 'Beira do telhado' tanto em NdD1 como em NdD2. Mas, no momento, é desta forma que descreveram e bem.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo feedback.
