### ISSUE TITLE
Attributos iDHidrografico em falta

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#11]
O documento de Normas Especificações Tecnicas V1.0 Vários obectos do tem Hidrografia contêm um atributos chamado iDHidrográfico, no entanto a implementação do modelo de dados em PostGIS não contém esse atributo.

**Comment by dgterritorio** [comment]
Já foi corrigido há 4 dias em https://github.com/dgterritorio/RECART/commit/0ed681b7ededeecc08a7e66ad015fb105a2ec8d0
