### ISSUE TITLE
Infraestruturas de transporte aéreo (ponto)

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#110]
Bom dia,

Gostaríamos de saber como classificar a Infraestrutura de Transporte Aéreo em hospitais, bombeiros, etc.
Segundo o dicionário de objetos, o valorTipoInfraTransAereo apenas deverá ser  "1 Aeródromo" (ponto), "2 Heliporto" (ponto) ou "3 Aeródromo com heliporto" (ponto) se houver uma infraestrutura de apoio. São estes locais considerados como infraestruturas de apoio ou devemos classificar o ponto como  “4 Local de aterragem” (ponto)?

Exemplo:

![image](https://user-images.githubusercontent.com/60008526/143592973-f6070697-1eeb-4928-8e30-85c569f0541d.png)

Obrigada

**Comment by aserronha** [comment]
Boa tarde,

Pode recorrer a fontes auxiliares como a ANAC, onde são disponibilizados os Heliportos de Portugal:
https://www.nav.pt/ais/vfr-manual/heliportos  

No dicionário de objetos também temos algumas observações sobre o que deve ou não ser considerado um **Heliporto** ou um simples **Local de Aterragem**. Ver em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20a%C3%A9reo)/InfraTransAereo.html#page_valorTipoInfraTransAereo
