### ISSUE TITLE
Representação do Objeto Salina

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#111]
Boa Tarde, 

**Como deve ser representado geometricamente as salinas?** 

- Opção A - Uma área única, linha amarela, no tema área artificializada ficando classificada como “equipamentos Indústrias” e com ligação à tabela instalação produção?

- Opção B. Várias áreas, polígonos a azul, no tema área artificializada ficando classificada como “equipamentos Indústrias” e com ligação à tabela instalação produção?

Devemos fazer sempre a relação à tabela instalação produção mesmo quando não temos nome, atribuindo-lhe o nome de "Salina", correto?

![image](https://user-images.githubusercontent.com/60113889/143719514-38641898-71fe-49ff-a1d1-9f682efe557f.png)

Obrigado,

**Comment by aserronha** [comment]
Por uma questão de simplificação pode ser a opção A. 

Correto.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento

**Comment by aserronha** [comment]
Boa tarde,

Como persistem muitas dúvidas na representação da Salina (que pode ser constituída por uma ou mais áreas) gostaríamos de esclarecer que deve-se verificar se no interior da área que representa a salina existem objetos cuja representação deverá ser discriminada, nomeadamente tanques, segmentos da via rodoviária, valas, etc.

A salina representa-se por uma ou mais áreas no tema [[07.02] Área artificializada](https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreasArtificializadas.html) com o [valorAreasArtificializadas](https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreasArtificializadas.html#page_valorAreasArtificializadas) “3. Equipamentos industriais” e com ligação à [[08.10] Instalação de produção](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/InstProducao.html) com o [valorInstalacaoProducao](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/InstProducao.html#page_valorInstalacaoProducao)  “4.4 Salina”.
Cada reservatório da "Salina" deve ser representado como "Tanque". 

Ver os seguintes esquemas:
https://www.dgterritorio.gov.pt/recart/imagens/eInstProducao-valorInstalacaoProducao4.4-1.jpg
https://www.dgterritorio.gov.pt/recart/imagens/eInstProducao-valorInstalacaoProducao4.4-2.jpg
https://www.dgterritorio.gov.pt/recart/imagens/eInstProducao-valorInstalacaoProducao4.4-3.jpg
