### ISSUE TITLE
R7 - Atribuição de Nomes

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#112]
Bom dia, 

Apenas para reflexão, se faz sentido não existir abreviaturas para todos os campos "nome" à excepção do "nome" da via rodoviária.

Se uma empresa tem o nome, por exemplo "J. Pinto Leitão, S.A" faz sentido ser colocado "Joaquim Pinto Leitão, S.A"?

Entendemos a finalidade de não existirem abreviaturas nestes campos, contudo, não nos parece o mais correto, até porque nos logos vs publicidade das empresas aparecem os nomes abreviados.
![image](https://user-images.githubusercontent.com/60113889/145799182-acf06841-a277-4312-ad7a-46fcfdabcfbb.png)

Além de que nem sempre é fácil decifrar o que querem dizer as abreviaturas nos nomes das empresas.

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Nestes casos particulares podem utilizar as abreviaturas disponíveis. Mesmo que as ferramentas assinalem estas incongruências, são casos de falsos erros.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento.
