### ISSUE TITLE
Designação do atributo “valorElementoAssociadoElectricidade”

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#113]
Para uniformizar e evitar erros de escrita, e uma vez que as outras designações seguem a escrita segundo o Acordo Ortográfico, recomenda-se que o atributo “valorElementoAssociadoElectricidade” seja alterado para “valorElementoAssociadoEletricidade” (Electricidade sem a letra “c” antes do “t”) uma vez que o objeto é designado por “Elemento Associado de Eletricidade” e a classe de objetos é “ElemAssocEletricidade”, ambos sem o “c” (aparentemente este é caso único).

**Comment by aserronha** [comment]
Boa tarde,

Obrigado pela sugestão mas mantivemos a designação para evitar alguma incongruência no futuro.
