### ISSUE TITLE
Representação Nó Infraestrutura - TransporteRodov 

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#115]
#108 
Bom dia, 

A - Nestes casos onde seria o(s) local(ais) mais apropriado(s) para a colocação do nó de infraestrutura referente à infraestrutura (Parque de estacionamento)?
Pela lógica teríamos de colocar dois nós visto que existem duas entradas em arruamentos diferentes. Pontos A e B.

B - Quando falamos de entradas, são consideradas todas independentemente do tipo de circulação, certo? ou o raciocínio apenas é válido para as entradas em que a circulação é feita por veículos automóveis?

C - Não podemos colocar  nós de infrestruturas em cima de nós "pseudo-nós"? 

![image](https://user-images.githubusercontent.com/60113889/149496157-2c25ba3a-e930-4680-8d3f-a2607b4edd97.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

A - Pela imagem apresentada e pelos sentidos de tráfego apresentados, aparentemente só há entrada em B. Os nós (infraestrutura), sempre que possível, devem ficar na via rodoviária "principal" de acesso à infraestrutura, ou seja, nesse exemplo é preferível ser colocado nessa via rodoviária com "aspeto" de Avenida/Circular...

B - A infraestrutura é "Parque de estacionamento". Por uma questão de simplificação bastam as entradas para veículos automóveis.

C - Nós (infraestrutura) não devem coincidir com nós (pseudo-nó).
