### ISSUE TITLE
Representação de Estação Elevatórias(EE) dentro de ETA

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#116]
#114

Bom dia, 

a)	Quando existe uma EE no interior de uma ETA, as áreas de estação elevatória e estação de tratamento devem ficar sobrepostas?
b)	O edificio (edificio A) estando associado à EE não se estabelece ligação à tabela insta_ambiental? 
c)	Ou estabelecemos ligação à tabela inst_ambiental e fica ligada à ETA?
![image](https://user-images.githubusercontent.com/60113889/150958761-c8f4e6a3-96aa-4593-b74b-e4ce43cdff1b.png)

d)	No tipo de EE ilustradas abaixo não estabelecemos ligação à tabela inst_produção, certo?
A nossa questão é por causa da colocação do nome, que desta forma não o colocamos em nenhum sitio.
![image](https://user-images.githubusercontent.com/60113889/150958802-8690f898-41cb-4f0a-b82a-460c8389c8d9.png)

Obrigado,

**Comment by aserronha** [comment]
> #114
> 
> Bom dia,
> 
> a) Quando existe uma EE no interior de uma ETA, as áreas de estação elevatória e estação de tratamento devem ficar sobrepostas?
R: Sim, se existir uma dentro de outra, pode ficar a área de Estação elevatória (EE) sobreposta à área de uma Estação de Tratamento de Água (ETA) desde que seja uma EE de água (para abastecimento). Estações elevatórias de Águas Residuais (esgotos) não se representam neste objeto mas sim no valor 5. em [valorAreasArtificializadas](https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreasArtificializadas.html#go_up_valorAreasArtificializadas)  
> b) O edificio (edificio A) estando associado à EE não se estabelece ligação à tabela insta_ambiental? 
R: Se for uma EE de abastecimento de água não há relação com uma 'Instalação de gestão ambiental' e como tal o edifício não tem relação com essa tabela. Se for uma EE de águas residuais deve ser estabelecida ligação à  insta_ambiental tanto da área artificializada (valor 5.) como do próprio edifício.
>c) Ou estabelecemos ligação à tabela inst_ambiental e fica ligada à ETA? ![image](https://user-images.githubusercontent.com/60113889/150958761-c8f4e6a3-96aa-4593-b74b-e4ce43cdff1b.png)
R: Anteriormente já foi dito que o modelo não estabelece relações entre inst_ambiental e ETA. Os elementos asssociados de água têm geometria própria e não têm relações.
> d) No tipo de EE ilustradas abaixo não estabelecemos ligação à tabela inst_produção, certo? A nossa questão é por causa da colocação do nome, que desta forma não o colocamos em nenhum sitio. ![image](https://user-images.githubusercontent.com/60113889/150958802-8690f898-41cb-4f0a-b82a-460c8389c8d9.png)
R: Neste momento só é permitido colocar nomes nos edifícios. Houve um lapso e como tal na próxima versão da base de dados já vai ser permitido colocar nomes em algumas [08] INFRAESTRUTURAS E SERVIÇOS DE INTERESSE PÚBLICO que não tinham o atributo nome.

> Obrigado,
