### ISSUE TITLE
Aplicação da Abreviatura “ACESSO/ACSS”

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#117]
Bom dia, 

Em que situações deve ser aplicado a abreviatura acss? 
É para ser aplicada nas situações de ramos de ligação?
![image](https://user-images.githubusercontent.com/60113889/150959148-a88e1645-60da-42c3-9a33-0daa9e4ebe06.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

É, por exemplo, para ser aplicado nas situações de ramos de ligação...

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento
