### ISSUE TITLE
Classificação de Ruínas com interesse Histórico

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#118]
Bom dia, 

Sendo as Ruinas com interesse histórico consideradas um ponto de interesse a sua representação geométrica fica apenas neste tema “pontoInteresse” classificadas como tal? Não sendo necessário a sua representação no tema “edificio”?

_A imagem abaixo ilustra a situação:_

Os poligonos representados referem-se a telheiros que estão a abrigar os monumentos abaixo. Estes poligonos apenas têm de estar desenhados no tema “pontoInteresse” ou também no tema edificio e classificados quanto ao valorUtilizacaoAtual : Atividades recreativas e culturais e ValorForma: Telheiro
![image](https://user-images.githubusercontent.com/60113889/150959591-3eb2109f-8b12-4749-9010-fdf78fa42f81.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Questões: Sendo as Ruinas com interesse histórico consideradas um ponto de interesse a sua representação geométrica fica apenas neste tema “pontoInteresse” classificadas como tal? Não sendo necessário a sua representação no tema “edificio”?

Respostas: Neste caso concreto sim. Não é necessário neste caso concreto representar mais nada sobre o ponto de interesse. Avaliar se o ponto de interesse é representado com a geometria ponto ou polígono de acordo com as dimensões mínimas aplicadas ao respetivo nível de detalhe (NdD). 


Questão: Os poligonos representados referem-se a telheiros que estão a abrigar os monumentos abaixo. Estes poligonos apenas têm de estar desenhados no tema “pontoInteresse” ou também no tema edificio e classificados quanto ao valorUtilizacaoAtual : Atividades recreativas e culturais e ValorForma: Telheiro

Resposta: Agora se nos referirmos apenas ao telheiro, este deve ser representado no objeto "Edifício" sem valorUtilizacaoAtual, ou seja, não é necessário referir que o telheiro tem essa utilização, e com ValorForma: Telheiro.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento.
