### ISSUE TITLE
Classificação do TipoTrocoRodoviario

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#119]
Bom dia, 

A - Nesta situação apenas devemos representar um seg_via, correto? 
B - Como devemos caraterizar este seg_via, quanto ao tipo de troço? 
•	Trilho ou via em escada?
![image](https://user-images.githubusercontent.com/60113889/150959725-aabf8ddf-7e40-49d3-b2c1-9822263b9b5c.png)

Nós achamos que este seg_via deve ficar caraterizado da seguinte forma: 
valorTipoTrocoRodoviario – trilho
valorTipoCirculacao - Veículo agrícola ou com tração às quatro rodas e Pedonal

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

A - Sim.
B - Via em escada porque é um troço com alguma singularidade. Como não é permitido multiplicidade neste atributo, o "Segmento da via rodoviária" deve apenas ser classificado (quanto ao valorTipoTrocoRodoviario ) como "Via em escada" ao invés de "Trilho").

Quanto ao valorTipoCirculacao, pela imagem, parece que pode ser "Veículo agrícola ou com tração às quatro rodas" e "Pedonal".

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento.
