### ISSUE TITLE
Imagem errada no postes de baixa tensºao

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#12]
Não sei se é o local ideial para reportar este problema, mas nas imagens de postes de baixa tensão, aparece o que aparenta ser um poste telefónico ou de telecomunicações.

http://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVIÇOS%20DE%20INTERESSE%20PÚBLICO/ElemAssocEletricidade.html

http://www.dgterritorio.gov.pt/recart/imagens/fElemAssocEletricidade-valorElementoAssociadoElectricidade7.3-1.jpg

**Comment by aserronha** [comment]
Boa tarde,

É claramente um erro. A imagem em questão já foi removida e, como tal, as outras duas imagens foram renomeadas.

Cumprimentos e obrigado.
