### ISSUE TITLE
Criação de Registo para Acesso na Tabela Via_Rodov

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#120]
#117

Bom dia, 

a) Pensando na parte prática, desta forma teremos de criar novos registos na tabela via_rodov, certo?

b) Qual a melhor forma de criar os registos para situações de acessos:

- b1) “ACSS A22”; “ACSS IP1”; “ACSS E01”

- b2) "ACSS E01/A22/IP1/IC4"

Achamos que a melhor opção seria a b1 por ter mais aplicabilidade.

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

a) Certo.
b) Como é permitida a multiplicidade faz sentido preencher de acordo com b2)

**Comment by aserronha** [comment]
Bom dia,

a) Certo.
b) Como é permitida a multiplicidade faz sentido preencher de acordo com b1)

**Comment by MartaValenteMuni** [comment]
Bom dia,

De acordo com esta issue, significa que os ramos de ligação deixam de ser editados conforme a imagem no dicionário de objetos?
![image](https://user-images.githubusercontent.com/60008526/151350802-afdcd96b-f84f-42fa-aed3-4018595d7652.png)


Isto não cria uma complexidade desnecessária, uma vez que, na óptica do utilizador, é possível identificar facilmente os ramos de ligação e quais os nomes associados?!
Passa então a ser obrigatória a criação dos registos de ACSS? O nome terá que ser "Acesso A22", uma vez que não é permito colocar abreviaturas? Ou poderá continuar a ser feita a ligação com os nomes das vias principais, conforme foi feito até aqui?

**Comment by aserronha** [comment]
Boa tarde,

Após analisarmos melhor a suituação decidimos editar a resposta e sim, concordamos que não deve existir tanta complexidade nos nomes dos ramos de ligação / acessos até porque naõ existe nada definido pelo Instituto da Mobilidade e dos Transportes (IMT).

Sendo assim, como não existe definição quanto aos acessos tanto da parte do Instituto Nacional de Estatística (INE) nem da parte do Instituto da Mobilidade e dos Transportes (IMT) perante os "ramos de ligação / acessos" então, decidimos que os ramos de ligação podem ficar apenas com os nomes das vias rodoviárias ao invés de criar uma abreviatura de acesso com novas nomenclaturas.
