### ISSUE TITLE
Concordância Dicionário de Objetos, Objetos em '.json' e definição BD 'recart.ddl'

### ISSUE THREAD

**Issue by RainIsGood** [dgterritorio/RECART#121]
Existem alguns objetos em que a sua definição difere entre o [Dicionário de Objetos](https://www.dgterritorio.gov.pt/recart), a [Definição dos Objetos em '.json'](https://github.com/dgterritorio/RECART/releases/tag/v1.1.2) e a [definição atual da BD 'recart.ddl'](https://github.com/dgterritorio/RECART/releases/tag/v1.1.2).

Isso levanta algumas questões, colocadas em baixo.

```
[objeto]
NoHidrografico

[atributo]
nome        

- Dicionário de Objetos
(-inexistente-)

- Definição '.json'
(-inexistente-)

- Definição 'recart.ddl'
nome varchar(255)
```

```
[objeto]
SegViaRodov

[atributo]
larguraViaRodov

- Dicionário de Objetos
larguraViaRodov Real

- Definição '.json'
(-inexistente-)

- Definição 'recart.ddl'
largura_via_rodov real
```

```
[objeto]
AreaTrabalho

[atributos]
inicioObjeto 
fimObjeto

- Dicionário de Objetos
inicioObjeto DataTempo
fimObjeto DataTempo

- Definição '.json'
inicioObjeto DataTempo
fimObjeto DataTempo

- Definição 'recart.ddl'
(-inexistente-)
(-inexistente-)
```

```
[objeto]
ElemAssocPGQ

- Dicionário de Objetos
Dimensão 2D

- Definição '.json'
Sem dimensão: "-"

- Definição 'recart.ddl'
Dimensão 2D
```

- Quais as definições que são consideradas certas ?

- Quais as definições que são usadas pela plataforma de homologação para considerar a cartografia válida, o Dicionário de Objetos, a Definição dos Objetos em '.json' ou a definição atual da BD 'recart.ddl' ?

- Quando uma base de dados CarTop, exportada de acordo com o procedimentos/comandos de backup indicados na plataforma de homologação, é colocada na plataforma de homologação, a diferença de nome de algum atributo, ou existência ou não de algum atributo, faz a plataforma não detetar a cartografia ?

- Quando se faz o upload de uma cartografia CarTop na plataforma de homologação, como sabemos no momento, antes de terminar a sessão, se a plataforma detetou ou não uma cartografia ? 

- Se não detetou, como podemos saber tecnicamente qual o motivo da não deteção ?

- Alguns dias depois de feito um upload na plataforma recebemos a indicação de um avaliador da plataforma dizendo que: "A cartografia não é detetável na plataforma. Devem carregar novamente um ficheiro SQL gerado de acordo com o descrito na "Ajuda", questão 6". 
Tendo esta sido produzida de acordo com o descrito, como podemos saber se não é uma destas discrepâncias de nomes e atributos, apresentadas entre as várias definições, que estão a invalidar que seja detetável ou não ?

- É obrigatório para a plataforma os backups binários  .backup  -não serem-  comprimidos num .zip ?

- É obrigatório para a plataforma os backups em texto  .sql  -serem-  comprimidos num .zip ?

Agradecíamos as respostas.

Obrigado.

**Comment by aserronha** [comment]
> Existem alguns objetos em que a sua definição difere entre o [Dicionário de Objetos](https://www.dgterritorio.gov.pt/recart), a [Definição dos Objetos em '.json'](https://github.com/dgterritorio/RECART/releases/tag/v1.1.2) e a [definição atual da BD 'recart.ddl'](https://github.com/dgterritorio/RECART/releases/tag/v1.1.2).
> 
> Isso levanta algumas questões, colocadas em baixo.
> 
> ```
> [objeto]
> NoHidrografico
> 
> [atributo]
> nome        
> 
> - Dicionário de Objetos
> (-inexistente-)
> 
> - Definição '.json'
> (-inexistente-)
> 
> - Definição 'recart.ddl'
> nome varchar(255)
> ```
> 
> ```
> [objeto]
> SegViaRodov
> 
> [atributo]
> larguraViaRodov
> 
> - Dicionário de Objetos
> larguraViaRodov Real
> 
> - Definição '.json'
> (-inexistente-)
> 
> - Definição 'recart.ddl'
> largura_via_rodov real
> ```
> 
> ```
> [objeto]
> AreaTrabalho
> 
> [atributos]
> inicioObjeto 
> fimObjeto
> 
> - Dicionário de Objetos
> inicioObjeto DataTempo
> fimObjeto DataTempo
> 
> - Definição '.json'
> inicioObjeto DataTempo
> fimObjeto DataTempo
> 
> - Definição 'recart.ddl'
> (-inexistente-)
> (-inexistente-)
> ```
> 
> ```
> [objeto]
> ElemAssocPGQ
> 
> - Dicionário de Objetos
> Dimensão 2D
> 
> - Definição '.json'
> Sem dimensão: "-"
> 
> - Definição 'recart.ddl'
> Dimensão 2D
> ```
> 
>     * Quais as definições que são consideradas certas ?
R: Supostamente deveriam estar todas alinhadas mas atenção que nem todas têm os mesmos objetivos e como tal existem algumas nuances porque o dicionário de objetos tem um objetivo distinto dos ficheiros *. json e também do documento escrito das Especificações técnicas (ET) e como é óbvio da própria base de dados (BD) que tem a implementação física do modelo. Se existirem algumas inconsistências por vezes podem ser gralhas e estamos cá para corrigir e não prejudicar quem tenha iniciado um processo de homologação.
> 
>     * Quais as definições que são usadas pela plataforma de homologação para considerar a cartografia válida, o Dicionário de Objetos, a Definição dos Objetos em '.json' ou a definição atual da BD 'recart.ddl' ? 
R: A homologação tem por base tudo isto mas atenção que o documento das ET (e a sua errata em determinada versão) pretende estar alinhado com a respetiva BD estável em vigor para produção. Neste momento (02/02/2022) a versão estável da BD para produção (v1.1.2 2020-07-20) é esta: [(https://github.com/dgterritorio/RECART/releases/tag/v1.1.2)]
Não devem confundir a versão estável com a versão de desenvolvimento, à qual vocês chamam 'recart.ddl' porque aí é onde se vão fazendo as alterações e é onde está o código fonte em desenvolvimento para se criar novas versões da BD sempre que for necessário atualizar alguma coisa.
> 
>     * Quando uma base de dados CarTop, exportada de acordo com o procedimentos/comandos de backup indicados na plataforma de homologação, é colocada na plataforma de homologação, a diferença de nome de algum atributo, ou existência ou não de algum atributo, faz a plataforma não detetar a cartografia ?
R: A recomendação que estamos fazer é para respeitar o que está no Ponto 6 em [(https://homologacao.dgterritorio.gov.pt/app/faq)]. Nos casos em que esta recomendação não é suficiente estamos a tentar avaliar as causas dessa insuficiência no que respeita ao conteúdo dos dados.
> 
>     * Quando se faz o upload de uma cartografia CarTop na plataforma de homologação, como sabemos no momento, antes de terminar a sessão, se a plataforma detetou ou não uma cartografia ?
R: Ir ao menu do lado direito onde está 'Produto' e ver se aparece a "área de trabalho" no mapa. Caso esta "área de trabalho" não apareça no mapa procederemos como exposto na resposta anterior.
> 
>     * Se não detetou, como podemos saber tecnicamente qual o motivo da não deteção ?
R: Podem existir situações que ainda não conseguimos identificar e pode ser necessário alguns ajustes no processo de carregamento da cartografia na plataforma.
> 
>     * Alguns dias depois de feito um upload na plataforma recebemos a indicação de um avaliador da plataforma dizendo que: "A cartografia não é detetável na plataforma. Devem carregar novamente um ficheiro SQL gerado de acordo com o descrito na "Ajuda", questão 6".
>       Tendo esta sido produzida de acordo com o descrito, como podemos saber se não é uma destas discrepâncias de nomes e atributos, apresentadas entre as várias definições, que estão a invalidar que seja detetável ou não ?
R: Ver respostas anteriores.
> 
>     * É obrigatório para a plataforma os backups binários  .backup  -não serem-  comprimidos num .zip ?
R: Ver respostas anteriores.
> 
>     * É obrigatório para a plataforma os backups em texto  .sql  -serem-  comprimidos num .zip ?
R: Ver respostas anteriores.
> 
> 
> Agradecíamos as respostas.
> 
> Obrigado.

Nota: Também queríamos referir que existe um e-mail próprio @homologacao@dgterritorio.pt para questões que tenham a ver com a homologação propriamente dita. Este github tem como principal objetivo disponibilizar toda a informação e esclarecer dúvidas que tenham a ver com as ET.
