### ISSUE TITLE
Linha de fronteira terra-água em ilhas de águas interiores

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#123]
Boa Tarde, 

A representação do objeto fronteira terra-água aplica-se também ao limite das ilhas em águas interiores e no mar. 
Nos casos das rias onde existem ilhas interiores questionamos como devemos representar este objeto? 
a)	Representar todas as ramificações adjacentes ao curso de agua área (linhas a amarelo)?
b)	Não Representar
c)	Outra Sugestão
![image](https://user-images.githubusercontent.com/60113889/153254146-0e891451-ec02-435b-bc8c-ea97a2c2d8f8.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

As ramificações devem ser representadas com algum grau de generalização. Ver esquema em https://www.dgterritorio.gov.pt/recart/imagens/eZonaHumida-valorZonaHumida1-1.jpg 
Por sua vez, esta representação deve ser feita através de vários polígonos mas no objeto [[04.10] Zona húmida](https://www.dgterritorio.gov.pt/recart/HIDROGRAFIA/ZonaHumida.html) com o valor 1 em [valorZonaHumida](https://www.dgterritorio.gov.pt/recart/HIDROGRAFIA/ZonaHumida.html#go_up_valorZonaHumida).
Não há ilhas interiores na imagem, são zonas húmidas que estão cobertas conforme a maré.

No objeto [[04.05] Fronteira terra-água](https://www.dgterritorio.gov.pt/recart/HIDROGRAFIA/FronteiraTerraAgua.html) devem ser representadas as ilhas (exteriores) barreira da Ria Formosa com o valor booleano [ilha](https://www.dgterritorio.gov.pt/recart/HIDROGRAFIA/FronteiraTerraAgua.html#page_ilha) = verdadeiro.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Quando se referem à representação da linha fronteira terra-água das ilhas (exteriores) são as assinaladas pelas setas a vermelho na seguinte imagem?

![image](https://user-images.githubusercontent.com/60113889/155575611-f9ccb2e9-9a8c-4519-b0fc-676d5f8ff7a9.png)

Obrigado,

**Comment by aserronha** [comment]
Exatamente.
