### ISSUE TITLE
Representação das Curvas de Nível em Passagens Inferiores

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#124]
Boa Tarde, 

Nas passagens inferiores a informação é classificada como ilustra a imagem abaixo. 

Os segmentos acima da obra de arte são aqueles que ficam classificados como suspensos ou elevados segundo as normas técnicas.
Contudo se pensarmos a nível altimétrico como devem ficar representadas as curvas de nível nestes casos? 
![image](https://user-images.githubusercontent.com/60113889/153631883-a99aef0c-5423-46e3-b698-7e601073bdb2.png)

Achamos que o correto seria como ilustrado na imagem esquerda. No entanto ao serem representadas desta forma, os segmentos não estão corretamente classificados, sendo que os segmentos que estão suspensos ou elevados deveriam ser considerados como estando ao nível do solo e pelo contrario o segmento abaixo da obra de arte com posição vertical = -1
![image](https://user-images.githubusercontent.com/60113889/153631935-4085eb12-03f1-47e3-bf5b-8ce676b6a784.png)
A imagem da direita ilustra o comportamento das curvas de nível em situações de obras de arte classificadas como Passagens Inferiores de acordo com as normas técnicas.

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Na imagem da direita a altimetria descreve o terreno, logo as curvas de nível que se encontram dos dois lados da via rodoviária que está ao nível do solo, têm de acompanhar as paredes da obra de arte (passagem inferior) e, como tal, estas curvas devem materializar a correta configuração da existência da via rodoviária que está ao nível do solo e não materializar a configuração da via que está suspensa ou elevada.
 
As curvas devem acompanhar o terreno e, ao "abrir-se" a passagem inferior, o terreno passou a ficar mais baixo. É claro que a construção da obra de arte proporcionou à via que já existia anteriormente, a existência de um novo cruzamento desnivelado em que o que interessa efetivamente saber é que a via que passou a ficar suspensa ou elevada, não materializa o terreno.
