### ISSUE TITLE
Continuidade de canais

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#125]
Bom dia,

Como devemos proceder quando existem canais (de irrigação) que não têm continuidade entre si? 
É obrigatório que haja continuidade entre os canais?
Para conseguirmos dar continuidade aos canais temos que “inventar” canais no subsolo – é este o procedimento correto?
Ou como proceder nestas situações?
Obrigada e ficamos a aguardar.

Exemplos:
![image](https://user-images.githubusercontent.com/60008526/154057531-c3041d9f-ee1d-470f-9394-25aa9dd7ea5c.png)

 
![image](https://user-images.githubusercontent.com/60008526/154057571-3bafc0ae-c0d9-471f-acc3-725b81166a06.png)

**Comment by aserronha** [comment]
> Bom dia,
> 
> Como devemos proceder quando existem canais (de irrigação) que não têm continuidade entre si? 
Resposta: Se efetivamente não têm continuidade, não se ligam.

>É obrigatório que haja continuidade entre os canais? Para conseguirmos dar continuidade aos canais temos que “inventar” canais no subsolo – é este o procedimento correto? Ou como proceder nestas situações? Obrigada e ficamos a aguardar.
Resposta: Não é obrigatório que haja continuidade entre os canais. Há situações em que é possível identificar que existem canais que se ligam através do subsolo mas existem outras situações em que os canais estão distantes e não se consegue aferir se existe ligações entre ambos nem saber o seu traçado no subsolo. Nestas condições é possível não haver ligações entre canais.

> Exemplos: ![image](https://user-images.githubusercontent.com/60008526/154057531-c3041d9f-ee1d-470f-9394-25aa9dd7ea5c.png)
> 
> ![image](https://user-images.githubusercontent.com/60008526/154057571-3bafc0ae-c0d9-471f-acc3-725b81166a06.png)

**Comment by vantunes** [comment]
concordo com o [aserronha](https://github.com/aserronha)
