### ISSUE TITLE
Diferença entre Lagoa e Charca

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#126]
Boa Tarde, 

Teoricamente compreendemos o que é uma Charca e uma Lagoa. Entendemos que as lagoas são massas de água que surgem em depressões do terreno e apresentam formas mais regulares enquanto que as charcas são escavações feitas no terreno e com fins agrícolas.

Por forma a entender melhor estes dois conceitos solicitávamos o vosso entendimento sobre estes dois objetos de forma a conseguirmos sermos mais assertivos na distinção destes objetos.

**Colocamos algumas imagens:** 
![image](https://user-images.githubusercontent.com/60113889/154090164-924171ad-361d-4431-b5e7-a2eb97a2519b.png)

Obrigado,

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Sempre que nos é possível e dispomos de informação que nos ajudam na sua classificação temos recorrido a essa informação, inclusive trabalho de campo. No entanto, por vezes é impossível fazer um trabalho de campo exaustivo e mesmo fazendo esse trabalho não conseguimos chegar a um critério que nos ajude na tomada de decisão.

No entanto para a distinção de uma charca de uma lagoa vamos ter em linha de conta o facto se houve ou não intervenção humana.

Obrigado,

**Comment by vantunes** [comment]
A charca é artificial e construida para apoio a agricultura
a Lagoa é natural.
Mas será relevante a classificação para o efeito? não chega ser classificada como massa de água?
Fica a sugestão.

**Comment by aserronha** [comment]
> A charca é artificial e construida para apoio a agricultura a Lagoa é natural. Mas será relevante a classificação para o efeito? não chega ser classificada como massa de água? Fica a sugestão.

Numa próxima versão das especificações técnicas vamos avaliar as implicações e se faz sentido ou não continuar a diferenciar a classificação destas massas de água distintas.
