### ISSUE TITLE
Nó Regulação de Fluxo

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#128]
Bom dia, 

Podem confirmar se tem que se colocar Nó de regulação de fluxo no curso de agua eixo mesmo quando não há interseção entre a barreira e o curso_agua_eixo?

![image](https://user-images.githubusercontent.com/60113889/154955011-295636fe-86f8-46c8-81ca-baf6a7140787.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

O esquema que estava no dicionário de objetos foi melhorado e foram adicionadas mais algumas observações nos vários objetos do tema [04] HIDROGRAFIA.
Introduziram-se também novos esquemas que ajudarão a esclarecer eventuais dúvidas. Podem ver aqui:
https://www.dgterritorio.gov.pt/recart/imagens/eBarreira1.jpg
https://www.dgterritorio.gov.pt/recart/imagens/eBarreira2.jpg
https://www.dgterritorio.gov.pt/recart/imagens/eBarreira3.jpg

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido.

Obrigado pelos esclarecimentos.
