### ISSUE TITLE
Representação de ciclovia em tráfego compartilhado

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#129]
Bom dia,

Como devemos proceder na representação do objeto Segmento da Via Rodoviária nos casos de tráfego compartilhado (ex: Zonas 30)?
Devem ser representados dois Segmentos da Via Rodoviária paralelos ou apenas um eixo? Caso seja apenas um eixo, quais os atributos corretos a colocar?

Exemplo 2 eixos:
![image](https://user-images.githubusercontent.com/60008526/155313579-07f5b74b-d446-49dd-8b16-fa641b8b4326.png)
![image](https://user-images.githubusercontent.com/60008526/155313673-7ded3bbd-1cfd-4e6c-a536-7dcbc3649ae3.png)

**Comment by aserronha** [comment]
Bom dia,

As especificações técnicas têm essa regra específica bem identificada:

![image](https://user-images.githubusercontent.com/46351849/155314518-7b493f66-6cbd-4132-b916-3e318af449a1.png)
