### ISSUE TITLE
Muro/Muralha com largura significativa

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#13]
A única localização para colocação de muros ou muralhas é no objecto Costruções lineares, no entanto, para cartografia de grande escala, parece-nos necessário representar os limites de muros ou muralhas cuja largura é superior a 1 metro (tal como a representação das linhas de água).

No entanto, o objecto ConstruçãoPoligonos não prevê em nenhum dos valores o tipo muro ou muralha.

**Comment by dgterritorio** [comment]
Propositadamente ignoraram-se os limites de muros ou muralhas e considerou-se apenas a sua representação linear (através do seu eixo). Ainda assim existe o atributo “largura” para se adicionar essa informação (de preenchimento não obrigatório na fase de produção dos dados, ou seja, é um atributo para a fase de exploração dos dados).

**Comment by SrNetoChan** [comment]
O problema é que uma muralha é geralmente irregular em termos de largura. Não é suposto que a cartografia homolgada através deste modelo de dados possa vir a ser usada para projectos urbanísticos de grande escala ou de arquitectura? Como podem eles trabalhar sem um definição mais exacta dos limites de um elemento como este?
