### ISSUE TITLE
Lista de Abreviaturas

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#130]
Boa tarde,

Verificámos a falta de algumas abreviaturas que necessitamos para a execução de um projeto, de acordo com informação recebida junto do cliente.

**"Antiga"**
Proposta: ‘ANTGA’

![image](https://user-images.githubusercontent.com/60008526/155718285-0bf4bac5-ab5d-4852-89ea-060462efc792.png)

**"Antigo"**
Proposta: ‘ANTGO’

![image](https://user-images.githubusercontent.com/60008526/155718311-1e974016-dfef-43e1-9e7f-c7c04b6ae50e.png)

**"Prado"**
Proposta ‘PRD’

![image](https://user-images.githubusercontent.com/60008526/155718343-4553b393-c161-42ff-ab92-66fa15c215e7.png)

**"Marginal"**
Proposta ´MARG’

![image](https://user-images.githubusercontent.com/60008526/155718382-56f7db87-1562-47ed-92ce-b22ee095b592.png)

Apesar de estar contemplado "Túnel" na lista, também não existe nenhuma abreviatura no campo "tipo_via_rodov_abv".
**237 	"Túnel"**
Proposta: TUN

![image](https://user-images.githubusercontent.com/60008526/155718693-3704e3bc-f9e3-445f-9543-71bf2f7ade7d.png)

**Comment by aserronha** [comment]
Bom dia,

Só não seguimos a proposta da abreviatura de "Prado". 

Fica da seguinte forma:
313 "Antiga" -> ‘ANTGA’
314 "Antigo" -> ‘ANTGO’
315 "Prado" -> 'PRAD'
316 "Marginal" -> ‘MARG’

237 "Túnel" -> 'TUN'

**Comment by MartaValenteMuni** [comment]
Bom dia,

Verificámos a necessidade de duas novas abreviaturas no Catálogo.

**"Aldeia"**
  
![image](https://user-images.githubusercontent.com/60008526/184327161-79bf34c0-a68a-4651-a2bb-a22fa5fde7eb.png)
![image](https://user-images.githubusercontent.com/60008526/184327172-ec54cda7-6f01-4dd6-a257-0eb1d12167c2.png)

**142 "Canto"**
Apesar de estar contemplado no Catálogo, não existe nenhuma abreviatura no campo "tipo_via_rodov_abv"
![image](https://user-images.githubusercontent.com/60008526/184328248-102c30a4-ac6b-41cb-855a-678bdcce87aa.png)

**Comment by aserronha** [comment]
> Bom dia,
> 
> Verificámos a necessidade de duas novas abreviaturas no Catálogo.
> 
> **"Aldeia"**
> 
> ![image](https://user-images.githubusercontent.com/60008526/184327161-79bf34c0-a68a-4651-a2bb-a22fa5fde7eb.png) ![image](https://user-images.githubusercontent.com/60008526/184327172-ec54cda7-6f01-4dd6-a257-0eb1d12167c2.png)
> 
> **142 "Canto"** Apesar de estar contemplado no Catálogo, não existe nenhuma abreviatura no campo "tipo_via_rodov_abv" ![image](https://user-images.githubusercontent.com/60008526/184328248-102c30a4-ac6b-41cb-855a-678bdcce87aa.png)


Boa tarde,

Vamos proceder à atualização das abreviaturas. Deverão ser utilizadas da seguinte forma:
142 "Canto" -> ‘CTO’
323 "Aldeia" -> ‘ALD’
