### ISSUE TITLE
Plugin de validação disponibilizado pela DGT

### ISSUE THREAD

**Issue by sfran22** [dgterritorio/RECART#131]
Constatámos que o Plugin de validação disponibilizado pela DGT não consegue processar/validar convenientemente os dados em projetos que sejam constituídos por mais do que uma área de trabalho.
Existe alguma previsão para upload de uma nova versão melhorada deste Plugin?
Obrigada

**Comment by aserronha** [comment]
Boa tarde,

A componente de validação do plugin está em contínuo desenvolvimento.

O plugin tem uma página própria no github https://github.com/dgterritorio/recart-plugin onde podem ser reportadas de forma colaborativa todas as dificuldades na sua utilização bem como sugestões ou contributos para a sua melhoria:

https://github.com/dgterritorio/recart-plugin/issues
https://github.com/dgterritorio/recart-plugin/pulls
