### ISSUE TITLE
PGQ - Classificação

### ISSUE THREAD

**Issue by sfran22** [dgterritorio/RECART#132]
Como devem ser classificados os elementos constantes nos dois casos que se apresentam de seguida:
1) 
Poligonos "Rosa"?
Poligonos "brancos"?
Poligono "Vermelho"?
![PQG_Image_1](https://user-images.githubusercontent.com/99874356/156627482-ce66b6c5-106f-4be2-8fe7-80fbdc38a9ec.PNG)
2) 
Poligonos "Laranja"?
Poligonos "rosa"?
Poligono "Vermelho"?
![PQG_Image_2](https://user-images.githubusercontent.com/99874356/156627705-f26aefb2-24c3-458f-8d68-bdba2fe96b92.PNG)

**Comment by sfran22** [comment]
Agradeço desde já os esclarecimentos, porém pergunto ainda:
1)Imagem 2 - Os poligonos rosa representam as estruturas metálicas iguais ás ilustradas no vosso dicionário de sinónimos
(2.4 | Unidade autónoma de gás natural (UAG))
https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocPGQ.html
Estas estruturas não devem ser representadas. Certo?
2)Imagem 1 - Representa a "Cepsa", pelo que o polígono "vermelho" que envolve toda a estrutura, foi representada como uma "área artificializada" do tipo industrial. Este polígono deve também constar como PGQ (1 | Petróleo ou derivados)?Não será considerado erro o fato da mesma geometria constar em duas tabelas distintas?

**Comment by aserronha** [comment]
Boa tarde,

1) Certo.  Afinal já percebemos (imagem 2) que se referem às estruturas metálicas. São vaporizadores: http://pt.industrialgastank.com/vaporizer/ambient-vaporizer/new-condition-atmospheric-vaporizer.html e até à data desta versão das especificações técnicas, são estruturas que não se representam nesta cartografia.

2) Pela imagem apresentada quanto às áreas duplicadas, na realidade podem é ser áreas sobrepostas, podendo ser coincidentes ou não. A área de PGQ pode inserir-se numa zona industrial mais ampla e assim já não são coincidentes. Podem sempre aceder a outra fontes de informação.

**Comment by aserronha** [comment]
@sfran22 como não obtemos feedback vamos encerrar a issue!

**Comment by aserronha** [comment]
@sfran22 para simplificar alguns aspetos de dúvidas nestas matérias resolvemos simplificar as especificações técnicas na versão 2.0 clarificando a representação das áreas apenas nas **áreas artificializadas** e a classificação de elementos que tenham a ver com os “Elemento associado água”, "Elemento associado de petróleo, gás e substâncias químicas" e "Elemento associado de electricidade" de dupla geometria (ponto, polígono) passam a uma única geometria (ponto) sem relações implícitas na Base de dados.
