### ISSUE TITLE
Representação dos Segmentos de Linhas Férreas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#135]
#93
Bom dia, 

Relativamente à representação dos segmentos de linhas férreas, e após os vossos esclarecimentos no Github (“Se já não existem carris não se representa nada”), permanecem algumas dúvidas, pois temos recebido informação contraditória. Podem-nos esclarecer o seguinte:
a)	Geometricamente a linha férrea é sempre representável independentemente do seu estado (desmantelada, em construção, em desuso, projetada ou funcional)?

b)	Se não for para se representar em que momento é aplicado os outros estados, se não existe a representação geométrica da linha férrea (mesmo que nesta fase para o atributo “valorEstadoLinhaFerrea” apenas seja pedido para especificar as vias em construção)?

c)	Quando a infraestrutura existe (ex. estações e apeadeiros), mas já não estão em funcionamento deverá ser feita a representação dos nós vs infraestrutura do transporte férreo? 

A cartografia com este nível de detalhe, entre outras finalidades, é utilizada nos processos de revisão dos PDM. Não existindo a representação dos canais ferroviários (ou existindo a possibilidade de existir uma representação intermitente em função da existência de carris) põe em causa a representação geométrica da respetiva servidão. Adicionalmente o uso destes canais (servidões administrativas) pode ser convertido (ex. ciclovias) sendo este mais um motivo para permanecer a representação geométrica do seu eixo.

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Antes de mais gostaríamos de dizer que estamos a ultimar a próxima versão das especificações técnicas (ET) e para evitar interpretações erradas relativamente a esta matéria, este aspeto vai ser revisto, passando a obrigatórios os seguintes valores:

![image](https://user-images.githubusercontent.com/46351849/160875278-766d9cef-731b-4284-b7f7-bdd5e581a1ee.png)

Se quiserem podem, desde já, aplicar estas classificações, aos dados que estão em trabalho, que até à presente data ainda não são obrigatórios. 

Se assim o fizerem, até é preferível, contribuindo para a uniformização e evolução do modelo na ET que se seguirão.
Então, se houver evidências no terreno que existe uma "representação intermitente da existência de carris" podem representar tudo e classificar a via como "Desmantelada".

--//--

Respondendo concretamente às questões, à luz das ET atuais v1.1 (com a correspondente base de dados v1.1.2) temos a dizer que:

a) É suposto adquirir todas as vias que existem no terreno (ou em construção) e não é suposto classificar-se mais nada no atributo [valorEstadoLinhaFerrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html#page_valorEstadoLinhaFerrea);

b) Se não se representa não é classificável;

c) Só se representam as estações e apeadeiros que estão em funcionamento. Quando um edifício já deixou de ter essa função, já não é uma "estação/apeadeiro" mas sim um “simples” edifício e como tal deixa de fazer sentido aplicar as "possíveis" relações à temática dos transportes.

Nota: O contexto desta abordagem de preenchimento dos atributos obrigatórios da cartografia topográfica até à data destas ET teve em conta o custo/benefício/tempo de produção e alguma simplificação na completagem da aquisição dos dados. 
Há uma divisão entre a fase de produção dos dados para o fim da cartografia topográfica e existe toda uma fase seguinte do ciclo de vida destes dados (que resolvemos chamar “fase de exploração”) que consiste na completagem que as entidades proprietárias queiram dar aos dados de maneira a servir múltiplas finalidades no futuro (sejam elas relativas à temática do ordenamento do território ou relativas a qualquer outra temática).

**Comment by CatarinaGaspar** [comment]
Boas

> Se assim o fizerem, até é preferível, contribuindo para a uniformização e evolução do modelo nas ET que se seguirão (sob a forma de uma nova versão).
> Então, se houver evidências no terreno que existe uma "representação intermitente da existência de carris" podem representar tudo e classificar a via como "Desmantelada".

Nós vamos manter a geometria da linha ferrea e classifica-la como "desmantelada". 

a) Quanto aos nós "passagem de nivel" não são precisos representar, certo?
b) E as linhas ferreas ficam continuas nos locais das antigas passagens de nivel, como ilustrado na imagem abaixo?

![image](https://user-images.githubusercontent.com/60113889/160915875-f0e2758c-bc1b-4c1b-b410-f34eda33669a.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

a) Certo.
b) Seguindo a abordagem que já enunciámos previamente, sim, podem ficar "contínuas", desde que sejam classificadas como "Desmanteladas".

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Obrigado pelo esclarecimento.

Bom trabalho,

**Comment by MartaValenteMuni** [comment]
Bom dia,

Quando estamos perante uma via férrea com representação intermitente e desmantelada sem nome e código da via férrea, como deve ser preenchida a tabela Linha Férrea?

Obrigada.

**Comment by aserronha** [comment]
Bom dia,

A tabela [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html) não necessita de ter nenhum registo "SEM NOME" nem relação estabelecida para os respetivos segmentos do troço em causa, ou seja, se não constar no catálogo [Catálogo das linhas férreas](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/CatalogoDasLinhasFerreas.html) e se efetivamente determinado troço não tiver nenhuma "designação oficial", então não se estabelece nenhuma relação entre o [[05.07] Segmento da via-férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html) e a [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html)

**Comment by aserronha** [comment]
> Bom dia,
> 
> A tabela [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html) não necessita de ter nenhum registo "SEM NOME" nem relação estabelecida para os respetivos segmentos do troço em causa, ou seja, se não constar no catálogo [Catálogo das linhas férreas](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/CatalogoDasLinhasFerreas.html) e se efetivamente determinado troço não tiver nenhuma "designação oficial", então não se estabelece nenhuma relação entre o [[05.07] Segmento da via-férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html) e a [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html)

**Comment by aserronha** [comment]
> Bom dia,
> 
> Quando estamos perante uma via férrea com representação intermitente e desmantelada sem nome e código da via férrea, como deve ser preenchida a tabela Linha Férrea?
> 
> Obrigada.

Bom dia,

A tabela [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html) não necessita de ter nenhum registo "SEM NOME" nem relação estabelecida para os respetivos segmentos do troço em causa, ou seja, se não constar no catálogo [Catálogo das linhas férreas](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/CatalogoDasLinhasFerreas.html) e se efetivamente determinado troço não tiver nenhuma "designação oficial", então não se estabelece nenhuma relação entre o [[05.07] Segmento da via-férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html) e a [[05.05] Linha férrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/LinhaFerrea.html)
