### ISSUE TITLE
Classificar áreas de faixa de gestão de combustível

### ISSUE THREAD

**Issue by martabmatos** [dgterritorio/RECART#136]
Bom dia,

No terreno (imagem em anexo) existem áreas associadas à limpeza de combustível, que neste caso corresponde a faixas de gestão associadas a linhas elétricas.
A dúvida que surgiu - classifica-se como Aceiro? Na nossa perspetiva não constituem vias rodoviárias mas sim áreas de redução de combustível (que não corta-fogos).
![aceiros_duvida](https://user-images.githubusercontent.com/88499637/161526595-f85ce8e6-897d-41ec-b6fc-a0d698b394d0.jpg)

Agradeço a atenção.

**Comment by aserronha** [comment]
Boa tarde,

Definição de "Aceiro" nestas Especificações técnicas - Via que desempenha funções de corta-fogo.

Os aceiros são "Faixas de Gestão de Combustível". Na realidade a função destas faixas nas zonas florestais é de aceiro.
