### ISSUE TITLE
Nó Variação de Fluxo

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#137]
Boa Tarde, 

Segundo a Regra 4.10 é colocado nó de Variação de Fluxo quando existe uma “Zona Húmida” ou “Queda de Água”.

Em que circunstâncias ou o que deve ser tido em conta para a colocação deste nó?

Estávamos a colocar o nó no curso de água-eixo sempre que este “entrava” e “saía” das áreas de zona húmida.

Na imagem abaixo podem-nos dizer onde devem ser colocados os nós de Variação de fluxo?
![image](https://user-images.githubusercontent.com/60113889/161543569-0c443894-3c70-4dc1-a843-f7365d7b4c9a.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Quando dizem "Estávamos a colocar o nó no curso de água-eixo sempre que este “entrava” e “saía” das áreas de zona húmida." podemos dizer que é exatamente isso que é pretendido como parece demonstrar esta zona da imagem apresentada:
![image](https://user-images.githubusercontent.com/46351849/162418705-f3e05846-dd41-400e-a7a4-cbbe3195818b.png)

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido. 

Obrigado,
