### ISSUE TITLE
Representação do objeto “Árvore” 

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#138]
Bom dia, 

Segundo as normas técnicas o valor "Árvore" aplica-se a qualquer tipo de árvore quando não localizada em parques, jardins, áreas desportivas ou áreas agrícolas, florestais ou matos e se a árvore em causa possuir uma copa de diâmetro igual ou superior a 4 metros ou uma altura igual ou superior a 8 metros. 

Mesmo não estando mencionado se devem ser colocadas dentro ou fora de propriedades privadas, não nos parece adequado a aquisição deste valor em propriedades privadas, isto é, a obtenção de árvores em área ajardinada de uma residência por exemplo.

Qual a finalidade da obtenção deste valor? Fará sentido a aquisição de árvores nestes locais?

![image](https://user-images.githubusercontent.com/60113889/161699674-b4974c8e-bb35-4c6a-b378-1a88faa2d1e2.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Como é habitual acontecer na cartografia topográfica, para quase todos os objetos, a definição não estabelece diferença entre localização em propriedades públicas ou privadas. Além do mais estamos a falar de um tipo de objeto que não tem especial dificuldade de recolha se estiver em propriedade mais difícil de aceder. Acresce que só é cartografado se tiver dimensão significativa. A finalidade de representação dos objetos na cartografia topográfica é múltipla, pode ser importante para alguns e não ter interesse para outros.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido. 

Obrigado,
