### ISSUE TITLE
Representação do Objeto Charca

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#140]
#126
Bom dia, 

No dicionário de objetos está a seguinte observação no valor charca: "Reservatório de água escavado no terreno ou situado numa depressão do terreno e localizado exteriormente à linha de água."

Queremos confirmar se o que é pretendido é em situações em que a as aguas lênticas são atravessadas pelo curso de agua eixo tem que ficar como lagoa e não podem ser classificadas como charcas. É essa a lógica?

![image](https://user-images.githubusercontent.com/60113889/164420560-202f2465-908a-4a59-b9b6-db3f7632ebb6.png)

Obrigada,

**Comment by aserronha** [comment]
Bom dia,

Vejam bem a definição de lagoa. Isso não são lagoas. Há tendência em classificar pequenas porções de acumulação de água como lagoa mas esses "bocados" de água ou não se representam ou simplesmente não classifiquem como águas lênticas. Há situações que simplesmente se houver "largura" classifiquem o polígono como "Curso de água - área" e respetivo "Curso de água -eixo". 

Nas linhas de água também não existem charcas. Normalmente as charcas situam-se perto das linhas de água e em alguns há "canalização" para a água ser captada nas albufeiras. Há outras situações que captam água diretamente das albufeiras. E depois há todas as outras situações da definição de charca.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido. 

Para nós, este assunto continua a ser muito subjetivo. 
Consoante algumas dicas vossas estamos a tentar criar alguns critérios para que possamos classificar esta informação de uma forma mais homogênea.

Obrigado,

**Comment by aserronha** [comment]
Entendemos a subjetividade da classificação mas existem as albufeiras, as lagoas, as charcas e as "acumulações de água" de um "Curso de água - eixo" que poderá ser representado por um "Curso de água - área" se tiver largura para tal. 
Se tiverem mais dúvidas também podem contactar a Agência Portuguesa do Ambiente.
