### ISSUE TITLE
Local de Paragem - Linhas ZigZag

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#141]
Bom dia, 

A)	As linhas ZigZag devem ser consideradas infraestrutura do transporte rodoviário – “local de paragem”?

B)	A representação dos limites de vias deve incluir essas áreas?

![image](https://user-images.githubusercontent.com/60113889/171114973-b7aa1480-b1f2-450d-a03d-2630622d2900.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Há situações muito diversas das linhas ZigZag. 

Respondendo concretamente às questões:
A) Sim
B) Depende. A área pode ficar "dentro" ou "fora" dos limites da via consoante o caso. No caso das imagens que apresentam e se dividirmos a imagem em parte 1, parte 2 e parte 3 em que a parte 1 e 3 são a mesma imagem, então podemos afirmar que na parte 1 e 3, a área da infraestrutura se situa "fora" dos limites da via, enquanto que nos casos da parte 2 da imagem, a área da infraestrutura se situa "dentro" dos limites da via:
![image](https://user-images.githubusercontent.com/46351849/171151535-19848b97-e610-4642-abd2-d3dc305fd609.png)

Nota: Tentámos colocar no dicionário algumas imagens que demonstrassem que a [[05.12] Área da infraestrutura de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/AreaInfraTransRodov.html) pode ser representada "dentro" ou "fora" da "área de circulação rodoviária" e, consoante o caso, pode influenciar o limite da via.

Por exemplo, nesta imagem do dicionário https://www.dgterritorio.gov.pt/recart/imagens/eAreaInfraTransRodov4.jpg queremos demonstrar que a sinalização horizontal de ZigZag se enquadra na situação em que o limite da via se situa exteriormente porque a área de circulação rodoviária, ou seja, onde o tráfego efetivamente circula, coincide com a sinalização ZigZag, ou seja, isto:
![image](https://user-images.githubusercontent.com/46351849/171154711-7f5a51f9-3efa-4442-91ca-0b573f3fee27.png)

O caso que apresentam (parte 1 e 3 da imagem) vai mais de encontro a um local de paragem "fora" da zona de circulação do tráfego. Este exemplo demonstra o limite da via a representar em zonas em que os locais de parqueamento (estacionamento) ou de paragem (de autocarros) se situam "fora" dos limites da via:
https://www.dgterritorio.gov.pt/recart/imagens/eAreaInfraTransRodov2.jpg

**Comment by pfteixeira** [comment]
Boa tarde, peço desculpa em intrometer-me na discussão, mas, depois desta troca de mensagem fiquei com dúvidas. Assim, a minha dúvida prende-se com o seguinte:

- Segundo o código da estrada, as linhas em ZigZag indicam zonas de cargas e descargas, como por exemplo em frente a garagens, onde é proibido parar ou estacionar;
![image](https://user-images.githubusercontent.com/82571415/171158285-e97f48e6-9d52-4bda-9ab4-e1d6c58a116d.png)
Neste contexto, e observando a figura de exemplo, neste local não pressupõe a paragem de qualquer transporte rodoviário, pelo que parece-me poder aferir que as linhas zigzag não são por si só uma "infraestrutura do transporte rodoviário – “local de paragem”", a não ser que, existam locais de paragem (devidamente sinalizados) sobrepostos com linhas deste tipo.

**Comment by aserronha** [comment]
> Boa tarde, peço desculpa em intrometer-me na discussão, mas, depois desta troca de mensagem fiquei com dúvidas. Assim, a minha dúvida prende-se com o seguinte:
> 
>     * Segundo o código da estrada, as linhas em ZigZag indicam zonas de cargas e descargas, como por exemplo em frente a garagens, onde é proibido parar ou estacionar;
>       ![image](https://user-images.githubusercontent.com/82571415/171158285-e97f48e6-9d52-4bda-9ab4-e1d6c58a116d.png)
>       Neste contexto, e observando a figura de exemplo, neste local não pressupõe a paragem de qualquer transporte rodoviário, pelo que parece-me poder aferir que as linhas zigzag não são por si só uma "infraestrutura do transporte rodoviário – “local de paragem”", a não ser que, existam locais de paragem (devidamente sinalizados) sobrepostos com linhas deste tipo.

Esta dúvida partiu do pressuposto que a linha ZigZag era a sinalização horizontal de um local de paragem. 

No caso agora apresentado não se aplica o que foi discutido anteriormente. 

Nota: Quando as coisas são escritas dá sempre aso a várias interpretações.
