### ISSUE TITLE
Rede Geodésica Nacional

### ISSUE THREAD

**Issue by bento-martins** [dgterritorio/RECART#143]
Boa tarde,

De acordo com o dicionário de objetos é necessário carregar informação sobre os pontos que fazem parte da Rede Geodésica Nacional, surgindo as seguintes dúvidas:

- Podemos basear os pontos a importar para a Base de Dados de acordo com o serviço WFS disponibilizado pela DGT?

- As imagens apresentados nos campo valorLocalGeodesico e valorOrdem são apenas referentes a vértices geodésicos. Podemos considerar para as marcas de nivelamento, pontos gravimétricos, marégrafos e estações da ReNEP o valor 995 nestes campos?

- Sendo um ponto 3D, que valor consideramos para a cota ortométrica dos pontos gravimétricos?

- Que data colocamos na data de revisão das marcas de nivelamento, pontos gravimétricos e ReNEP? Podemos considerar 2015 para os vértices geodésicos de acordo com o documento disponível em: https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-geodesia/RGN_PTTM06_ETRS89.xls ?

Obrigado

**Comment by aserronha** [comment]
> Boa tarde,
> 
> De acordo com o dicionário de objetos é necessário carregar informação sobre os pontos que fazem parte da Rede Geodésica Nacional, surgindo as seguintes dúvidas:
> 
> * Podemos basear os pontos a importar para a Base de Dados de acordo com o serviço WFS disponibilizado pela DGT?
R: Sim.
> * As imagens apresentados nos campo valorLocalGeodesico e valorOrdem são apenas referentes a vértices geodésicos. Podemos considerar para as marcas de nivelamento, pontos gravimétricos, marégrafos e estações da ReNEP o valor 995 nestes campos?
R: Sim.
> * Sendo um ponto 3D, que valor consideramos para a cota ortométrica dos pontos gravimétricos?
R: Esses sinais geodésicos não devem ser considerados até à versão atual (v1.1.2) das Especificações Técnicas (ET).
> * Que data colocamos na data de revisão das marcas de nivelamento, pontos gravimétricos e ReNEP? Podemos considerar 2015 para os vértices geodésicos de acordo com o documento disponível em: https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-geodesia/RGN_PTTM06_ETRS89.xls ?
R: Esses sinais geodésicos não devem ser considerados até à versão atual (v1.1.2) das Especificações Técnicas (ET). Quanto aos vértices geodésicos a data de revisão é a que estiver associada à data da última revisão da rede disponibilizada pela DGT.
> 
Notas gerais: A DGT está a rever as ET e irá publicar a versão 2.0 que terá algumas alterações relativamente à forma de representação do objeto "Sinal geodésico". Quando for publicada a nova versão será também disponibilizada pela DGT toda a informação necessária para a representação total deste objeto e não apenas dos vértices geodésicos, como atualmente.
> Obrigado

**Comment by aserronha** [comment]
O objeto "Sinal Geodésico" foi revisto e modificado na versão 2.
