### ISSUE TITLE
Designações Locais - valor "serra" para Ndd1

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#144]
Boa Tarde, 

O valor “serra” só esta disponível para o NdD2. 
Não faz sentido este valor também ser adquirido para o NdD1?

![image](https://user-images.githubusercontent.com/60113889/188152075-66e1f0f0-5285-45a1-be34-4f552eeeefb8.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Esse valor não está previsto para NdD1 porque este nível de detalhe aplicar-se-ia a áreas de pequena dimensão.
Para o trabalho em causa, caso se justifique a utilização desse valor, pode ser utilizado apesar de não ser obrigatório.
Na próxima versão das Especificações Técnicas essa questão será revista.

Obrigado!

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Questionámos precisamente por isso, isto é, temos tido projetos ndd1 que se justificaria a aquisição desse valor.

Obrigado,
