### ISSUE TITLE
Aquisição do Valor Margem

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#145]
Bom dia, 
Segundo a definição existente no dicionário de objetos, a margem é “Faixa de terra em contacto com qualquer massa de água”.

Questionamos o seguinte:
1-	Podemos ter duas margens seguidas uma a outra? (ponto1) 

2-	Se não pudermos ter duas margens seguidas, como é indicado na definição, onde devemos fazer os cortes na margem de rocha?
![image](https://user-images.githubusercontent.com/60113889/190107285-60a3b90b-2c23-4453-af25-8d26fb87faab.png)

Obrigado,

**Comment by vantunes** [comment]
Na minha opinião o que define a margem não é o tipo de material que é composta (rocha ou areia) assim deve haver apenas uma linha com a separação agua-terra.

**Comment by aserronha** [comment]
> Na minha opinião o que define a margem não é o tipo de material que é composta (rocha ou areia) assim deve haver apenas uma linha com a separação agua-terra.

O que refere já existe nas Especificações Técnicas no objeto [[04.05] Fronteira terra-água](https://www.dgterritorio.gov.pt/recart/HIDROGRAFIA/FronteiraTerraAgua.html)

**Comment by aserronha** [comment]
> Bom dia, Segundo a definição existente no dicionário de objetos, a margem é “Faixa de terra em contacto com qualquer massa de água”.
> 
> Questionamos o seguinte: 1- Podemos ter duas margens seguidas uma a outra? (ponto1)
> 
> 2- Se não pudermos ter duas margens seguidas, como é indicado na definição, onde devemos fazer os cortes na margem de rocha? ![image](https://user-images.githubusercontent.com/60113889/190107285-60a3b90b-2c23-4453-af25-8d26fb87faab.png)
> 
> Obrigado,

Neste caso concreto, é válida a solução proposta em 1.

Nota: Esta cartografia topográfica, excetuando os limites administrativos, representa o que existe no território.
Existem conceitos legais definidos em Leis (exemplo da [Lei n.º 54/2005])(https://data.dre.pt/eli/lei/54/2005/p/cons/20160823/pt/html)) que deverão ser estabelecidos pelas entidades competentes a partir desta cartografia e de outros elementos que considerem relevantes.

**Comment by CatarinaGaspar** [comment]
Entendido. 

Obrigado pelo esclarecimento.
