### ISSUE TITLE
Local de Paragem - Locais de Cargas e Descargas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#149]
Boa Tarde, 
#141

Devemos considerar as situações ilustradas na imagem abaixo como Local de Paragem?
Quanto ao tipo de serviço, deve ficar como “não aplicável”, uma vez que é para cargas e descargas? Caso não seja este o tipo de serviço a aplicar, qual é o mais adequado?

![image](https://user-images.githubusercontent.com/60113889/197811705-dc36c328-dac2-4b07-9ec1-14bb3d95da26.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

De acordo com o que já tínhamos respondido em #141 essa fotografia parece não ter nada a ver com um "[Local de Paragem](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html#go_up_valorTipoInfraTransRodov)" Nota: Pensamos que as fotografias e esquemas são elucidativas.
A definição de "Local de paragem" é a seguinte: Local de paragem de uma linha de transporte rodoviário.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido e Obrigado,
