### ISSUE TITLE
classificar em AreaAgricolaFlorestalMato como 2.1 ou 2.2? 

### ISSUE THREAD

**Issue by ricardodepinho** [dgterritorio/RECART#15]
https://github.com/dgterritorio/RECART/blob/71db64992d65a71d70347316334e8afcd0562095/objectos/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreaAgricolaFlorestalMato.json#L109

Considerando as duas opções de classificação: AreaAgricolaFlorestalMato

2.1 - Pastagem permanente: Área permanentemente ocupada com vegetação essencialmente do tipo herbácea (cultivada ou natural)

2.2 - Vegetação herbácea natural: Área de vegetação herbácea que se desenvolvem sem adubação, cultivo, sementeira ou drenagem.

Como classificar uma área ocupada com vegetação herbácea natural?

**Comment by dgterritorio** [comment]
Novas definições de Pastagem permanente e Vegetação herbácea natural em
https://github.com/dgterritorio/RECART/commit/66be4da950ff9de7eeab47f5b4c6b9955a571db7
