### ISSUE TITLE
Representação do objeto “Árvore”

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#150]
#138
Bom dia, 

Precisamos de alguns esclarecimentos adicionais acerca da representação do objeto "Árvore".
Algumas situações para tentarmos perceber:
**Representamos as árvores situadas em A e C (logradouro) e não as localizadas em B (quintal)?**
![image](https://user-images.githubusercontent.com/60113889/200294300-4505f17c-449f-4e19-82a4-d9ecc810acbb.png)

**Representamos as árvores situadas em A, B e C?**
![image](https://user-images.githubusercontent.com/60113889/200294332-2eeec856-9170-45cf-864b-a7314ae8178e.png)

**Não representamos as árvores situadas em A, B (jardins)?** 
![image](https://user-images.githubusercontent.com/60113889/200294371-30b8b499-e3a7-4d8b-a523-9b946b61610f.png)

Obrigado,

**Comment by aserronha** [comment]
> #138 Bom dia,

> Precisamos de alguns esclarecimentos adicionais acerca da representação do objeto "Árvore". Algumas situações para tentarmos perceber: **Representamos as árvores situadas em A e C (logradouro) e não as localizadas em B (quintal)?** ![image](https://user-images.githubusercontent.com/60113889/200294300-4505f17c-449f-4e19-82a4-d9ecc810acbb.png)
>
Resposta DGT: De acordo com a própria definição (Árvore de qualquer tipo quando não localizada em parques, jardins, áreas desportivas ou áreas agrícolas, florestais ou matos.) representam as árvores (seja em logradouro ou quintal) desde que cumpram a RE6.7:
![image](https://user-images.githubusercontent.com/46351849/200886947-c78f5a5c-8784-46a5-869d-8af10f9696d1.png)
> 
> **Representamos as árvores situadas em A, B e C?** ![image](https://user-images.githubusercontent.com/60113889/200294332-2eeec856-9170-45cf-864b-a7314ae8178e.png)
>
Resposta DGT: A resposta anterior aplica-se igualmente aqui.
> 
> **Não representamos as árvores situadas em A, B (jardins)?** ![image](https://user-images.githubusercontent.com/60113889/200294371-30b8b499-e3a7-4d8b-a523-9b946b61610f.png)
>
Resposta DGT: Se efetivamente for um jardim e este já estiver representado nos correspondentes objetos, não se representam as árvores em jardins de acordo com a própria definição.
> 
> Obrigado,

Nota: Já tínhamos previamente respondido à mesma questão em #138 como identificaram e bem no início desta issue (problema) porque não há distinção da representação de árvores dentro ou fora de propriedades privadas.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

> Resposta DGT: Se efetivamente for um jardim e este já estiver representado nos correspondentes objetos, não se representam as árvores em jardins de acordo com a própria definição.

@CatarinaGaspar: Não sendo representados os parques, jardins e áreas desportivas, por motivos de não terem área minima de representação, as árvores devem ser representadas nestes locais ou mesmo assim não são de todo para se representar? 

@CatarinaGaspar As árvores dentro de equipamentos coletivos (ex: escolas, hospitais, centros de saúde, etc...) representam-se?

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> > Resposta DGT: Se efetivamente for um jardim e este já estiver representado nos correspondentes objetos, não se representam as árvores em jardins de acordo com a própria definição.
> 
> @CatarinaGaspar: Não sendo representados os parques, jardins e áreas desportivas, por motivos de não terem área minima de representação, as árvores devem ser representadas nestes locais ou mesmo assim não são de todo para se representar?
> 
> @CatarinaGaspar As árvores dentro de equipamentos coletivos (ex: escolas, hospitais, centros de saúde, etc...) representam-se?
> 
> Obrigado,



> Bom dia,
> 
> > Resposta DGT: Se efetivamente for um jardim e este já estiver representado nos correspondentes objetos, não se representam as árvores em jardins de acordo com a própria definição.
> 
> @CatarinaGaspar: Não sendo representados os parques, jardins e áreas desportivas, por motivos de não terem área minima de representação, as árvores devem ser representadas nestes locais ou mesmo assim não são de todo para se representar?
> 
Resposta DGT: Nesses casos, não existindo áreas que representem essa ocupação do espaço, as árvores devem ser representadas individualmente (caso verifiquem a RE6.7).
>
> @CatarinaGaspar As árvores dentro de equipamentos coletivos (ex: escolas, hospitais, centros de saúde, etc...) representam-se?
>
Resposta DGT: Não há nada que não diga que não devem ser representadas nessas áreas, logo são para representar.
> 
> Obrigado,

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Obrigado pelos esclarecimentos.
