### ISSUE TITLE
Representação const_lineares - Sebes

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#151]
Bom dia, 

Qual a representação correta desta situação:
**a - representa-se o muro + sebe?**
![image](https://user-images.githubusercontent.com/60113889/200304476-8baecdf3-d03f-4590-8a9a-d38a93dcfde6.png)

**b - representa-se apenas um deles? qual o criterio de representação?** 

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Para respondermos adequadamente às questões, questionamos novamente se a imagem se refere a uma sebe,

- que existe em cima do muro:
![image](https://user-images.githubusercontent.com/46351849/200869900-3c7bcf85-95fe-4f74-8a4c-41b178b7f83d.png)

-  ou a uma sebe que cresce junto à parte "interior" do muro:
![image](https://user-images.githubusercontent.com/46351849/200873237-0e25021e-c9f4-418e-afe4-e3d6da664f09.png)

**Comment by CatarinaGaspar** [comment]
Boa tarde,

A situação que questionamos é a segunda opção: "sebe que cresce junto à parte "interior" do muro".

A 1º situação que colocaram, sabemos que temos de representar o que tiver maior altura, conforme RE6.2

Obrigado,

**Comment by aserronha** [comment]
> Boa tarde,
> 
> A situação que questionamos é a segunda opção: "sebe que cresce junto à parte "interior" do muro".
> 
> A 1º situação que colocaram, sabemos que temos de representar o que tiver maior altura, conforme RE6.2
> 
> Obrigado,

Boa tarde,

Sem querer generalizar, se os elementos identificados cumprirem a RE6.1 devem ser representados. No NdD1 além da RE6.1 é preciso averiguar a RE6.3.
