### ISSUE TITLE
Representação do nó de infraestrutura em fins de via

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#154]
Bom dia, 

Perante parqueamentos em pracetas, a representação mais correta do nó de infraestrutura é sobre o nó de fim da via (seta a laranja)? 

![image](https://user-images.githubusercontent.com/60113889/201310838-0d3d96ab-65c4-483b-abbd-17b154db4fc0.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Não necessariamente, normalmente é colocado num ponto que faça sentido (por exemplo a meio do segmento entre o nó de fim da via e o nó de junção. Na localização que essa imagem apresenta (triângulo amarelo) também faz sentido. Na RE5.5.9 é dito o ponto mais próximo para que faça sentido a infraestrutura estar nas imediações e não apresente localizações disparatadas, mas o que interessa é que a relação entre os identificadores do(s) nó(s) e da(s) infraestrutura(s) sejam genericamente bem estabelecidas!

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido e obrigado pelo esclarecimento.

Bom trabalho,
