### ISSUE TITLE
Edifício com valorCondicaoConst = Demolido

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#156]
Para o objeto Edifício, como deve ser interpretado/ representado o valorCondicaoConst = Demolido?
Tendo em consideração a definição (Construção demolida já não subsistindo vestígios visíveis):
1. se no momento da aquisição dos dados não existem vestígios visíveis, então o objeto "não existe", significa que não é adquirido.
2. se o objeto foi adquirido e classificado como, por exemplo, Funcional, e posteriormente foi demolido, como se deve atualizar este objeto? O valorCondicaoConst passa de Funcional para Demolido, mas continua a ser representado ou é removido?
3. Em que circunstâncias é que Edifício com valorCondicaoConst = Demolido devem ser visualizados? Coexistem e são visualizados com os restantes?

**Comment by aserronha** [comment]
> Para o objeto Edifício, como deve ser interpretado/ representado o valorCondicaoConst = Demolido? Tendo em consideração a definição (Construção demolida já não subsistindo vestígios visíveis):
> 
> 1. se no momento da aquisição dos dados não existem vestígios visíveis, então o objeto "não existe", significa que não é adquirido.
**Resposta DGT: Como descrito em https://github.com/dgterritorio/RECART/issues/93#issuecomment-1020187308 estas Especificações Técnicas (ET) são para cartografia de finalidade múltipla que representa as características naturais e artificiais do terreno. Por outro lado estas ET contemplam atributos de interesse para dois momentos distintos: produção e exploração/atualização. Na fase de produção são indicados os objetos, atributos e valores de recolha obrigatória (marcados com “x”). Nesta fase, a opção de representação de entidades “não obrigatórias” é da total responsabilidade do proprietário da cartografia. 
A exploração/atualização desta cartografia não está abrangida por estas ET.** 

> 2. se o objeto foi adquirido e classificado como, por exemplo, Funcional, e posteriormente foi demolido, como se deve atualizar este objeto? O valorCondicaoConst passa de Funcional para Demolido, mas continua a ser representado ou é removido?
**Resposta DGT: A exploração/atualização desta cartografia não está abrangida por estas ET.**

> 3. Em que circunstâncias é que Edifício com valorCondicaoConst = Demolido devem ser visualizados? Coexistem e são visualizados com os restantes?
**Resposta DGT: A exploração/atualização desta cartografia não está abrangida por estas ET.**

**Comment by anvpires** [comment]
Obrigado pela resposta.
