### ISSUE TITLE
Classificação Tipo de Troço - vias de acesso a moradores

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#157]
Bom dia, 

Como devem ser classificadas as vias de acesso a moradores, isto é, as vias entre prédios ou de acesso às habitações, quanto ao tipo de troço? Deverão ficar como trilhos ou plenas vias?

**Exemplos das situações a que nos estamos a referir:**
![image](https://user-images.githubusercontent.com/60113889/207314811-d27c16c3-a8d9-4ade-ad67-101c85637f48.png)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Quanto ao tipo de troço as imagens apresentadas parecem ter o enquadramento de "Trilho" nos valores possíveis de preenchimento.

Cumprimentos

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido.

Obrigado,
