### ISSUE TITLE
Aplicação da RE6.1

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#158]
Na execução de um plano de urbanização à escala 1:5000 (NdD2), qual o entendimento da aplicação da Regra Específica 6.1 relativamente à construção linear (muros de alvenaria, na situação específica)?
De acordo com a regra apenas são adquiridos os muros com mais de 3 metros de comprimento e 2 metros de altura e a cartografia será entregue conforme imagem abaixo. Verificamos que estamos perante uma zona habitacional do tipo moradia unifamiliar e onde ficarão representados apenas alguns muros (elementos a amarelo).
Está correta esta análise? Não ficará o cliente com informação em falta para o Plano de Urbanização? 

 
![image](https://user-images.githubusercontent.com/60008526/208419766-fa5aead4-c289-4bd0-8346-639c35c7330d.png)

![image](https://user-images.githubusercontent.com/60008526/208419808-49ba15a4-fb2c-4f58-9b82-990674b560ee.png)

Aguardamos pelo vosso feedback.

**Comment by aserronha** [comment]
Bom dia,

O NdD2 é um modelo que visa uma cobertura geral do território, contribuindo decisivamente para a Base de Dados Nacional de Cartografia (BDNC), devendo apresentar homogeneidade, por isso prever a não representação de objetos de pouca dimensão. 
Para Instrumentos de Gestão Territorial (IGT) o que a lei estabelece é que, em termos de exatidão posicional, a cartografia NdD2 tem exatidões compatíveis com a exatidão exigida para a cartografia base de um Plano de Urbanização (PU), o que não quer dizer que, para determinado PU, o promotor ou a autarquia não ache que é melhor o NdD1. Isso tem que ser avaliado antes de se encomendar a cartografia topográfica. Por exemplo, os Plano Diretor Municipal (PDM) podem ser, tendo em conta apenas a exatidão posicional, elaborados com base na carta 1:25000 mas muitos municípios podem achar que devem usar a 1:10000 (NdD2) porque entendem que, para o PDM, é mais adequado.

**Comment by MartaValenteMuni** [comment]
Boa tarde,

Ainda sobre a aplicação desta regra surgiu a dúvida se na contabilização da altura mínima de 2 metros (no caso do NdD2), numa situação de muro com gradeamento, os 2 metros de altura incluem a vedação e/ou gradeamento por cima do muro ou são apenas referentes à altura do muro.

Exemplos de muros com menos de 2 metros sem contabilizar o gradeamento ou mais de 2 metros contabilizando o gradeamento:
![image](https://github.com/dgterritorio/RECART/assets/60008526/94fda519-fca8-46ac-b66f-f691c51ecb23)

![image](https://github.com/dgterritorio/RECART/assets/60008526/07f2fb8f-5564-4ef0-8968-33a994bd20f2)

Estes muros devem ser representados no NdD2?

Obrigada.

**Comment by aserronha** [comment]
Boa tarde,

Pensamos que é claro que as regras específicas RE6.1 e RE6.2 das Especificações Técnicas (ET), para efeitos de dimensionar em altura, ditam que deve-se contabilizar a totalidade da "Construção linear" (neste caso os 2 metros aplicam-se à totalidade em altura de 1 = Muro de alvenaria ou betão + 4 = Gradeamento ou vedação) e de acordo com a RE6.2 deve-se apenas, como classificação final, atribuir apenas 1 desses 2 valores (ao que tem maior altura) da lista de códigos [valorConstrucaoLinear](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/ConstruLinear.html#page_valorConstrucaoLinear). 

Respondendo à questão "Estes muros devem ser representados no NdD2?" podemos dizer que a forma como a RE6.1 está escrita leva a que seja legítimo dizer-se que, para haver representação, as duas condições têm que se verificar em simultâneo, isto é, se um muro for muito comprido mas com altura abaixo de 2 metros não é representado, ou se for muito alto mas com comprimento abaixo dos 3 metros também não é (isto no NdD2). Pelo contrário se a "Construção linear" for representada deve assumir o valor da porção que tiver maior altura.

Nota: De qualquer das formas, na próxima versão das ET, iremos melhor a forma como está escrita a RE6.2

**Comment by CatarinaGaspar** [comment]
Bom dia, 

No caso do Ndd2, em que a construção linear tem altura e comprimento para serem representados, mas o elemento de maior altura é o gradeamento. 

Essa construção linear é representável como muro, dado que o valor "gradeamento" não existe neste nivel de detalhe?
Ou não é representável de todo.

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> No caso do Ndd2, em que a construção linear tem altura e comprimento para serem representados, mas o elemento de maior altura é o gradeamento.
> 
> Essa construção linear é representável como muro, dado que o valor "gradeamento" não existe neste nivel de detalhe? Ou não é representável de todo.
> 
> Obrigado,


Boa tarde,

Entendemos a questão e para evitar incongruências entre as regras específicas e a questão das obrigatoriedades, já temos tudo tratado para que na próxima versão das especificações técnicas exista a obrigatoriedade de recolha e classificação nos dois níveis de detalhe também para "Sebe", "Gradeamento ou Vedação" e "Portão", para garantir que um elemento que é tão caracterizador do território não fique sem representação após determinada dimensão.

Como estamos perante o preenchimento de um atributo sem multiplicidade e atendendo ao facto de que existem regras específicas de dimensões associadas, para dissipar mais dúvidas relacionadas com a partilha da tipologia dos materiais de construção associados à "Construção linear",  ao invés de preencherem como "Muro de ...", é mais correto preencher já como "Gradeamento ou vedação", apesar de não ser obrigatório.

Cumprimentos

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Para os próximos projetos procederemos como sugerem. No entanto para os projetos em curso não estamos a representar as construções lineares quando o objeto de maior altura não tem classificação no Ndd2.

Obrigado,

**Comment by aserronha** [comment]
Do que foi escrito anteriormente o "Portão" afinal vai manter a não obrigatoriedade de recolha no NdD2.

**Comment by aserronha** [comment]
Boa tarde, 

A representação dos muros e as suas regras específicas foram revistas para NdD1 e NdD2 e constam nas Especificações Técnicas v2.0.2.
