### ISSUE TITLE
Listagem de Abreviaturas

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#159]
Boa tarde,

Verificámos a falta de duas abreviaturas que necessitamos para a execução de um projeto, de acordo com informação recebida junto do cliente.

**“Ruinha”**
 
![image](https://user-images.githubusercontent.com/60008526/209570172-00a439b0-f146-45f0-bc7f-61f079fa1937.png)

**“Terceira Rua”**
 
![image](https://user-images.githubusercontent.com/60008526/209570199-bc6233b1-d9cd-4210-a19a-f457bf28ea36.png)

**Comment by aserronha** [comment]
Boa tarde,

As abreviaturas foram adicionadas.

Obrigado!
