### ISSUE TITLE
Como classificar em valorestadoviarodov uma instalação que esteja funcional?

### ISSUE THREAD

**Issue by ricardodepinho** [dgterritorio/RECART#16]
https://github.com/dgterritorio/RECART/blob/71db64992d65a71d70347316334e8afcd0562095/objectos/TRANSPORTES/Transporte%20rodovi%C3%A1rio/SegViaRodov.json#L137
Dadas as várias opções: valorestadoviarodov
1 - Desmantelada
2 - Em construção
3 - Em desuso
4 - Projetada
Como classificar uma instalação que esteja a funcionar?
Nota: Na versão 0.7 existia a opção: "Funcional" : "A instalação está funcional."

**Comment by dgterritorio** [comment]
O valor "Funcional" foi reposto com uma nova definição e preenchimento obrigatório em https://github.com/dgterritorio/RECART/commit/866af7f58668a18a81bf12a11c487890c16450bc
