### ISSUE TITLE
Casas decimais no script descontinuidades e regra 4_9_1

### ISSUE THREAD

**Issue by sandraedia** [dgterritorio/RECART#160]
Boa tarde,
Ao executar o script para as descontinuidades e a regra 4_9_1  (Plugin recart_DGT) dos objetos 3D resultou um elevado número de erros com grande quantidade de casas decimais (15).  Para corrigir estes “falsos” erros foi alterado na base de dados o número de casas decimais para 3 eliminando assim estes erros. Este foi um procedimento de teste, é uma solução? Podemos aplicar de forma definitiva à base de dados?

![Desc](https://user-images.githubusercontent.com/61501678/212379561-b001504e-a320-47cb-ba8f-0586011e2b64.png)

Obrigada

**Comment by aserronha** [comment]
Boa tarde,

Pedíamos apenas para excluir esta issue deste repositório e colocar a questão antes no repositório do plugin: https://github.com/dgterritorio/recart-plugin/issues 

Obrigado!

**Comment by aserronha** [comment]
Resposta em https://github.com/dgterritorio/recart-plugin/issues/44
