### ISSUE TITLE
Representação Passagem Pedonal

### ISSUE THREAD

**Issue by bento-martins** [dgterritorio/RECART#161]
Boa tarde, 

Estamos com uma dúvida de como representar os seg_via_rodov nas passagens pedonais elevadas. 

É necessário representar todas as rampas da passagem pedonal, mesmo as que se encontram sobrepostas? Sendo um elemento 3D bastará a cota do solo e do topo da obra de arte?

![image](https://user-images.githubusercontent.com/34031305/213240863-465ef871-f79a-4c7f-9568-2158e06f6fa4.png)

Muito obrigado. Continuação de um bom trabalho.

**Comment by aserronha** [comment]
Como não obtivemos mais nenhum feedback vamos encerrar esta issue.
