### ISSUE TITLE
Representação de gasodutos vs oleodutos

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#162]
Boa Tarde, 

Nas situações ilustradas na imagem abaixo, como deve ser representado os gasodutos vs oleodutos? É necessário representar cada oleoduto vs gasoduto individualmente, como ilustrado na imagem? Sendo que é difícil ver o traçado dos oleodutos vs gasodutos.
Como devemos proceder nestas situações?
![image](https://user-images.githubusercontent.com/60113889/214881909-8856a060-583f-4a8e-b955-40ee0d25b9e2.png)
![image](https://user-images.githubusercontent.com/60113889/214881922-fb8d3ca5-da3f-4f17-9b83-aa7a5b25b680.png)

Obrigado,

**Comment by aserronha** [comment]
Resposta DGT: Para o NdD2 pode ser feita uma generalização das várias tubagens (reduzindo por vezes as n tubagens a uma tubagem apenas) para dar uma ideia mais representativa da informação existente nos entrocamentos e cruzamentos existentes entre tubagens.  Para o NdD1 devem representar e detalhar o que for possível de interpretar de acordo com a informação que tiverem disponível de maneira a que faça ter o "maior detalhe possível" nesta representação.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido. Obrigado pelo esclarecimento.
