### ISSUE TITLE
Representação do objecto Comporta

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#163]
Boa Tarde, 

#134

A Barragem do Alqueva tem 2 comportas de meio fundo (seta a vermelho) e 3 de cimo (comportas laterais). 

A) Neste casos, a comporta fica representada:
a) conforme a linha verde
b) ou conforme linha a laranja

![image](https://user-images.githubusercontent.com/60113889/214891873-bf044d3f-6a56-4b8d-bc9f-65d4844eb872.png)

B) Caso não existissem as comportas de meio fundo representavamos na mesma a comporta como ilustrada na imagem pela linha laranja?

C) E nos casos em que só existem comportas de um dos lados, por exemplo a Barragem de Castelo de Bode, apenas tem duas comportas laterais? Nesta situação o curso de água eixo teria de ser desviado, de forma a passar pela comporta lateral ?
![image](https://user-images.githubusercontent.com/60113889/214894142-912bad4f-6c91-43d3-be23-b34953441489.png)

Obrigado,

**Comment by aserronha** [comment]
> Boa Tarde,
> 
> #134
> 
> A Barragem do Alqueva tem 2 comportas de meio fundo (seta a vermelho) e 3 de cimo (comportas laterais).
> 
> A) Neste casos, a comporta fica representada: a) conforme a linha verde b) ou conforme linha a laranja
> ![image](https://user-images.githubusercontent.com/60113889/214891873-bf044d3f-6a56-4b8d-bc9f-65d4844eb872.png)

Resposta DGT: Conforme a linha laranja (independentemente da área que ocupa, do número de comportas individuais
e do nível de detalhe). Para coincidir parcialmente com a representação da barreira da barragem e a comporta devem ser representadas na zona mais a montante. As regras específicas 4.2 e 4.3 com a ajuda dos esquemas tentam elucidar esses aspetos nem sempre de fácil interpretação. Ver os esquemas:

![image](https://user-images.githubusercontent.com/46351849/215541200-cb0a309e-7448-4fcc-8d1f-0209e1baadef.png)

![image](https://user-images.githubusercontent.com/46351849/215544782-be87bcd4-b978-4561-a84c-20f65aebe147.png)

> B) Caso não existissem as comportas de meio fundo representavamos na mesma a comporta como ilustrada na imagem pela linha laranja?

Resposta DGT: Sim, a linha é meramente representativa e abarca toda a área das comportas "visíveis". 

> C) E nos casos em que só existem comportas de um dos lados, por exemplo a Barragem de Castelo de Bode, apenas tem duas comportas laterais? Nesta situação o curso de água eixo teria de ser desviado, de forma a passar pela comporta lateral ? ![image](https://user-images.githubusercontent.com/60113889/214894142-912bad4f-6c91-43d3-be23-b34953441489.png)

Resposta DGT: Se só existirem comportas de um dos lados é desse lado que se representa a linha que identifica as comportas (a 2D) coincidente com a linha que representa a barreira da respetiva barragem (a 2D) ajustando o Curso de água - eixo a esse local de interseção a 2D com o Curso de água - eixo (3D) e o nó de regulação de fluxo (3D).
A jusante das barragens, sempre que possível, o Curso de água - eixo (fictício) deve ser representado a partir do nó de regulação de fluxo até ao descarregador do caudal ecológico, ao invés do descarregador de cheias (zona a verde) e é a partir daí que se deve delimitar o leito que recebe o caudal ecológico (presença de água em contínuo). Ver no esquema a seta azul:

![image](https://user-images.githubusercontent.com/46351849/215540858-93f267a7-5677-43ac-ba51-20b1c6c05b7a.png)

**Comment by aserronha** [comment]
Boa tarde,

@CatarinaGaspar podemos encerrar esta issue? Está tudo esclarecido?

**Comment by CatarinaGaspar** [comment]
Sim entendemos. Pode ser fechada esta issue. Obrigado.
