### ISSUE TITLE
Dificuldade de distinção entre Postes de Fibra Ótica e Postes Telefónicos.

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#165]
Bom dia, 

Ultimamente temos tido muita dificuldade em conseguir distinguir os postes de telefónicos dos postes de fibra ótica. Sendo que na cartografia - ndd1 apenas são para representar os postes de telefónicos. 
A dificuldade prende-se, pelo facto de os mesmos postes serem utilizados para vários tipos de redes de telecomunicações: rede telefone, rede internet e mais recentemente fibra ótica.  

![image](https://user-images.githubusercontent.com/60113889/218443353-a38fb38f-dc99-46c5-956f-2052a6cac897.png)

Temos feito algumas pesquisas e questionado pessoas conhecidas para nos ajudarem sobre este assunto, mas não tem sido fácil. Contudo já percebemos que:
•	Os postes telefónicos são todos em madeira (salvo algumas exceções);
•	Os postes telefónicos em madeira são usados para outras comunicações, distribuição de internet (adsl ou fibra);
•	As caixas instaladas com letras amarelas ou brancas são de distribuição de ADSL (para distribuição a clientes);
•	As caixas instaladas com letras vermelhas são fibra – PDO (para distribuição a clientes)
•	As caixas redondas são apenas de distribuição, mas não comercial (alguns mais antigos ainda da adsl, e alguns mais recentes com letras vermelhas de fibra);

Dado esta dificuldade, não seria preferível em vez de termos que distinguir os postes telefónicos, ser criado um valor que abrangesse todas as situações ex: poste de telecomunicações?
Caso não seja possível a criação de um valor mais genérico, têm conhecimento de alguma fonte que nos possa ajudar sobre este assunto?

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Podem desde já utilizar o valor 1. 'Poste telefónico' para todo o tipo de telecomunicações em [valorElementoAssociadoTelecomunicacoes](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocTelecomunicacoes.html#page_valorElementoAssociadoTelecomunicacoes)

Já tínhamos identificado essa dificuldade no processo de produção e temos tudo preparado para que na próxima versão das ET o valor 1. 'Poste telefónico' fosse substituído para 'Poste' mas fica melhor 'Poste de telecomunicações'. Como tal, voltámos a redefinir este valor em https://github.com/dgterritorio/RECART/commit/6e01128c5a1db4302c5469d9317dc4ffb86f27c3 (Base de dados - versão de desenvolvimento) com uma definição mais abrangente:

![image](https://user-images.githubusercontent.com/46351849/218785438-1e749346-3431-4843-916a-aa76c638846e.png)

**Comment by FGueifao** [comment]
Acho muito bem.
Assim abrange tudo o que é telecomunicações.

De: André Serronha ***@***.***
Enviada: 14 de fevereiro de 2023 15:42
Para: dgterritorio/RECART ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [dgterritorio/RECART] Dificuldade de distinção entre Postes de Fibra Ótica e Postes Telefónicos. (Issue #165)


Boa tarde,

Podem desde já utilizar o valor 1. 'Poste telefónico' para todo o tipo de telecomunicações em valorElementoAssociadoTelecomunicacoes<https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocTelecomunicacoes.html#page_valorElementoAssociadoTelecomunicacoes>

Já tínhamos identificado essa dificuldade no processo de produção e temos tudo preparado para que na próxima versão das ET o valor 1. 'Poste telefónico' fosse substituído para 'Poste' mas fica melhor 'Poste de telecomunicações'. Como tal, voltámos a redefinir este valor em 6e01128<https://github.com/dgterritorio/RECART/commit/6e01128c5a1db4302c5469d9317dc4ffb86f27c3> (Base de dados - versão de desenvolvimento) com uma definição mais abrangente:

[image]<https://user-images.githubusercontent.com/46351849/218785438-1e749346-3431-4843-916a-aa76c638846e.png>
