### ISSUE TITLE
Utilização de Apoios de Baixa Tensão para Outras Redes

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#167]
#165

Bom dia, 

Quando um poste de baixa também é usado pela rede de telefone e de fibra ótica. Devemos colocar:
a) apoio de baixa tensão
b) apoio de baixa tensão + apoio de telecomunicação

![image](https://user-images.githubusercontent.com/60113889/221561504-8a86173c-6503-4bb2-89b8-2d195b1fb838.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Na imagem apresentada parece que também existe simultaneamente apoio para a iluminação. Se efetivamente for isso poderão coincidir planimetricamente e até são 2 objetos diferentes:

c) 6.2 "Apoio de iluminação e baixa tensão" em [valorElementoAssociadoElectricidade](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocEletricidade.html#go_up_valorElementoAssociadoElectricidade)  + 1 "Poste telefónico" (Apoio de telecomunicações) em [valorElementoAssociadoTelecomunicacoes](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocTelecomunicacoes.html#go_up_valorElementoAssociadoTelecomunicacoes)

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 
Entendido. Obrigado
