### ISSUE TITLE
Parqueamentos com carregamento Elétrico

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#168]
Boa Tarde, 

Queremos esclarecer as seguintes situações:

**a)	Como devem ser representados os parqueamentos com lugares de carregamento elétrico?**

1. Isolar os lugares com carregamento elétrico (linhas a azul)
2. Parqueamento continuo em que no tipo de serviço é preenchido com: “carregamento elétrico + estacionamento” (linha verde)

![image](https://user-images.githubusercontent.com/60113889/223135875-c6e95880-0462-45fd-aca9-5a01082c6572.png)

**b)	Relativamente ao ponto de infraestrutura:**

1. Devemos apenas “agregar” os parqueamentos que tenham o mesmo tipo de serviço (pontos a azul)? 
2. Ou podemos “agregar” os parqueamentos que tenham tipo de serviço diferente (ponto rosa)?
![image](https://user-images.githubusercontent.com/60113889/223136029-91e3281d-5d8c-4e60-9c57-5644e2527901.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Embora o modelo permita várias representações, aquela que agrega o estacionamento com 2 serviços (“carregamento elétrico + estacionamento) parece mais ajustado que tenha um ponto de infraestrutura individualizado, enquanto que as outras 2 áreas de estacionamento (imagem de baixo) devem ter apenas um segundo ponto de infraestrutura "partilhado" que têm apenas o mesmo serviço de "Estacionamento", ou seja, em a) representar-se de acordo com 2. e em b) representar-se de acordo com 1.
