### ISSUE TITLE
Como classificar em valorcondicaoconst uma construção que esteja funcional?

### ISSUE THREAD

**Issue by ricardodepinho** [dgterritorio/RECART#17]
https://github.com/dgterritorio/RECART/blob/71db64992d65a71d70347316334e8afcd0562095/objectos/CONSTRU%C3%87%C3%95ES/Edificio.json#L102
Dadas as várias opções: valorcondicaoconst
1 - Demolido
2 - Desafetado
3 - Em construção
4 - Projetado
5 - Ruína
Como classificar uma construção que esteja a funcionar?
Nota: Na versão 0.7 existia a opção: "Funcional" : "A construção está funcional."

**Comment by SrNetoChan** [comment]
Não sendo um campo não obrigatório, será que é de assumir que a construção está funcional se nenhuma das opções for escolhida. Na verdade o não estar preenchido pode ter outra interpretação que é: desconhecido...

**Comment by ricardodepinho** [comment]
Essa é outra dúvida, se "valorCondicaoConst" é ou não de preenchimento obrigatório?
De acordo com a pag. 91 das Normas e Especificações técnicas V1.0:
As definições de ndd estabelecidas para os valores são:
1 - Demolido - ndd1="" , ndd2 = "" 
2 - Desafetado - ndd1="" , ndd2 = "" 
3 - Em construção - ndd1="x" , ndd2 = "x" 
4 - Projetado - ndd1="" , ndd2 = "" 
5 - Ruína - ndd1="x" , ndd2 = "x" 

Como se interpreta isto? que só é obrigatório preencher (em ambos os níveis de detalhe) se estiver em estado de 3 ou 5? nos outros casos não é necessário preencher?

**Comment by ricardodepinho** [comment]
Nas versões anteriores das Normas e Especificações Técnicas, até à [versão V0.7](http://www.dgterritorio.pt/filedownload.aspx?schema=b511271f-54fe-4d21-9657-24580e9b7023&channel=8A3DD3D8-603E-47AA-801A-B20A4FFC9647&content_id=D4E671FD-1CF6-4508-A5A6-F5F300C88111&field=file&lang=pt&ver=1&filetype=pdf&dtestate=2019-03-07120324), pagina 18, eram definidos os "Estereótipo" vazio (Voilable) para garantir que todos os campos eram sempre preenchidos, clarificando sempre as situações com:
995 - não aplicável - não se aplica nenhuma das opções possíveis
996 - desconhecido - o valor correto não é conhecido
997 - não preenchido - a propriedade não faz parte das opções disponíveis, apesar de existir no mundo real
998 - confidencial - o valor pode existir mas é confidencial

Na versão v1.0 esta definição de Voilable desaparece e apenas constam em poucas situações a possibilidade de uso da "995 - não aplicável" nos:
- valorcategoriabitola (pag 90)
- valorlocalgeodesico (pag 99)
- valorordem (pag 101)
- valortipomargem (pag 109)

O desaparecimento da definição de Voidable terá sido por engano ou propositado?

**Comment by dgterritorio** [comment]
O valor "Funcional" foi reposto com uma nova definição e preenchimento obrigatório em https://github.com/dgterritorio/RECART/commit/866af7f58668a18a81bf12a11c487890c16450bc
