### ISSUE TITLE
Construções dentro de Parques de Campismo

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#170]
Boa Tarde, 

**As construções dentro das áreas de Parque de Campismos devem:**

1. Ser todas representadas?

2. Ser representadas apenas as construções principais?

3. Ser representadas apenas as construções mais permanentes? Apesar de existir alguma dificuldade, pela tonalidade da cobertura consegue-se perceber mais ou menos as construções que são fixas. 

4. Caso não seja nenhuma das opções anterior como devemos proceder?

![image](https://user-images.githubusercontent.com/60113889/225105378-5b5665df-3fb7-4d68-893d-2305627f264f.png)

Obrigada,

**Comment by aserronha** [comment]
Viva,

1. Não.

2. Sim.

3. Sim. Devem tentar fazer a análise dessa distinção recorrendo também a dados auxiliares e eventualmente trabalho de campo.

4. Não se aplica.

Nota: A próxima versão das especificações técnicas terá informação mais detalhada sobre estas construções e similares.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido.

Bom trabalho,
