### ISSUE TITLE
Representação dos Ecopontos

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#171]
Boa Tarde, 

Tendo em conta que nem sempre existe uma fixação fisica para os ecopontos e que estes podem estar situados nos mais variados locais da via pública, nomeadamente: no meio da via, em cima de passeios, dentro de áreas de parqueamento. Além de que são objectos que mudam de locais com alguma frequência. 
No nosso entendimento, e até ao momento, apenas estavamos a representar os ecopontos que tinham um fixação fisica. 
No entanto entendemos a importância de representar os ecopontos que não tenham uma fixação fisica. E neste sentido questionamos:

**1.	Em que situação o objeto “ecoponto” deve ser representado?**

- A – Apenas quando há uma fixação física
- B – Todos mesmo quando não têm fixação física?

**2.	Como representar os ecopontos dentro de áreas de parqueamento?**

- A – Pelas linhas a amarelo
- B – Pelas linhas a verde

![image](https://user-images.githubusercontent.com/60113889/227275237-06ac149d-1e90-4f1a-9ed6-18ebc293fe04.png)

- C – As áreas dos ecopontos são subtraídas à dos parqueamentos?

**3.	Como representar os ecopontos no meio da via pública ou em cima do passeio?**
![image](https://user-images.githubusercontent.com/60113889/227275531-374470e4-1ddd-4b3c-af3d-d54884648492.png)

![image](https://user-images.githubusercontent.com/60113889/227275557-f062fe70-9e94-4189-b3d5-e8ba70625ad2.png)

Obrigada,

**Comment by aserronha** [comment]
Viva,

1. B

2. Deve ser representada a área que indicie visualmente que o Ecoponto está presente ou pode vir a estar.
Nota: Na pergunta 2 existe uma alínea c) com uma questão que a resposta pode ser dada dizendo que não é necessário subtrair áreas. As áreas são independentes, de diferentes temas e podem sobrepor-se.

3. Ver respostas anteriores.
Nota: Se as várias áreas forem contíguas (por exemplo: Ecoponto em área reservada + Ecoponto em cima do passeio) e representarem ambas Ecopontos, estas áreas podem ser agregadas numa única área.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido. Iremos proceder em conformidade.

Obrigado,
