### ISSUE TITLE
Representação "Local de Paragem"

### ISSUE THREAD

**Issue by sfrancisco22** [dgterritorio/RECART#173]
Representamos habitualmente como "Local de Paragem" dois tipos de situações:
1) Zonas reservadas a paragem de transportes públicos, assinaladas no chão por sinalização horizontal;
![image](https://user-images.githubusercontent.com/117730699/229867248-f60f6677-a1cc-40bd-bb0a-0581b5f7ac43.png)
2) Zonas reservadas a paragem de transportes públicos, materializadas no terreno por recorte no lancil (paralelo á via);
![image](https://user-images.githubusercontent.com/117730699/229867639-dffc7c05-cb30-4390-a5ca-e62aacf08ded.png)
Questionamos se faz sentido a representação de "Local de Paragem" em frente a um edificio de "Paragem Rodoviária", sem zona reservada, ou seja em que a paragem do transporte público acontece na via pública. Esta pergunta acontece devido ao facto de ter sido colocada a imagem seguinte no dicionário de objectos (descrição  "Local de Paragem")
![image](https://user-images.githubusercontent.com/117730699/229869045-b69eeac0-b89f-41ae-997e-ddd8e0e780d2.png)

**Comment by aserronha** [comment]
Boa tarde,

As situações descritas em 1. (sinalização horizontal) e 2. (delimitação "física") são situações em que é necessário adquirir a respetiva informação da seguinte forma (obrigatoriedade para NdD1): 

-  [[05.13] Infraestrutura de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html) com ligação a

- [[05.12] Área da infraestrutura de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/AreaInfraTransRodov.html) (a área é representada sempre que se verifique a "Regra global 1").



Por outro lado quando junto a um "local de paragem" não se verifica a existência de área(s) reservada(s) para o efeito como em 1. ou 2.  então é necessário adquirir a respetiva informação apenas da seguinte forma (obrigatoriedade para NdD1):

-  [[05.13] Infraestrutura de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html)

**Comment by sfrancisco22** [comment]
Muito obrigada. Está esclarecido.
Cumprimentos

**Comment by aserronha** [comment]
As perguntas não abordam o assunto mas pode-se ainda acrescentar que sempre que estamos perante uma [[05.13] Infraestrutura de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html) é necessário efetuar a correta ligação entre a infraestrutura e o(s) respetivo(s) [[05.14] Nó de transporte rodoviário](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/NoTransRodov.html) 5. Infraestrutura em [valorTipoNoTransRodov](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/NoTransRodov.html#go_up_valorTipoNoTransRodov)
