### ISSUE TITLE
Representação de Cais

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#174]
Boa Tarde, 

As imagens abaixo são referentes a cais. E as estrutura são amovível, pelo que deve ser classificado como pontão.

Como deve ser representado as áreas de cais nestas situações?

![image](https://user-images.githubusercontent.com/60113889/233146721-4a46cc2f-0eb9-4ead-9b1b-899ceaf78484.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Neste assunto sabemos que existem algumas dificuldades na interpretação das especificações técnicas relativamente à temática dos transportes e construções (poligonais).
Assim sendo, queremos elucidar o presente e o futuro das especificações técnicas já que vamos introduzir alguns ajustes no melhoramento destas especificações.

No presente e, recorrendo às atuais especificações técnicas, estas construções devem ser representadas no 2. Pontão em [valorTipoConstrucao](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/ConstruPolig.html#go_up_valorTipoConstrucao)
Podem colocar o [nome](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/ConstruPolig.html#page_nome) dos respetivos pontão/cais como consta nas vossas imagens.
Tudo o que diga respeito a pontão/cais de recreio, sem infraestruturas de transporte e que não são considerados cais de transportes de serviços coletivos com rotas marítimas pré-definidas, não são representados na temática dos transportes. 
Nota: Só as áreas de portos, cais (com infraestruturas de transporte coletivo) ou docas/marinas é que são representadas na temática do transportes em que a área representa o conjunto de ocupação do solo de todas as infraestruturas. O ponto em [[05.11] Infraestrutura de transporte por via navegável](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20por%20via%20naveg%C3%A1vel)/InfraTransViaNavegavel.html) caracteriza a área da infraestrutura.

Agora, relativamente ao futuro e para ajudar a esclarecer as "construções na margem" vai ser introduzido um novo objeto no tema da hidrografia em que algumas coisas representadas nas construções poligonais vão transitar para esse novo objeto.

Entendido?

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Sim entendido. Como referem fica mais fácil a representação dos transportes navegáveis

Obrigado
