### ISSUE TITLE
Nome nas Escapatórias

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#176]
Bom dia, 

As escapatórias das Autoestradas devem:
a)	Ser classificadas como Autoestradas quanto à caraterística física?
b)	Devem ter o nome da autoestrada adjacente ou ficar sem toponimia associada?

![image](https://github.com/dgterritorio/RECART/assets/60113889/e8042db9-39ad-4ad7-87d4-ece5b0ba346e)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Após obtermos alguns esclarecimentos com o Instituto da Mobilidade e dos Transportes I.P. (IMT) decidimos que nesta versão das Especificações Técnicas (ET) devem:

a) Sim. 
Nota aparte: Os esclarecimentos com o IMT também se prenderam com uma nota a uma questão que não foi aqui colocada mas que pretendemos que aqui seja esclarecida quanto ao [valorTipoTrocoRodoviario](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorTipoTrocoRodoviario) que nesta versão deve assumir o valor = "Via de serviço"... mas que na próxima versão das ET haverá um novo valor mais adequado = "Escapatória".

b) Devem ter o nome da autoestrada "adjacente".

Entendido?

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Sim entendido.

Bom trabalho,
