### ISSUE TITLE
Passagem sobre linha de agua/vala

### ISSUE THREAD

**Issue by alexandreSantos1982** [dgterritorio/RECART#178]
Boa tarde,

Tenho uma duvida na representação para NdD2.

Encontrei uma passagem para campo agrícola sobre uma linha de agua ou vala.

Devo representar e se sim em que tema?  "Obra de Arte – Ponte"?, "Obra de Arte – Passagem hidráulica", outro?

![passagem sobre linha de agua](https://github.com/dgterritorio/RECART/assets/136596328/883925ac-9849-4b78-b21c-c4ec3f82400b)

**Comment by aserronha** [comment]
Bom dia,

Parece tratar-se de uma pequena "Obra de arte" com uma área que "parece" inferior aos 20m2 (NdD2), logo se assim for não tem representação. 

A ser representável e partindo do princípio que a linha de água ou vala também o será, é claro que a "passagem" serve de acesso a veículos ao "campo", como se deduz dos traços descontínuos na via. 
Não nos parece a solução construtiva "Passagem hidráulica". Parece-nos que estes casos particulares são de uma pequena "Ponte", levando em linha de conta o que foi dito anteriormente.
