### ISSUE TITLE
Representação de Vias Cicláveis

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#180]
Bom dia, 

Como devemos considerar vias que são clicáveis? Como ciclovias?

Ou estas vias não devem ser classificadas como ciclovias e apenas no tipo de circulação devem ficar classificadas como velocípedes e pedonais?  

Estamos a falar de vias que existem no interior de jardins por exemplo:
![image](https://github.com/dgterritorio/RECART/assets/60113889/7a1683fd-1764-4c0a-9e23-7783f163593c)

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Como devemos considerar vias que são clicáveis? Como ciclovias?

Resposta: Nem sempre. No dicionário de objetos inserimos várias imagens para tentar demonstrar que uma ciclovia é mais diferenciadora e normalmente associada a algum tipo de sinalização vertical e/ou horizontal.
Para estas Especificações Técnicas a "Ciclovia" (Via de comunicação destinada à circulação de 
velocípedes podendo permitir a circulação de pessoas a pé.) pretende alargar a definição mais clássica de espaço destinado especificamente para a circulação de pessoas utilizando bicicletas, já que na verdade existem muitas vias com sinalização de circulação partilhada por pessoas e velocípedes.

> 
> Ou estas vias não devem ser classificadas como ciclovias e apenas no tipo de circulação devem ficar classificadas como velocípedes e pedonais?
> 

Resposta: Atendendo à tipologia de via inserida num Parque urbano parece ser mais apropriado classificar como "Via urbana" com circulação "Pedonal" (DEDICADA à circulação de pessoas a pé) e eventualmente nalguns troços ou até na totalidade, a circulação também ter sido "construída" para ser DEDICADA à circulação de velocípedes (podendo ter multiplicidade n).

Para mais informações podem contactar as Câmaras Municipais para saber as vias classificadas como "Ciclovia".

> Estamos a falar de vias que existem no interior de jardins por exemplo: ![image](https://user-images.githubusercontent.com/60113889/248730712-7a1683fd-1764-4c0a-9e23-7783f163593c.png)
> 
> Obrigado,

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento
