### ISSUE TITLE
Representação de "Telheiros" - Toldos

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#181]
Bom dia, 

Os toldos dos stands automóveis devem ser representados? 
Caso sejam para se representar qual a utilização a colocar – comércio?
![image](https://github.com/dgterritorio/RECART/assets/60113889/d3579caa-8e4b-4b06-970c-c21a25a7f832)

Estas estruturas quando localizadas em estacionamentos de áreas comerciais estamos a representar.
![image](https://github.com/dgterritorio/RECART/assets/60113889/d303e1a8-84c3-4fc7-a83e-ffeaddef4617)

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Os toldos dos stands automóveis devem ser representados? Caso sejam para se representar qual a utilização a colocar –  comércio? 
![image](https://user-images.githubusercontent.com/60113889/251095766-d3579caa-8e4b-4b06-970c-c21a25a7f832.png)
> 

Resposta DGT: Sim, se tiverem dimensões, são para representar. No caso do stand automóvel apresentado o [valorUtilizacaoAtual](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html#page_valorUtilizacaoAtual) Comércio (NdD2) é adequado.

> Estas estruturas quando localizadas em estacionamentos de áreas comerciais estamos a representar. ![image](https://user-images.githubusercontent.com/60113889/251095817-d303e1a8-84c3-4fc7-a83e-ffeaddef4617.png)
> 
Resposta DGT: Nestes casos, de utilização para estacionamento, o [valorUtilizacaoAtual](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html#page_valorUtilizacaoAtual) "Outro - Transportes" é adequado.

> Obrigado,
