### ISSUE TITLE
Classificação da Rede Viária

### ISSUE THREAD

**Issue by sfrancisco22** [dgterritorio/RECART#183]
A Classificação da rede viária apresentada pelos registos das infraestruturas de Portugal, tem um caráter histórico, sendo que em muitos casos, nomeadamente ao nível das Autoestradas identifica como “roadnumber” a designação da Autoestrada em causa e em simultâneo como “road1” “road2” “road3” as designações anteriores, antes desta ser promovida a Autoestrada.
Tendo em conta que a produção de cartografia pressupõe que esta seja atual, pergunto se nestes casos o correto não devia ser considerar apenas a designação da via no presente e/ou se faz sentido acumular ambas as designações, sendo que uma delas ou mais se encontra desatualizada?
A titulo de exemplo considere-se o caso:
A1/IC2 – Onde presentemente não existe ao nível de placas quilométricas ou direcionais, qualquer referência a IC2.
Obrigada

**Comment by aserronha** [comment]
Bom dia @sfrancisco22 ,

A interpretação que fez de que na informação da IP, SA ( https://dados.gov.pt/pt/datasets/rede-rodoviaria-nacional/ )o roadnumber indica o nome da estrada atual e que os campos road1, road2 e road3 são designações anteriores, é incorreta!

Trata-se de níveis hierárquicos da rede, sendo que o roadnumber tem o nível mais importante, o road1 tem o nível seguinte, e assim sucessivamente… Por exemplo, o troço da Ponte Vasco da Gama, provavelmente tem roadnumber=”A12”, road1=”IP1” e road2=”IC1” e nenhuma delas se encontra desatualizada. No entanto, a demarcação quilométrica (ou a sinalização de orientação) considera apenas a designação da estrada de nível superior (mais importante).

Relembramos que este modelo da Base de Dados permite classificar cada "Segmento da via rodoviária" com os n itinerários/nomes que lhe sejam devidos: https://github.com/dgterritorio/RECART/blob/f4f129b718a8b71981363dfc928111f305dd5f81/recart.ddl#L1096
