### ISSUE TITLE
Representação de Infraestruturas rodov sem áreas de infraestrutura

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#184]
#173
Boa Tarde, 

Para as situações em que só existe sinalização vertical de estacionamento autorizado, sem que no pavimento da via esteja demarcado essa área, também devemos apenas representar a infraestrutura como “parqueamento”? Como se faz para as paragens de autocarro quando não tem uma área reservada para o efeito.

![image](https://github.com/dgterritorio/RECART/assets/60113889/3e66754f-a580-4bad-82db-7117032e1825)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde, 

Apesar de não existir sinalização horizontal, sabemos que esta área tem esta função, pelo que deve ser representada, assim como a infraestrutura (ponto) respetiva e consequentemente o nó (infraestrutura) no(s) respetivo(s) "Segmento da via rodoviária".
O limite concreto da área deve ser estimada em articulação com o lancil e a representação do limite da via transitável adjacente (Limite exterior sem berma).

Ao contrário do "Parqueamento" que normalmente tem sempre uma área reservada para o estacionamento mesmo que possa não ter sinalização horizontal, o "Local de paragem" principalmente em meio urbano, por vezes, é apenas definido por sinalização vertical e se assim for o caso, é aceitável que não seja representada a área da infraestrutura. Por sua vez, deve ser sempre representada a infraestrutura (ponto) e consequentemente o nó (infraestrutura) no(s) respetivo(s) "Segmento da via rodoviária".

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendemos.

Contudo, vamos representar as áreas de infraestrutura mediante a orientação dos carros estacionados (estacionamentos longitudinais, oblíquos e perpendiculares) e utilizando as medidas padrão existentes no IMTT. A nível de extensão vamos ter bom senso, porque existem casos mais dúbios de se representar. 

Para estas situações o limite de via também deve excluir a áreas reservada para estacionar  (linha a azul), certo?
![image](https://github.com/dgterritorio/RECART/assets/60113889/b28cff70-324a-4003-9f07-37cef52122a0)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

É exatamente isso tudo que se pretende. No exemplo apresentado a linha azul define o limite da área reservada ao "Parqueamento" e simultaneamente o "Limite exterior sem berma".
