### ISSUE TITLE
Classificação das Ciclovias no cruzamento com Passadeiras

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#185]
Boa Tarde, 

**Como devemos proceder relativamente ao nº de vias e tipo de circulação no cruzamento com nas passadeiras?**

1-	Devemos interromper o segmento no inicio e fim da passadeira (linha a azul) e considerar:
             - **Nº de vias :** 1
             - **Tipo de Circulação:** Velocípedes
         
2-	Devemos não interromper o segmento no cruzamento com as passadeiras e “generalizar” a sua classificação nestes sítios:
            - **Nº de Vias:** 3 (2 vias para bicicleta e 1 via para pedestres)
            - **Tipo de Circulação:** Velocípedes + Pedonal
        
![image](https://github.com/dgterritorio/RECART/assets/60113889/d93f3c00-8db1-4f2f-b618-3f5516c4da05)
![image](https://github.com/dgterritorio/RECART/assets/60113889/4668e612-ace4-4bff-aacd-38e9a62a1e53)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

1- Não entendemos o que poderá originar dúvidas. Se nada mudar em termos de atributos a "ciclovia" continua logo não é necessário interromper no início e fim da passadeira. Só quando os segmentos se "cruzam" que é o que parece que a imagem demonstra com nós de junção quando isso acontece.

2- É exatamente o que se pretende. O(s) segmento(s) da via rodoviária é/são caracterizados por ser(em) uma "ciclovia" (com 3 vias de trânsito não discriminadas com "Tipo de Circulação": Velocípedes + Pedonal) com [valorSentido](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorSentido) = "Duplo"

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Sim entendido.

Obrigado,
