### ISSUE TITLE
Listagem de abreviaturas

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#188]
Bom dia,

De acordo com informação disponibilizada por cliente, necessitávamos que os seguintes tipos de abreviaturas fossem contemplados na listagem:

Serventia
1ª Serventia
2ª Serventia

![image](https://github.com/dgterritorio/RECART/assets/60008526/484757de-0a9c-40da-b2a7-4c1d09ae60ef)

Obrigada.

**Comment by aserronha** [comment]
Boa tarde,

As novas abreviaturas poderão ficar desta forma:

tipoViaRodovC | tipoViaRodovAbv | tipoViaRodovD
329 | SV | Serventia
330 | 1SV | 1ª Serventia
331 | 2SV | 2ª Serventia

Em momento oportuno as abreviaturas serão introduzidas em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html

**Comment by aserronha** [comment]
Abreviaturas introduzidas em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html
