### ISSUE TITLE
Edificios em Ruinas – Existência só das fachadas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#189]
Bom dia, 

Como proceder nos casos de edificios em ruinas, em que no terreno apenas existem as fachadas dos prédios? Em alguns casos é difícil representar a geometria dos edificios.
Neste caso em concreto estamos a basear-nos pelo Geoportal. 
Mas caso não tivéssemos como saber como era a(s) geometria(s) do(s) edificio(s) como devíamos proceder? Estes casos temos de representar os edificios em ruínas?

![image](https://github.com/dgterritorio/RECART/assets/60113889/6f6d6fde-4f6a-4785-acd0-55304408036a)

Obrigado,

**Comment by CatarinaGaspar** [comment]
Bom dia, 

As situações que estamos a reportar são casos onde se vê vestígios das construções, logo entendemos, que estas devam ser representadas. 
No entanto, por vezes as ruinas encontram-se num estado tão degradado que é difícil representar a sua geometria, nomeadamente quando só existe as paredes das fachadas externas e/ou internas dos edificios. 
Contudo temos recorrido às imagens do Google de anos anteriores para perceber como eram os edificios. Agradecemos a dica da plataforma da DGT “Portugal visto do Céu”.
Pelo que entendemos, quando apenas temos apenas as paredes das fachadas ou paredes das divisões internas dos edificios podemos representar como muros, certo?

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,
Entendemos a dificuldade destes casos particulares e também entendemos que o ideal seria terem uma resposta de SIM ou NÃO, mais objetiva, mas muitas vezes não a podemos dar porque não temos os elementos todos para fundamentar uma resposta de SIM/NÃO além de que contextos muito particulares podem levar a interpretações generalizadas.

A "Imagem da Rua" enviada parece ser de várias fachadas que deduzimos que se mantiveram nos limites de uma via rodoviária. Quanto à ruína de cada edifício é necessário analisar. Nesta última questão já perguntam se também é possível seguir o mesmo raciocínio para representar muros em paredes interiores. É necessário avaliar e ter todos os elementos para saber se devem apenas ser representados os edifícios em ruínas (que também têm/tiveram paredes interiores) ou se houve transformações na paisagem em que apenas as fachadas podem ter dado lugar a muros delimitadores. 

O trabalho no local daria certamente resposta a estas questões.

**Comment by CatarinaGaspar** [comment]
Boas Tardes, 

Entendemos. No entanto penso que já percebemos a lógica.

Obrigado e bom trabalho
