### ISSUE TITLE
Omissão do tipo de arteria Passagem - Listagem de Abreviaturas

### ISSUE THREAD

**Issue by pfteixeira** [dgterritorio/RECART#190]
Boa tarde,

O tipo de artéria "Passagem" não se encontra na listagem de abreviaturas.
![image](https://github.com/dgterritorio/RECART/assets/82571415/ec592b1c-bd6a-4fc9-9cb0-60f767178e66)

**Comment by aserronha** [comment]
Boa tarde,

A nova abreviatura poderá ficar desta forma:

tipoViaRodovC | tipoViaRodovAbv | tipoViaRodovD
332 | PASSAG | Passagem

Em momento oportuno a abreviatura será introduzida em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html

**Comment by aserronha** [comment]
Abreviatura introduzida em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html
