### ISSUE TITLE
Representação de Vias Rodoviárias Obstruídas-Fechadas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#191]
Bom dia. 

As vias que se encontram obstruídas devem ser representadas?

![image](https://github.com/dgterritorio/RECART/assets/60113889/2cca70f8-d0f8-4e28-98b9-2e9a292b73fb)

![image](https://github.com/dgterritorio/RECART/assets/60113889/58986cdf-92af-44a6-8b2a-5761696ac0c7)

Obrigada,

**Comment by aserronha** [comment]
Bom dia,

Para estes casos específicos, como a via existe no terreno, deve ser representado o [[05.15] Segmento da via rodoviária](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html) com [valorTipoCirculacao](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorTipoCirculacao) = 'Pedonal'
