### ISSUE TITLE
Representação de LinhasQuebra com Estruturas de Apoio

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#192]
Bom dia, 

Que objetos devem ser representados nas imagens abaixo, Linhas de Quebra e Muros de Suporte? Ou apenas um destes objetos?

Nota: De referir que os muros exigidos no modelo de dados são a 2D.

**Situação1 – Nestes casos consideramos que são Linhas de Quebras e Muros?**

![image](https://github.com/dgterritorio/RECART/assets/60113889/73872346-3af4-45ad-a5a7-3ba3b2b23f00)

**Situação 2 – Nestes casos ficam apenas como muro de suporte?**

![image](https://github.com/dgterritorio/RECART/assets/60113889/cf5bcc13-c552-4125-8fd6-926a22c18989)

**É este o entendimento? Caso não seja, como proceder?**

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Os objetos Linhas de Quebra e Construção Linear pertencem a temas distintos pelo que a sua representação é independente.
A construção linear deve apresentar o atributo suporte como verdadeiro caso esta estrutura desempenhe essa função.

Se, para a correta definição do relevo, for necessário considerar uma linha de quebra que permita modelar o terreno de forma mais eficaz, através da identificação do seu topo e da sua base, esta deve ser representada, independentemente de coincidir ou não com outro objeto.

**Comment by CatarinaGaspar** [comment]
Bom dia,
 
Entendemos a lógica.

Obrigada,
