### ISSUE TITLE
Representação de Edificios WC

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#193]
Bom dia, 

Segundo as ET o valor “Sanitário público” – Mobiliário Urbano e Sinalização, não é de representação obrigatória. 
No entanto, no trabalho que estamos a executar, estes edificios têm alguma dimensão. Estes edificios não devem ser representados, segundo as normas?

Exemplo de duas situações:
![image](https://github.com/dgterritorio/RECART/assets/60113889/f9081fbe-f2a8-42a7-9dd9-3d2f4aef6b97)

![image](https://github.com/dgterritorio/RECART/assets/60113889/fb329e1b-f300-4cbc-894a-9484f7dc9b6a)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Os 'WC/Sanitários Públicos' devem ser representados nos Edifícios com [valorUtilizacaoAtual](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html#go_up_valorUtilizacaoAtual) = '7.3 Outros - Serviços'.

Os sanitários públicos do tema [[09.01] Mobiliário Urbano e sinalização](https://www.dgterritorio.gov.pt/recart/MOBILI%C3%81RIO%20URBANO%20E%20SINALIZA%C3%87%C3%83O/MobUrbanoSinal.html) tinham outro propósito e não irão constar na lista de valores, na próxima versão das Especificações Técnicas, sendo todos os WC/Sanitários públicos representados apenas no objeto [[06.03] Edifício](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html) da forma já descrita.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Obrigado pelo esclarecimento, 

Bom trabalho
