### ISSUE TITLE
Representação de Passeios e Vias Rodoviárias

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#194]
Boa tarde,

Estamos a efetuar um projeto onde o cliente pediu o objeto adicional "Passeio".

1. Quando estamos perante uma via pedonal com delimitação da via rodoviária - limite, esta deve ser coincidente com o Passeio e serem representados os 3 objetos (construção poligonal, segmento da via rodoviária e via rodoviária - limite) ou nestes casos a prioridade é a via rodoviária?

Exemplos:
![image](https://github.com/dgterritorio/RECART/assets/60008526/57baeb7c-4f79-4878-b234-8c54690e470a)

![image](https://github.com/dgterritorio/RECART/assets/60008526/46a8fc1d-d013-4bd0-976b-eb7ec6452cfb)

2. Quando estamos perante uma zona de passeio onde há coexistência de veículos e peões, o passeio deve ser representado por cima da via rodoviária ou interrompido?

Exemplos:
![Screenshot_2](https://github.com/dgterritorio/RECART/assets/60008526/b4a77e28-810e-4a76-931c-e32d905fd916)

![image (1)](https://github.com/dgterritorio/RECART/assets/60008526/91ee0496-bc99-4d2a-8986-da3612741c19)

Obrigada.

**Comment by aserronha** [comment]
Boa tarde,
 
Percebemos a dificuldade em contexto urbano da representação dos objetos de diferentes temáticas, contudo:
 
1 - Não há prioridades. Os objetos podem coexistir em simultâneo (representados em temas/objetos diferentes). 
Nota: Convém referir que muitos passeios não constituem “vias” em zonas pedestres. Interessa representar as "vias" (pelo seu segmento e eventualmente limites se a regra da largura for cumprida) que simultaneamente acabaram por utilizar passeios que se encontram bem delimitados. É a sinalização horizontal e vertical e alguns elementos físicos no terreno que muitas vezes delimitam a coexistência entre vias e passeio. Quanto ao conceito de “via pedonal” só interessa representar "em passeio" aquelas que tenham um carácter "dedicado" ([valorTipoCirculacao](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorTipoCirculacao)). 
 
2 – Utilizando a linguagem apresentada, “o passeio deve ser representado por cima da via rodoviária” e como tal “não necessita de ser interrompido”. Os objetos coexistem em temas diferentes.

Esperamos que o esquema seguinte ajude a elucidar as imagens apresentadas:
![image](https://github.com/dgterritorio/RECART/assets/46351849/44954b86-a7b1-4ae0-a5aa-86692adfebbe)
