### ISSUE TITLE
Pedidos de escalas pelos clientes

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#197]
Boa tarde,

No caso dos clientes pedirem especificamente escala 1:500 ou 1:1000, como respeitar o detalhe pretendido pelos mesmos e, ao mesmo tempo, as normas e especificações para o NdD1? Falamos, por exemplo, de áreas mínimas de representação.

Obrigada

**Comment by aserronha** [comment]
Boa tarde,

Os parâmetros de dimensão mínima definidos para o NdD1 enquadram-se na representação à escala 1:1000. Logo as dimensões mínimas definidas para este nível de detalhe devem ser mantidas. 

Já para os parâmetros de exatidão, apesar de os valores indicados no NdD1 serem perfeitamente aceitáveis na escala 1:1000, convém referir que estes parâmetros são indicadores de tolerância mínima, podendo-se optar num determinado projeto por valores inferiores, mais exigentes a definir pelo proprietário. A próxima versão das especificações técnicas fará uma diferenciação entre escalas do mesmo nível de detalhe.

Também para a escala 1:1000 pode-se utilizar um adensamento de curvas de nível, de metro a metro, para uma melhor definição altimétrica utilizando para isso as curvas de nível auxiliares.

No que respeita a escalas maiores que 1:1000 (cartografia de projeto), devemos ter presente que estas escalas não se enquadram no conceito desta cartografia topográfica, logo não têm que ser produzidas com estas normas e especificações técnicas.
