### ISSUE TITLE
Área Artificializada - Equipamentos de Educação

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#199]
Boa tarde,

Gostaríamos de confirmar que áreas de edifícios dedicados à investigação científica devem ter uma área artificializada do tipo Equipamentos de Educação.
Exemplo: Instituto Gulbenkian de Ciência
![image](https://github.com/dgterritorio/RECART/assets/60008526/f0f7511e-ffb0-46e1-8b32-1c8bf76f9d20)

Obrigada

**Comment by aserronha** [comment]
Bom dia,

Como os equipamentos de investigação científica se enquadram em valor 1.3 "Ensino superior e investigação" da lista de códigos [valorTipoEquipamentoColetivo](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/EquipUtilColetiva.html#page_valorTipoEquipamentoColetivo) dos equipamentos de utilização coletiva,
a caracterização da área artificializada respetiva na lista de códigos [valorAreasArtificializadas](https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreasArtificializadas.html#page_valorAreasArtificializadas) 2 "Equipamentos de educação" é a mais adequada.

Foram obtidos os esclarecimentos?

**Comment by MartaValenteMuni** [comment]
Certo.

Obrigada
