### ISSUE TITLE
Hortas Comunitárias

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#200]
Boa tarde,

Como devem ser representadas as Hortas Comunitárias? Apenas com o polígono de área agrícola, florestal e mato (Agricultura em NdD1) ou com área artificializada e respetivo equipamento de Área Verde? Ou, eventualmente, outra situação?

![image](https://github.com/dgterritorio/RECART/assets/60008526/88e6d0d5-ed5f-43d9-aae0-1907393f9bfa)

![image](https://github.com/dgterritorio/RECART/assets/60008526/a1702955-4798-4aba-841c-e079c49bc78c)

Obrigada,

**Comment by aserronha** [comment]
Boa tarde,

Resposta DGT: As hortas, quer sejam de uso comunitário ou individual, são “Área agrícola, florestal ou mato” com:
“valorAreasAgricolasFlorestaisMatos” = 1 "Agricultura" (NdD1)
“valorAreasAgricolasFlorestaisMatos” = 1.1 "Cultura temporária de sequeiro e regadio" (NdD2)

**que são representáveis se cumprirem as Regras Específicas (RE) do tema Ocupação do Solo.**
