### ISSUE TITLE
RE5.5.2 e 	Limite exterior com berma pavimentada

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#202]
Boa tarde,

Numa situação em que são adquiridos (a pedido do cliente), no objeto Via Rodoviária - Limite, o limite exterior sem berma e o limite exterior com berma pavimentada, como devem ser interrompidos os mesmos?
Apenas nas situações descritas na RE5.5.2 ou também sempre haja interseção de 3 ou mais linhas?

Exemplo:
![image](https://github.com/dgterritorio/RECART/assets/60008526/759ba5df-3aeb-4aec-8cd2-49d65a780860)

![image](https://github.com/dgterritorio/RECART/assets/60008526/3eef88c5-8416-4a63-ba4c-1115e6c40ed6)

Obrigada,

**Comment by aserronha** [comment]
Boa tarde,

A RE5.5.2 indica que a A “Via rodoviária - Limite” é interrompida nas mesmas condições do “Segmento da via rodoviária”.

Não entendemos a questão "... ou também sempre haja interseção de 3 ou mais linhas?" Do que entendemos da 1ª imagem e a questão "Deve estar partido?" questionamos, deve estar partido porquê se a linha a cinzento escuro teria que terminar nas setas... O mesmo se aplica à 2ª imagem em que a linha a amarelo devia ser um prolongamento (não há motivo para partir) da linha a branco... A linha a cinzento nesta 2ª imagem simplesmente termina na zona da seta.

Nota: Não há nós sobre as linhas da "Via rodoviária - Limite" (sejam esses [valorTipoLimite](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/ViaRodovLimite.html#go_up_valorTipoLimite) "Limite exterior sem berma" ou "Limite exterior com berma pavimentada". 
Não podem existir em simultâneo linhas representadas no mesmo espaço, ou seja, se um limite for "Limite exterior sem berma" nunca será coincidente no mesmo espaço geométrico com o que na mesma "Via" será o seu "Limite exterior com berma pavimentada". 

@MartaValenteMuni será que foi perceptível?

**Comment by aserronha** [comment]
@MartaValenteMuni devido à ausência de feedback a "issue" foi encerrada.
