### ISSUE TITLE
O uso do schema public é obrigatório?

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#203]
Tendo em conta algumas das características do schema public:
- como o nome indica é um schema que todos os users têm acesso e até à versão 15 todos os utilizadores conseguem criar novas tabelas.
- é o schema onde são guardadas as funções, datatypes e tabelas referentes ao PostGIS e outras extensões, como o uuid-oss
- é schema onde são guardadas funções de outros sistemas como o Kart (versionamento)

Pergunto se para a @dgterritorio em termos de homologação, é obrigatório que o dados estejam no schema public, ou podem ser entregues noutros schemas.

Na prática, a não obrigatoriedade abriria a porta a guardar mais do que um projecto ou versões de um projecto na mesma base de dados, podendo, antes de efectuar o backup eliminar os schemas desnecessários. E Tornaria mais fácil a utilização de sistemas de versionamento como por exemplo o kart.

Obrigado

**Comment by dgterritorio** [comment]
Notar que o schema "public" não permite a visualização do conteúdo das tabelas ou vistas a utilizadores que não tenham privilégios  específicos, portanto os dados que estão neste schema não são propriamente públicos.

Admitimos que, em termos operacionais, a não obrigatoriedade dos dados estarem no schema "public" poderia facilitar o trabalho, nomeadamente na gestão das versões.

No entanto, em termos da homologação, todo o workflow de submissão dos processos, validação, etc. está baseado no schema "public" não estando prevista qualquer alteração neste sentido.

**Comment by SrNetoChan** [comment]
Percebido. Ainda assim, estariam abertos a um Pull Request no âmbito de tornar o recart.ddl menos dependente do schema public? Isto é, por omissão seria usado o schema public, mas tornar o script genérico (sem referências ao schema).

**Comment by dgterritorio** [comment]
Sim, pode fazer o Pull Request. 

Obrigado pela colaboração.
