### ISSUE TITLE
Classificação de Canaviais

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#205]
Boas Tardes, 

Os canaviais devem ser classificados no tema de ocupação de uso do solo?
Se sim, qual a classificação que devemos utilizar no Ndd1 e Ndd2?

![image](https://github.com/dgterritorio/RECART/assets/60113889/e938bd3d-335e-453b-9a43-91eca4d0ad7d)

Obrigada,

**Comment by aserronha** [comment]
Boa tarde,

Sim.
A interpretação da DGT e do ICNF sobre esta questão é que devem ser classificados como #5 Mato em [valorAreasAgricolasFlorestaisMatos](https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreaAgricolaFlorestalMato.html#page_valorAreasAgricolasFlorestaisMatos). O SMOS passará a classificar estas áreas desta forma.

Cumprimentos.

**Comment by aserronha** [comment]
@CatarinaGaspar está esclarecido para podermos encerrar a issue?

**Comment by CatarinaGaspar** [comment]
Sim, está esclarecido.

Obrigado,
