### ISSUE TITLE
Classificação de Zonas Industriais

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#206]
Boas Tardes, 

Segundo a CM a área industrial dos Riachos é a delimitada pela linha a azul. Sendo que neste perímetro estão incluídas casas residenciais e áreas agrícolas.
A nossa questão prende-se em saber se devemos representar a área artificializada – “equipamentos industriais” como ilustra a imagem ou se a delimitação deverá ser apenas o que já existe no terreno (área ocupada) e não a projetada. Visto que se representarmos a Zona Industrial por este limite, não devemos representar as áreas de ocupação de uso do solo no seu interior.

![image](https://github.com/dgterritorio/RECART/assets/60113889/52f23888-4b43-4982-baf8-2f054722fd17)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

A cartografia topográfica não representa os planos, apresenta as evidências à data de aquisição dos dados.
