### ISSUE TITLE
Representação do objeto Ecoponto

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#208]
Boa Tarde,

Uma vez que no conceito de “ecoponto” (elemento obrigatório) não devem ser incluídos os contentores relativos ao lixo indiferenciado porque estes devem ser representados como “contentor” (elemento não obrigatório), como devemos representar os “ecopontos” nas seguintes imagens:

 **A) Se não tiverem área mínima de representação devemos colocar 2 pontos (pintas a amarelo)?**
![image](https://github.com/dgterritorio/RECART/assets/60113889/39887641-6f02-45cd-83e6-435f7f28857b)

**B) Se tiverem áreas mínima de representação devemos representar pela:**
        1. linha verde? Se for por esta devemos colocar um ponto no ecoponto do óleo, certo?
        2. linha vermelha? Se for por esta devemos também incluir o ecoponto do óleo, certo?
![image](https://github.com/dgterritorio/RECART/assets/60113889/3a6e20cd-3891-4e34-9441-bb733a2e4e4c)

**C)	Nas imagens seguintes devemos excluir o contentor referente ao lixo orgânico?**
![image](https://github.com/dgterritorio/RECART/assets/60113889/49a8cb1a-4fb6-474c-9e7d-728e554cb840)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Ao analisarmos também a issue https://github.com/dgterritorio/RECART/issues/171 a nossa resposta é agora dada no sentido de simplificar a aquisição destes conjuntos de recetáculos de lixo diferenciado para reciclagem ou lixo indiferenciado.

Como existem casos muito particulares de configurações de "Ecopontos" (de lixo diferenciado) misturados ou não com "Contentores" (de lixo indiferenciado) que podem ou não uma ter uma fixação física então é preferível representar estes elementos sempre como:
- 1 único ponto (colocado da forma mais abrangente possível) para caracterizar o recetáculo ou conjunto de recetáculos de "Ecoponto" ao local, delimitado ou não no solo, onde se encontram instalados um ou vários contentores para recolha diferenciada de resíduos para reciclagem (papelão, vidrão, embalão, pilhão, óleão, roupão, eletrão, lixo orgânico ou outros semelhantes);
-  1 único ponto (colocado da forma mais abrangente possível) para caracterizar o recetáculo ou conjunto de recetáculos de "Contentor" ao local, delimitado ou não no solo, onde se encontram instalados um ou vários contentores que se destinam apenas à recolha de resíduos indiferenciados, vulgarmente designado por lixo doméstico não reciclável.

A) Apenas 1 ponto colocado no local/área que abranja os 3 recetáculos de lixo diferenciado (apesar da configuração não ser em contínuo já que pelo meio existe um "Contentor" de lixo indiferenciado). 
Apesar de não ser obrigatório recolher o "Contentor", se o forem fazer, devem colocar apenas 1 ponto no local/área que abranja esse recetáculo de lixo diferenciado (apesar de pelo meio existir um "Ecoponto" de lixo diferenciado). 
![image](https://github.com/dgterritorio/RECART/assets/46351849/b62deef7-f280-4690-96cd-41d5f18d8c04)


B) Aplica-se o mesmo princípio para recolher 1 único ponto ("Ecoponto") abrangendo agora 5 recetáculos de lixo diferenciado + 1 único ponto ("Contentor") abrangendo 1 recetáculo de lixo indiferenciado.
![image](https://github.com/dgterritorio/RECART/assets/46351849/a9146fcc-6891-48ed-9c13-91cbbca39271)


C) Entenda-se lixo orgânico como um resíduo diferenciado (faz parte dos elementos do Ecoponto). Se queriam dizer "Lixo indiferenciado" podemos dizer que aplica-se o mesmo princípio das alíneas anteriores.
![image](https://github.com/dgterritorio/RECART/assets/46351849/a572e976-b359-453d-94c0-3383de20f0ed)

**Comment by CatarinaGaspar** [comment]
Boas, 

Estamos esclarecidos relativamente a este assunto.

Obrigado,
