### ISSUE TITLE
Representação dos Edificios

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#209]
Bom Dia, 

**Qual o critério ou lógica que deve ser usado(a) na delimitação geométrica dos Edificios?**

Entendemos que o edifico deve ser representado geometricamente por um poligono, mesmo que este seja composto por telhados de várias alturas. 

Na sua representação também temos tido em conta outros indícios que nos ajudam a identificar a delimitação geométrica dos edificios, nomeadamente: juntas/apegamentos dos edificios, telhados e caleiras. 

Há casos em que é difícil conseguirmos perceber a divisão dos edificios, principalmente quanto estamos perante prédios em áreas antigas das cidades. Os prédios vistos de cima dão a entender que devem ser divididos, mas ao analisarmos as suas fachadas já nos parece que deviam ser apenas um só edificio.

**Para entendermos o conceito, colocamos de seguidas algumas situações:**
**Situação 1 -** Estação de Campanhã
![image](https://github.com/dgterritorio/RECART/assets/60113889/712e03be-b2f7-445c-a250-e8ca0d7f662a)

**Situação 2 –** Edificio da Direita (linha a Vermelha)
 ![image](https://github.com/dgterritorio/RECART/assets/60113889/8bc88343-4009-4dcf-b916-008ac79c90d6)

**Situação 3 –** Edificio do Meio (linha a Amarela) 
![image](https://github.com/dgterritorio/RECART/assets/60113889/26194233-11a1-4b58-ba56-6a8b9d86f1e2)

Obrigado,

**Comment by aserronha** [comment]
Concordamos com a abordagem que cada edifício com uma identidade arquitetónica bem definida, por exemplo olhando as fachadas, deve ser representado como um único edifício.

Resposta à situação 1): Um polígono só. 
Resposta à situação 2): No edifício da linha vermelha, parece ser um único polígono já que não é possível diferenciar, na fachada, qualquer divisão através das "juntas/apegamentos ou caleiras", que eventualmente pudessem existir. No caso do edifício ter várias utilizações e números de polícia, estes devem ser contemplados dentro da lógica definida no modelo de dados.
Resposta à situação 3): Aplica-se o mesmo que na resposta anterior.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Quando mencionam que "No caso do edifício ter várias utilizações e números de polícia, estes devem ser contemplados dentro da lógica definida no modelo de dados.", querem dizer que devem ser adicionadas tantas utilização quantas existirem nesse(s) edificios, bem como, se existirem vários números de polícia, estes devem ser todos colocados (ficaria um edificio ligado a vários números de policia), certo?

Obrigado,

**Comment by CatarinaGaspar** [comment]
Boas, 

Estamos esclarecidos.

Obrigado e Bom trabalho,
