### ISSUE TITLE
Trigger de verificação errado para tabela curso de água

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#21]
A tabela curso de água tem um trigger associado para validar sem a geometria é uma linha ou um polígono. No entanto, na versão mais recente da base de dados esta tabela apenas suporta linhas.

Ainda assim, o trigger persiste.

Para além disso, o trigger está errado, não existem geometrias do tipo ST_Line, mas sim do tipo ST_LineString

https://github.com/dgterritorio/RECART/blob/master/recart.ddl#L1477

Sugiro que o trigger seja removido, já não faz sentido.

**Comment by dgterritorio** [comment]
Feito!
Obrigado pela indicação.
