### ISSUE TITLE
Representação de Elementos Associados à Eletricidade

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#210]
Bom Dia, 

**1- Como devem ser classificados os Postos de Iluminação?**
a)	Apenas como Poste de iluminação?
b)	Como Poste de Iluminação + Poste de Baixa?

Nota: É uma área antiga da cidade, onde a rede de baixa está afixada nas fachadas dos edificios. Não existem postes de baixa, apenas candeeiros de iluminação ou posteletes.

![image](https://github.com/dgterritorio/RECART/assets/60113889/354f4c8f-ef6a-4416-b741-14ebba5f9c78)

**2- Como devemos proceder quando os cabos de baixa estão seguros por grampos (setas a rosa)?** 
![image](https://github.com/dgterritorio/RECART/assets/60113889/6005eda5-10fd-4d37-bdc8-de579a65c875)

Neste caso a rede interseta na cruz a vermelho (na imagem acima “pinta” a amarelo). 
**Colocamos neste sitio um poste?** Por forma a que a rede a nível de configuração não se altere muito e possa existir?
![image](https://github.com/dgterritorio/RECART/assets/60113889/8c85837e-4e38-4fbe-97da-64ad0b35c8ad)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Resposta a 1 – :
a) “Apenas como Poste de iluminação”. Nesta versão das Especificações Técnicas (ET) o valor correspondente só encaixa no valor 6.1 em [valorElementoAssociadoElectricidade](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocEletricidade.html#go_up_valorElementoAssociadoElectricidade)

Resposta a 2 – :
O objeto cabo elétrico deve ser representado com os "desvios" que efetivamente sofrer. Grampos em edifícios não são considerados "apoios". A definição de apoios aplica-se a estruturas com tipologia de "postes". 

Aparte: Apenas deve existir “Apoio de iluminação e baixa tensão” nestes casos: https://www.dgterritorio.gov.pt/recart/imagens/fElemAssocEletricidade-valorElementoAssociadoElectricidade6.2-1.jpg . 
A "iluminação" deve existir dissociada da rede elétrica (exceto nestes casos). 

Resposta a “Colocamos neste sítio um poste?”:
Não. 

De forma a ficar mais percetível vamos fazer alguns ajustes na próxima versão das especificações técnicas para melhorar a interpretação e esclarecer dúvidas. Também vamos aproveitar para introduzir as vossas fotografias.

Obrigado.

**Comment by CatarinaGaspar** [comment]
Boas Tardes, 

Sendo assim podemos ter vertices em cabos que não tenham apoios, certo?

![image](https://github.com/dgterritorio/RECART/assets/60113889/243222f0-c925-4572-af7a-d4506eaf7a03)

Obrigado,
