### ISSUE TITLE
Duvida Scripts SQL

### ISSUE THREAD

**Issue by iangsilva** [dgterritorio/RECART#211]
Bom dia.

Estou a tentar executar os scripts do info3d mas apenas consigo executar o curvas_nivel_mediana.sql. Os outros que se seguem dependem do que resulta deste primeiro script, mas não tenho muito conhecimento e gostava de perceber como posso exportar o resultado do curvas_nivel_mediana.sql. 

Obrigado desde já.

**Comment by dgterritorio** [comment]
@iangsilva , em https://github.com/dgterritorio/recart-scripts-sql/blob/main/info3d/info3d_consistencia_pontos.sql .   subentende-se que a view "curvas_nivel_mediana" está criada no schema "carttop" .
