### ISSUE TITLE
Nó de Infraestruturas em Ciclovias

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#212]
Bom dia, 

Segundo as regras, nos casos em que ciclovia partilha o eixo com o eixo da faixa de rodagem da via rodoviária representam-se os “dois eixos”, para “Ciclovia” e “Via urbana”. 

Contudo, quando existe infraestruturas apenas deve ser colocado o nó de “infraestrutura” no eixo referente à “via urbana” ou o eixo da ciclovia também deve levar nó de infraestrutura?

![image](https://github.com/dgterritorio/RECART/assets/60113889/4fd0675d-aa47-465a-a34e-1951146fd9ab)
Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Qual é a infraestrutura a verde? 

No modelo atual leva nó apenas no segmento da "Via urbana" (utilizando o vosso exemplo) porque não existem infraestruturas associadas à ciclovia.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

A infraestrutura a verde é um local de paragem (bus). Mas também temos situações de parqueamentos e estacionamentos.

Não nos fazia sentido colocar nó de infraestrutura na ciclovia. Mas preferimos confirmar.

Obrigado,

**Comment by aserronha** [comment]
Sendo assim não há dúvidas.

Podemos adiantar que em princípio vai haver uns ajustes com o melhorar das definições e alguns novos valores em [valorTipoInfraTransRodov](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html#go_up_valorTipoInfraTransRodov)  e [valorTipoServico](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html#go_up_valorTipoServico) na próxima versão para se poderem adicionar infraestruturas para o parqueamento de outro tipo de veículos e nalguns casos poderá fazer sentido colocar nó de infraestrutura na ciclovia. Contudo não será de produção obrigatória em NdD1 nem em NdD2.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Ok. Estamos a aguardar por essa nova versão. 
Para nós fará sentido se forem adquiridos estacionamento para bicicletas por exemplo.

Obrigado e Bom trabalho,

**Comment by aserronha** [comment]
Na versão 2.x foi eliminado o valor **7 - Estacionamento para velocípedes** em https://www.dgterritorio.gov.pt/recart/MOBILI%C3%81RIO%20URBANO%20E%20SINALIZA%C3%87%C3%83O/MobUrbanoSinal.html#page_valorTipoMobUrbSinal
