### ISSUE TITLE
Classificação dos Reservatórios de Água Elevados- Edifico

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#215]
Bom dia, 

Os reservatórios de água elevados não devem ser considerados como “Reservatório de armazenamento”, mas sim como Torre no valor forma – edificios?
Levantamos esta questão porque reparamos que em função do tipo de reservatório este é classificado de forma diferente quanto ao valor forma – edificio.
Se faz “sentido” existir esta especificidade sendo ambos reservatórios. E como o reservatório elevado já prossupõe estar sobre uma estrutura elevada, se se justificaria serem classificados como “Torre” em vez de “Reservatório de armazenamento”.

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

RespostaDGT: Aperfeiçoámos a abordagem da diretiva INSPIRE  que indica claramente que estes reservatórios são Torres (Edifícios): https://knowledge-base.inspire.ec.europa.eu/publications/inspire-data-specification-buildings-technical-guidelines_en

Os reservatórios de água elevados devem ser considerados nos Edifícios como “29. Torre” em [valorFormaEdificio](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html#page_valorFormaEdificio). Nas observações dizemos que também devem ser representados (Geometria (ponto)) como “7.1 Reservatório de água elevado” em [valorElementoAssociadoAgua](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocAgua.html#page_valorElementoAssociadoAgua).

Este princípio aplica-se a alguns elementos que possam ser edifícios e ao mesmo tempo tenham representação noutras temáticas. O espaço reservado às "Observações" no dicionário de objetos ajuda a esclarecer algumas destas questões.
