### ISSUE TITLE
Delimitação dos Tipos Fronteira-Terra-Água

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#216]
Boa Tarde, 

Nesta nova versão é necessário classificar a fronteira quanto ao tipo.
As nossas dúvidas prendem-se aos 2 primeiros tipos: linha de costa e linha limite de leito.

**1ª – Esta informação vai ser disponibilizada?** 
Apenas encontramos informação geográfica referente à linha limite de leito. Um dos problemas é a informação estar a 2D. Outro é, a falta de rigor na aquisição dos dados, tendo estes sido adquiridos à escala 25000. 
Não encontramos informação referente à linha de costa.

**2ª – Esta informação apenas é para usar como referencia?**
Tentamos analisar o limite de leito com os dados de algumas cartografias que temos e em certos sítios conseguimos perceber que é coincidente, mas noutros sítios existem algumas divergências.  

Nota: A Linha a Vermelho corresponte ao Limite de leito oficial disponibilizado pela Agencia Portuguesa do Ambiente.
![image](https://github.com/dgterritorio/RECART/assets/60113889/9aea8564-c75e-49e5-a7e8-dd94ec926c06)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

1ª - Sim

2ª - Sim

Oportunamente será disponibilizada a informação com as respetivas indicações. A issue permanece em aberto e poderá servir para esclarecer essa situação.

**Comment by aserronha** [comment]
Boa tarde,

Para responder a questões como esta devem passar a consultar a seguinte informação:
https://github.com/dgterritorio/BDNC/tree/main/cartografia2025/Dados_oficiais/Ag%C3%AAncia%20Portuguesa%20do%20Ambiente
