### ISSUE TITLE
Diferença entre construção margem (pontão ou cais) e área do transporte navegável (cais)

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#217]
Bom dia, 

Apenas queremos clarificar o que devemos representar como “pontão-cais” no tema das construções margem e “área de cais” no tema transporte navegável.

A imagem abaixo reflete o que entendemos da representação destes dois objetos:
![image](https://github.com/dgterritorio/RECART/assets/60113889/291897f9-d12f-4002-8c84-3fe01981b86d)

No entanto há casos que nos suscitam dúvidas. Colocamos a imagem seguinte para ser mais fácil de entender:
![image](https://github.com/dgterritorio/RECART/assets/60113889/d2a674ca-26af-4901-b41e-0c44aaae0666)

a)	Os elementos estão bem representados e classificados? A elemento identificado com o “A” deve ser considerado pontão-cais (construção margem) e não deve ser incluído na área de “Molhe-QuebraMar”? 
b)	Neste caso também temos de representar alguma área de cais – transporte navegável? Se sim onde? 
c)	Podem existir pontões-cais sem termos que representar área de cais do transporte navegável, certo? Caso prático, imagem seguinte.
![image](https://github.com/dgterritorio/RECART/assets/60113889/f37dc909-3ea2-4b0c-839a-7346bac5f6a0)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

RespostaDGT: 

a)	Os elementos poligonais parecem todos bem representados e classificados através dessas linhas. Parece faltar apenas um ponto que caracterize a infraestrutura “Doca” e 
podem incluir a área do “Pontão ou cais” dentro da área do “Molhe ou quebra-mar”. É o que nos parece mais aceitável através do esquema https://www.dgterritorio.gov.pt/recart/imagens/eConstruNaMargem-valorTipoConstMargem1-1.jpg 

b)	Não nos parece que seja necessário representar “Área de cais” em [valorTipoAreaInfraTransViaNavegavel](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20por%20via%20naveg%C3%A1vel)/AreaInfraTransViaNavegavel.html#go_up_valorTipoAreaInfraTransViaNavegavel) nem “Cais” em [valorTipoInfraTransViaNavegavel](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20por%20via%20naveg%C3%A1vel)/InfraTransViaNavegavel.html#page_valorTipoInfraTransViaNavegavel) na temática do Transporte por via navegável. Basta a representação da “Área da doca” e “Doca” nas respetivas listas de códigos.

c)	Sim, podem existir “Pontão ou cais” nas margens fluviais ou marítimas e que não possuem instalações, equipamentos e serviços destinados ao tráfego por via navegável e como tal não existe representação na temática do Transporte por via navegável.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Esclarecidos.

Obrigado e Bom trabalho,
