### ISSUE TITLE
Representação da Estrutura de Captação de Água

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#219]
Boa Tarde, 

Na versão 2x, a representação da estrutura de captação de água deve ser representada no tema ElemAssAgua como ponto e no tema Edificio como ponto ou área dependente da área minima de representação do NDd.

Qual a representação correta da estrutura de captação de água? 
Apenas deve ser representada a torre de tomada (imagem A) ou também devem ser incluídos os acessos (imagem B).

![image](https://github.com/dgterritorio/RECART/assets/60113889/b59ed049-06c0-4a82-8680-9e3cae9b288d)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Foi adicionado um esquema no dicionário de objetos em:
https://www.dgterritorio.gov.pt/recart/imagens/eElemAssocAgua-valorElementoAssociadoAgua9-1.jpg 

Este esquema pretende ilustrar ainda melhor o que já constava nas Observações do [valorFormaEdificio](https://www.dgterritorio.gov.pt/recart/v_1_1_2/CONSTRU%C3%87%C3%95ES/Edificio.html#page_valorFormaEdificio) igual a **29 - Torre** do [[06.03] Edifício](https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html) e que simultaneamente é uma **9 - Estrutura de captação de água** em [valorElementoAssociadoAgua](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocAgua.html#page_valorElementoAssociadoAgua)

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido

Obrigado,
