### ISSUE TITLE
Altura dos edifícios só aceita inteiros

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#22]
Embora o dicionário de objectos indique que a altura dos edifícios deve ser descrita com valores reais (que faz sentido), a implementação na base de dados é int4

http://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html

**Comment by dgterritorio** [comment]
Corrigido!
https://github.com/dgterritorio/RECART/commit/fe5b6ab49de2c2eb2d31bdfbc12edde991521916
Mais uma vez obrigado pelo contributo.
