### ISSUE TITLE
Representação de Parques Infantil

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#220]
Boa Tarde, 

Na versão 2x, os parques infantis passaram a pertencer à tabela dos equipamentos coletivos. Regra geral, todos os objetos que tem relação com a tabela do equipamento coletivo têm que ter nome para serem representados. 

Quando não existir nome para o parque infantil como devemos fazer? Não fica referenciado? Colocamos apenas “parque infantil” no nome?

Por norma os parques infantis estão inseridos em um equipamento (parques e jardins, escolas, etc..), sempre podemos dar essa designação ao parque infantil também, ex: Parque Infantil do Colégio “Espaço Júnior”
![image](https://github.com/dgterritorio/RECART/assets/60113889/4fd8e33e-c86a-4469-b063-47c0e215a445)

Não teria mais logica a representação dos parques infantis no tema das construções poligonais, à semelhança do que acontece com os campos de jogos?

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

O parque infantil não se destaca (também pelas suas dimensões reduzidas), é apenas uma tipologia no conjunto de tipologias que os equipamentos de utilização coletiva podem ter, neste caso, o equipamento "Colégio Espaço Júnior" pode ter o [valorTipoEquipamentoColetivo](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/EquipUtilColetiva.html#page_valorTipoEquipamentoColetivo) =1.1 ou 1.2 (Educação) e o [valorTipoEquipamentoColetivo](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/EquipUtilColetiva.html#page_valorTipoEquipamentoColetivo)= 7.5 Parque Infantil.

Notar que também seria possível destacar o equipamento "Parque infantil" como mais uma área artificializada (valor 7 = Área de equipamentos desportivos e de lazer) e não sobreposta, ficando este equipamento com n geometrias: 2 áreas artificializadas (para o caso concreto).

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Para confirmar se entedemos bem.

1- Os parques infantis não devem ser isolados dos equipamentos, isto é, são representados geometricamente no tema “edificio” e ficarão agregados ao “Identificador” do equipamento coletivo.

![image](https://github.com/user-attachments/assets/ae5a6790-de9f-458a-bea8-d6019df60bd9)

1.1- Sendo o parque infantil representado no tema "edificio", a altura deste é 0, certo?

2- A representação da área artificializada nestes casos é obrigatória? Ou seja, teríamos que representar as 2 áreas: uma para o colégio e outra para o parque infantil.

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Para confirmar se entedemos bem.
> 
> 1- Os parques infantis não devem ser isolados dos equipamentos, isto é, são representados geometricamente no tema “edificio” e ficarão agregados ao “Identificador” do equipamento coletivo.
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/353377173-ae5a6790-de9f-458a-bea8-d6019df60bd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjk1MDksIm5iZiI6MTcyMjMyOTIwOSwicGF0aCI6Ii82MDExMzg4OS8zNTMzNzcxNzMtYWU1YTY3OTAtZGU5Zi00NThhLWJlYTgtZDYwMTlkZjYwYmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4NDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDVkY2U5ZGM3NzBjM2ZjZWI2MjhkNGIwMTIyOWIyZjBhODljN2Y3YjZjM2E0MzY5OGZiOWY5ZDQwMGU3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ds5Fo69arJcN7yuJqNQcIWvFd6FURXTYZzX_o3IGQjE)
> 
> 1.1- Sendo o parque infantil representado no tema "edificio", a altura deste é 0, certo?
> 
> 2- A representação da área artificializada nestes casos é obrigatória? Ou seja, teríamos que representar as 2 áreas: uma para o colégio e outra para o parque infantil.

Como foi dito anteriormente podem fazer como entenderem. 
A geometria de um colégio e/ou Parque infantil não é feita nos edifícios. É a área artificializada (valor 7 = Área de equipamentos desportivos e de lazer) que contém a geometria. Esta geometria pode ser apenas de 1 área artificializada do perímetro de todo o colégio (com n equipamentos, pode ter o [valorTipoEquipamentoColetivo](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/EquipUtilColetiva.html#page_valorTipoEquipamentoColetivo) =1.1 ou 1.2 (Educação) e o [valorTipoEquipamentoColetivo](https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/EquipUtilColetiva.html#page_valorTipoEquipamentoColetivo)= 7.5 Parque Infantil ) ou eventualmente de acordo com o que foi dito na resposta anterior também é aceitável representarem 2 áreas artificializadas individualmente (1 polígono dentro de outro recortado para não haver sobreposição) com 1 área artificializada para o equipamento de "Educação" que é o colégio e a outra área artificializada lá dentro tem o equipamento "Parque Infantil".
Finalmente, também devem estabelecer a relação entre o(s) edifício(s) e o(s) equipamento(s).
Para ajudar a esclarecer a regra específica 7.8 está previsto acrescentar esta frase (a amarelo):
![image](https://github.com/user-attachments/assets/5a256119-b420-4ab3-aad8-8fb52867b921)

> 
> Obrigado,

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Entendido. 

Obrigado,
