### ISSUE TITLE
RE6.9 - Generalização da Construção Linear Junto a Edifícios

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#221]
Boa Tarde, 

_“A representação da construção linear (muros, etc.) adjacente a um edifício não deve ser interrompida devido à presença dessa construção mesma que esta seja representada com geometria pontual, de forma a garantir a continuidade da construção linear, devendo apenas ser respeitadas as interrupções nos portões que têm representação.”_

**Questões:**

**a)	As construções lineares não são interrompidas quando os “portões” não são representados?**
![image](https://github.com/dgterritorio/RECART/assets/60113889/81ba0108-04ce-4513-92f3-ed4730dea783)

**b)	As construções lineares não devem ser interrompidas quando:**

1. Adjacentes a um edificio

No nosso entender, a regra aplica-se às situações da imagem da esquerda. Contudo queremos confirmar se são estas as situações ou se também se aplica aos casos da imagem da direita.

![image](https://github.com/dgterritorio/RECART/assets/60113889/07c6343e-3f25-425f-a51d-35bba2c356b3)

1.1 - Neste tipo de situação os muros devem ser interrompidos pelos edificios?

![image](https://github.com/dgterritorio/RECART/assets/60113889/df266032-4a7f-4c23-9acb-1ac97bcee45b)

2. Quando os edificios são representados através de um ponto ou sem representação (edificios associados à residência- isolados)
       
![image](https://github.com/dgterritorio/RECART/assets/60113889/6debb01f-6df2-44e7-96a3-06c4d92196ea)

Obrigado,

**Comment by aserronha** [comment]
> Boa Tarde,
> 
> _“A representação da construção linear (muros, etc.) adjacente a um edifício não deve ser interrompida devido à presença dessa construção mesma que esta seja representada com geometria pontual, de forma a garantir a continuidade da construção linear, devendo apenas ser respeitadas as interrupções nos portões que têm representação.”_
> 
> **Questões:**
> 
> **a) As construções lineares não são interrompidas quando os “portões” não são representados?** ![image](https://private-user-images.githubusercontent.com/60113889/334440801-81ba0108-04ce-4513-92f3-ed4730dea783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDA4MDEtODFiYTAxMDgtMDRjZS00NTEzLTkyZjMtZWQ0NzMwZGVhNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzQ4ZTljOWI2NDkzZjljNGFiZTYwNjZiMzgxNjVkYTk5YjY4NmZiODUzZTdhNDI5MjBjZWFmOGQzMTI3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2pF6qUGxxYc6WOEFaTo-e86_-q28hv-7UqdWIpcB30)
> 
Para o caso apresentado as Especificações Técnicas nunca indicam para generalizar portões para dar continuidade a muros/gradeamentos. Teria de existir representação do portão caso este tivesse as dimensões exigidas. De qualquer das formas neste caso concreto não aparenta existir nem portão (ver valores exigidos para NdD2) nem muro+gradeamento com uma altura superior a 2,5m (NdD2).
 
> **b) As construções lineares não devem ser interrompidas quando:**
> 
> 1. Adjacentes a um edificio
> 
> No nosso entender, a regra aplica-se às situações da imagem da esquerda. Contudo queremos confirmar se são estas as situações ou se também se aplica aos casos da imagem da direita.
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/334441384-07c6343e-3f25-425f-a51d-35bba2c356b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDEzODQtMDdjNjM0M2UtM2YyNS00MjVmLWE1MWQtMzViYmEyYzM1NmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjZiN2E1NTY0OTVjNzk0N2E5YjFhMDg2YWQ0MjU1MTg5MDlkYjAyOTY0NjA0Nzg0ZGUxODEwNjc1Y2RkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AItlCZbUDfkxmCcdaYI5rdeLxXvDmRqyqU8MoQ4YOs4)
> 
> 1.1 - Neste tipo de situação os muros devem ser interrompidos pelos edificios?
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/334441969-df266032-4a7f-4c23-9acb-1ac97bcee45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDE5NjktZGYyNjYwMzItNGE3Zi00YzIzLTlhY2ItMWFjOTdiY2VlNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiN2IwMTEyMWMzNjhmM2RhNThmOGI1MjUzMjk4YmYyODI3N2E1ZTgwZWVhYzVmMmQ1ZGViNTVjMTliNmY3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96xYyKwnRwnUBhP8zEeEwLwakmT4LihSUQ3Mrf4R7Pk)
> 
> 2. Quando os edificios são representados através de um ponto ou sem representação (edificios associados à residência- isolados)
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/334446835-6debb01f-6df2-44e7-96a3-06c4d92196ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDY4MzUtNmRlYmIwMWYtNmRmMi00NGU3LTk2YTMtMDZjNGQ5MjE5NmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYjRhNTlmOGIwZjhmMzFjM2IwMDA1MzI0NTk1YTM2MGZmOGRmZmRkNTUwYmQzY2Y1NjE1ZWMyZGQ3ZjNmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eHYj80qTXCPE7myyuAIKqJn44zuBOokVz7qpj3RMAnA)
> 
> Obrigado,

A questão da representação cartográfica  das construções lineares, com destaque para os muros é de difícil parametrização e, a propósito das dúvidas levantadas no GITHUB, algumas regras específicas sofrerão alguns ajustes no próximo upgrade para a versão 2.0.2 das Especificações Técnicas.

Não obstante, para algumas situações a DGT tem já algumas alterações previstas que podem ser atendidas, nomeadamente:

- A Regra específica 6.9 passará a ter a seguinte formulação: “A representação da construção linear adjacente a um edifício não deve ser interrompida devido à presença dessa construção no caso desta ser representada por um ponto, de forma a garantir a continuidade da construção linear. ”


- Sempre que existe evidência física do muro mesmo que “colado” à parede do edifício mas sobressaindo dela, deve ser representado como muro e não deve ser interrompido:
![image](https://github.com/user-attachments/assets/0a615e16-76bb-4f89-8408-8655a36cef89)

 
- No caso de um muro terminar num edifício aquele muro deve ser interrompido (na verdade deixa de haver muro e passa a haver parede do edifício) exceto, claro, se estivermos num caso da regra  6.9.  É a situação que se vê nas fotos do muro que acaba num edifício branco ou no que acaba numa garagem, telheiro ou arrecadação, como é o caso da metade direita das fotos: 
![image](https://github.com/user-attachments/assets/2a3ee0c4-f6b6-4a3b-94df-77a525b14f54)

**Comment by CatarinaGaspar** [comment]
Bom dia, 

> > **a) As construções lineares não são interrompidas quando os “portões” não são representados?** ![image](https://private-user-images.githubusercontent.com/60113889/334440801-81ba0108-04ce-4513-92f3-ed4730dea783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDA4MDEtODFiYTAxMDgtMDRjZS00NTEzLTkyZjMtZWQ0NzMwZGVhNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzQ4ZTljOWI2NDkzZjljNGFiZTYwNjZiMzgxNjVkYTk5YjY4NmZiODUzZTdhNDI5MjBjZWFmOGQzMTI3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2pF6qUGxxYc6WOEFaTo-e86_-q28hv-7UqdWIpcB30)
> 
> Para o caso apresentado as Especificações Técnicas nunca indicam para generalizar portões para dar continuidade a muros/gradeamentos. Teria de existir representação do portão caso este tivesse as dimensões exigidas. De qualquer das formas neste caso concreto não aparenta existir nem portão (ver valores exigidos para NdD2) nem muro+gradeamento com uma altura superior a 2,5m (NdD2).

O facto de na imagem ter escrito ndd2 pode induzir em erro (os objetos não seriam representados por não terem dimensões minimas). Na realidade, o que queriamos confirmar é se mesmo o portão não sendo representado por não ter dimensão, o muro deve ser interrompido nesses casos. 
Questionamos isto por na regra estar escrito _"de forma a garantir a continuidade da construção linear, devendo apenas ser respeitadas as interrupções nos portões que têm representação.”_. não está claro, nos casos em que os portões não são representados se os muros ficam interrompidos.


As outras questões estão esclarecidas.

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> > > **a) As construções lineares não são interrompidas quando os “portões” não são representados?** ![image](https://private-user-images.githubusercontent.com/60113889/334440801-81ba0108-04ce-4513-92f3-ed4730dea783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDc3ODIsIm5iZiI6MTcyMjI0NzQ4MiwicGF0aCI6Ii82MDExMzg4OS8zMzQ0NDA4MDEtODFiYTAxMDgtMDRjZS00NTEzLTkyZjMtZWQ0NzMwZGVhNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwMDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzQ4ZTljOWI2NDkzZjljNGFiZTYwNjZiMzgxNjVkYTk5YjY4NmZiODUzZTdhNDI5MjBjZWFmOGQzMTI3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2pF6qUGxxYc6WOEFaTo-e86_-q28hv-7UqdWIpcB30)
> > 
> > 
> > Para o caso apresentado as Especificações Técnicas nunca indicam para generalizar portões para dar continuidade a muros/gradeamentos. Teria de existir representação do portão caso este tivesse as dimensões exigidas. De qualquer das formas neste caso concreto não aparenta existir nem portão (ver valores exigidos para NdD2) nem muro+gradeamento com uma altura superior a 2,5m (NdD2).
> 
> O facto de na imagem ter escrito ndd2 pode induzir em erro (os objetos não seriam representados por não terem dimensões minimas). Na realidade, o que queriamos confirmar é se mesmo o portão não sendo representado por não ter dimensão, o muro deve ser interrompido nesses casos. Questionamos isto por na regra estar escrito _"de forma a garantir a continuidade da construção linear, devendo apenas ser respeitadas as interrupções nos portões que têm representação.”_. não está claro, nos casos em que os portões não são representados se os muros ficam interrompidos.
> 
> As outras questões estão esclarecidas.
> 
> Obrigado,

Sim, o(s) muro(s) fica(m) "interrompido(s)".

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Estamos esclarecidos.

Obigado,

**Comment by aserronha** [comment]
Boa tarde, 

A representação dos muros e as suas regras específicas foram revistas para NdD1 e NdD2 e constam nas Especificações Técnicas v2.0.2.
