### ISSUE TITLE
Representação de Aceiros

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#222]
Bom dia, 

Já percebemos que consideram também como aceiros, as faixas de gestão de combustivel ao longo das linhas de rede elétrica. 
Como já mencionado na issue #136.

Embora, a manutenção do arbóreo nas faixas de servidão elétrica ajude a impedir a propagação de incêndios que possam começar em outros lugares ou ser causados por falhas na rede elétrica, a sua principal função é evitar que interfiram com os cabos e causem curtos-circuitos ou faíscas que possam iniciar um incêndio.
Pelo que sabemos nestas faixas pode existir vegetação até determinada altura, máximo 3 metros de altura, esta depende da tensão da linha elétrica. 
Não significa que em alguns casos, não seja possível a circulação de veículos de socorro em casos de emergência, mas nem em todos os casos a sua circulação é possível.

Entendemos a lógica, mas não achamos correto a representação de aceiros nestas situações. Não o estávamos a considerar até aqui. 

Dado que este assunto tem sido reportado nos últimos relatórios aproveitamos para levantar algumas questões:

1. As faixas de servidão das linhas de rede elétrica devem ser consideras como aceiros?
2. Nesta situação, imagem abaixo, o limite do aceiro deve incluir o caminho?
3. O eixo do caminho, tem que ficar no centro? Ou pode ficar representado onde efetivamente o caminho existe?

![image](https://github.com/dgterritorio/RECART/assets/60113889/948b86fe-4b8f-4e0a-8919-e397bf5a6f3e)

5. Podemos deixar os caminhos quando estes atravessam estas faixas?
![image](https://github.com/dgterritorio/RECART/assets/60113889/fcfd9fb0-d660-4122-a061-3b73740e28c2)

Obrigado,

**Comment by aserronha** [comment]
> 1. As faixas de servidão das linhas de rede elétrica devem ser consideras como aceiros?

respostaDGT: Sim.

> 2. Nesta situação, imagem abaixo, o limite do aceiro deve incluir o caminho?

respostaDGT: Sim, mas como em qualquer entroncamento/cruzamento entre vias basta representar os seus eixos com o nó de junção na interseção. Não é necessário representar os limites do "caminho" dentro da área delimitada pelos limites do aceiro.

> 3. O eixo do caminho, tem que ficar no centro? Ou pode ficar representado onde efetivamente o caminho existe?

respostaDGT: "Os eixos são representados por linhas que se aproximam o melhor possível do centro do fenómeno a que 
dizem respeito (...)" cf. Especificações Técnicas. Não é necessário representar os limites do "caminho" dentro da área delimitada pelos limites do aceiro.

> 4. -

> 5. Podemos deixar os caminhos quando estes atravessam estas faixas?

respostaDGT: Quando os "caminhos" atravessam estas faixas (área delimitada pelos limites do aceiro) basta apenas representar o seu eixo. 

Esclarecido @CatarinaGaspar ?

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Escalrecidos quanto a este assunto.

Obrigado,
