### ISSUE TITLE
Representação dos Elementos Associados ao PGSQ

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#223]
Bom dia, 

Todos os objetos contemplados neste tema devem ser também representados por área no tema área artificializada?

![image](https://github.com/dgterritorio/RECART/assets/60113889/8da4dcb9-e1cd-4b1d-ac22-ec88752a4130)

1. Mesmo nestas situações leva área artificializada? Indústria?
![image](https://github.com/dgterritorio/RECART/assets/60113889/31f01607-92a0-4f3a-84de-02debcb3b1dc)

2. E se a área artificializada não tiver área minima de representação? Não se representa, certo? Fica apenas o ponto referente ao elemento do tema em questão?

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Todos os objetos contemplados neste tema devem ser também representados por área no tema área artificializada?

respostaDGT: É exatamente como fizeram no esquema em baixo.
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/337627143-8da4dcb9-e1cd-4b1d-ac22-ec88752a4130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjgwMDksIm5iZiI6MTczNDQyNzcwOSwicGF0aCI6Ii82MDExMzg4OS8zMzc2MjcxNDMtOGRhNGRjYjktZTFjZC00YjFkLWFjMjItZWM4ODc1MmE0MTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzMxYTgxYmEzMzJlZjY4NjEwNDM5MDQ0NGFjOWYwNTM1NjVlNGRhOTQ0YjNiNTlkZTY0MmVjNWYyZjM4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A39tVjk6jiepqZjxDdUOj6XnHWiOIRmZ2aE52E_twOI)
> 
> 1. Mesmo nestas situações leva área artificializada? Indústria?

1. respostaDGT: Sim, de acordo com os parâmetros do respetivo nível de detalhe (NdD).
>    ![image](https://private-user-images.githubusercontent.com/60113889/337627243-31f01607-92a0-4f3a-84de-02debcb3b1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjgwMDksIm5iZiI6MTczNDQyNzcwOSwicGF0aCI6Ii82MDExMzg4OS8zMzc2MjcyNDMtMzFmMDE2MDctOTJhMC00ZjNhLTg0ZGUtMDJkZWJjYjNiMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDVlZGVmZGI0ZWI4OTY2ZDk2ZDQyNzc3YWIxNGJlZTdkNGYxNTNjMjAyZGIzYjI5MWViZTE0MzQyNjA5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rz0WsZL9Wl5Hdp1qh095qQRzu2wVCrX560STPvWA5CA)
> 2. E se a área artificializada não tiver área minima de representação? Não se representa, certo? Fica apenas o ponto referente ao elemento do tema em questão?

2. respostaDGT: Exatamente.
> 
> Obrigado,

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Entendido.

Obrigado,
