### ISSUE TITLE
RE4.14 – Comprimento mínimo do curso de água

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#225]
Bom dia, 

O que entendemos desta regra é que apenas se aplica aos inícios do curso de água eixo – (cae). Portanto é possível existirem segmentos do cae pelo meio da rede ou mesmo no fim da rede em que o seu comprimento possa ser igual ou inferior aos comprimentos mínimos. 
![image](https://github.com/dgterritorio/RECART/assets/60113889/55731d93-ee3b-43b6-a32c-8985c08b066b)
a) Esta é a lógica?

**Algumas situações práticas, para entendermos melhor:**
![image](https://github.com/dgterritorio/RECART/assets/60113889/ef411dbc-731b-45b1-8150-b22313f92d42)

**Caso 1 – O segmentos A e B não tem dimensão mínima.**
a) Ambos os segmentos devem ser eliminados;
b) Elimina-se um dos segmentos dado que juntando A ou B ao segmento C já ganha dimensão;
![image](https://github.com/dgterritorio/RECART/assets/60113889/076942a4-dd76-48cb-93b8-d6e46319f2f1)

**Caso 2 – Os segmentos A, B e C não tem dimensão minima**
a) Todos os segmentos devem ser eliminados;
b) Elimina-se um dos segmentos dado que juntando A ou B ao segmento C já ganha dimensão
![image](https://github.com/dgterritorio/RECART/assets/60113889/6d10413c-e19e-4a7d-8e36-71d726807337)

**Caso 3 – Os segmentos A, B e C não tem dimensão minima**
a) Todos os segmentos devem ser eliminados porque mesmo juntando A ou B ao segmento C este fica sem dimensão
b) Pode-se ponderar eliminar o segmento D por forma a manter os segmentos A ou B e o C. Isto porque o segmento D é um afluente e parece-nos mais correto o traçado dos outros segmentos. Mesmo visualmente não fica estranho.
![image](https://github.com/dgterritorio/RECART/assets/60113889/6732361a-be80-49ca-a654-c0c573bb2fc3)

Esta é a interpretação que deve ser feita?

Caso 4  - Nesta situação temos de eliminar estas duas linhas por não terem dimensão, nem ser possivel serem juntas por terem carateristicas diferentes?
![image](https://github.com/dgterritorio/RECART/assets/60113889/d605956e-a076-4477-b4f2-b394ece49cc8)

Caso 5 - Quando são inícios provindos de águas lênticas, também devemos eliminar? Não nos parece correto.
![image](https://github.com/user-attachments/assets/576c83f6-7bcd-464f-af2c-1ed889c6df99)

Obrigada,

**Comment by aserronha** [comment]
> Bom dia,
> 
> O que entendemos desta regra é que apenas se aplica aos inícios do curso de água eixo – (cae). Portanto é possível existirem segmentos do cae pelo meio da rede ou mesmo no fim da rede em que o seu comprimento possa ser igual ou inferior aos comprimentos mínimos. 
![image](https://private-user-images.githubusercontent.com/60113889/340982632-55731d93-ee3b-43b6-a32c-8985c08b066b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDA5ODI2MzItNTU3MzFkOTMtZWUzYi00M2I2LWEzMmMtODk4NWMwOGIwNjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNDg5MmE1NGEzZWEwNWFmZmJlNDQ2Y2I0NjUyYWUzYjNjOGM5Nzk0OWVkMjVmODMyMGFmMmVhZTRjNDg5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m-U91bSrQ9ODt1uE7vIz-cWcFmvx7WGIXQgjZWBhFhE) 
a) Esta é a lógica?
> 
**resposta: Sim. É necessário averiguar apenas os segmentos que "tocam" o "nó = Início" e perceber as ramificações quando encontram outro segmento.**

> **Algumas situações práticas, para entendermos melhor:** 
![image](https://private-user-images.githubusercontent.com/60113889/340982726-ef411dbc-731b-45b1-8150-b22313f92d42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDA5ODI3MjYtZWY0MTFkYmMtNzMxYi00NWIxLTgxNTAtYjIyMzEzZjkyZDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjlkNTI3NjhkNDQzNjNlNDBjMDc5ODNhOTYwMmJmNDE4YzYyMmM1OGY1OTkzMzUxMWNkY2JlYmNjNTRiYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bSrnausQE4YPrWrtWXra5BhofPuR2z7CnIAO7X-xeoU)
> 
> **Caso 1 – O segmentos A e B não tem dimensão mínima.** 
a) Ambos os segmentos devem ser eliminados; 
b) Elimina-se um dos segmentos dado que juntando A ou B ao segmento C já ganha dimensão; 
![image](https://private-user-images.githubusercontent.com/60113889/340982913-076942a4-dd76-48cb-93b8-d6e46319f2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDA5ODI5MTMtMDc2OTQyYTQtZGQ3Ni00OGNiLTkzYjgtZDZlNDYzMTlmMmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzU0NTdkMjVlYzdmMDU4NzNmYTY1NTZhMjE4MWUzMDA5NGI1N2YyZWY2Y2Y5NDZhYjZmYmI2NzZmZTFlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rdXLXHmkFjfSgKjlI0nYx3cCuBV2QGyctYo1bxuDChg)
> 
**resposta: b) e deve-se elimininar o segmento B que "parece" de dimensão inferior a A.**

> **Caso 2 – Os segmentos A, B e C não tem dimensão minima** 
a) Todos os segmentos devem ser eliminados; 
b) Elimina-se um dos segmentos dado que juntando A ou B ao segmento C já ganha dimensão 
![image](https://private-user-images.githubusercontent.com/60113889/340983107-6d10413c-e19e-4a7d-8e36-71d726807337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDA5ODMxMDctNmQxMDQxM2MtZTE5ZS00YTdkLThlMzYtNzFkNzI2ODA3MzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYmExOGE1NDBhMGI5NjdjZWRlMGIwYmM3NGMxZjlhYjVlYTJhYmUzNzI0YzkwODJiYTA0NDFiMWY1Y2Q2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tpH2Bx92YNezyxCU40JahT2flKX0wOhxDI1cu8Z28dw)
> 
**resposta: Não podemos escolher a) ou b). C+A ou C+B tem de ser avaliado em conjunto com D e E (partindo do princípio que E é o único segmento que não está identificado na imagem).**

> **Caso 3 – Os segmentos A, B e C não tem dimensão minima** 
a) Todos os segmentos devem ser eliminados porque mesmo juntando A ou B ao segmento C este fica sem dimensão 
b) Pode-se ponderar eliminar o segmento D por forma a manter os segmentos A ou B e o C. Isto porque o segmento D é um afluente e parece-nos mais correto o traçado dos outros segmentos. Mesmo visualmente não fica estranho. 
![image](https://private-user-images.githubusercontent.com/60113889/340983289-6732361a-be80-49ca-a654-c0c573bb2fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDA5ODMyODktNjczMjM2MWEtYmU4MC00OWNhLWE2NTQtYzBjNTczYmIyZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTc5OTlhOGNiOTFmZTExMTNhNmI3ODg4ZGIxNjg5NDdiMmNiNDJlN2NhMTMxN2M4MDViYWUyNDE3NzFjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zft7-G5P72irFCF-Jht8whkBZsBZtC7UI9_BaqVp5ZM)
> 
> Esta é a interpretação que deve ser feita?

**resposta: Não. Primeiro é necessário avaliar o comprimento de E. Avaliam depois o comprimento de D. Se D tiver dimensão representa-se. Se não tiver dimensão deixa de existir nó e já deixa de existir segmento C, ou seja, E+C serão o mesmo segmento.**

> 
> Caso 4 - Nesta situação temos de eliminar estas duas linhas por não terem dimensão, nem ser possivel serem juntas por terem carateristicas diferentes? 
![image](https://private-user-images.githubusercontent.com/60113889/344694002-d605956e-a076-4477-b4f2-b394ece49cc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNDQ2OTQwMDItZDYwNTk1NmUtYTA3Ni00NDc3LWI0ZjItYjM5NGVjZTQ5Y2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzN2MwZjEzZDRkZThjNDRhZTc4ODBjMTg5NzU5YzdlMWVkNmFmOTQ0NGZlOGFhOWRmZDZmOGFkMTk1NTA4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4kPh52L84xA2zq1blbSAnQxaEKFNuxer2xwxAW6IOBs)
> 
**resposta: Aqui não existem ramificações de segmentos no mesmo nó logo não se aplica esta regra. O curso de água deve ser considerado como um todo apesar de existirem nós que só servem para partir as linhas de características distintas.**

> Caso 5 - Quando são inícios provindos de águas lênticas, também devemos eliminar? Não nos parece correto. 
![image](https://private-user-images.githubusercontent.com/60113889/367708258-576c83f6-7bcd-464f-af2c-1ed889c6df99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDgwOTEsIm5iZiI6MTcyOTYwNzc5MSwicGF0aCI6Ii82MDExMzg4OS8zNjc3MDgyNTgtNTc2YzgzZjYtN2JjZC00NjRmLWFmMmMtMWVkODg5YzZkZjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTU0NmUzOGZjM2VhNzUyYjZmMTliYmVlYWEyOTMxNmIzZDA2YjVhYTg0N2NmM2JkMTU4NGIxYzZjOWRkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.COrs7ENWmtgqiaZSyyz4cmxrbcAjkinXd_uWC7L_hSk)
> 

**resposta: Aqui não se aplica esta regra seguindo mesmo critério da questão anterior, por isso os vários segmentos da linha de água são todos representáveis.**

> Obrigada,

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Já compreendemos que esta regra só se aplica quando existe ramificações no inicio das linhas de água.

No entanto, no caso 3 não compreendemos o que deve ser feito a A/C/B quando o D tem dimensão? Sendo que juntando A+C ou C+B estes não ganham dimensão.

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Já compreendemos que esta regra só se aplica quando existe ramificações no inicio das linhas de água.
> 
> No entanto, no caso 3 não compreendemos o que deve ser feito a A/C/B quando o D tem dimensão? Sendo que juntando A+C ou C+B estes não ganham dimensão.
> 

Nesse caso matematicamente pode ser eliminado A/C/B.
Nota: Em cartografia topográfica esta regra não tem de ser matemática, ela pretende apenas garantir que a rede hidrográfica não está repleta de linhas de água de dimensão muito reduzidas, no entanto, não é impeditiva de se representarem troços (segmentos) que contribuam para uma representação mais adequada da rede, nomeadamente nessas ligações iniciais da rede em cabeceiras, nascentes que por vezes até têm implantação conhecida.

> Obrigado,

**Comment by CatarinaGaspar** [comment]
Boas Tardes, 

Ok, entendido.

Bom trabalho.
