### ISSUE TITLE
Representação dos Números de Policia

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#226]
Boa Tarde, 

De acordo com o que entendemos, os números de polícia (npol) devem ser georreferenciados tendo em conta o contexto. Quando são visíveis as divisões de propriedade, normalmente identificadas por construções lineares (muros, vedações, etc..), os números devem ser posicionados à frente dos edificios dentro da propriedade **(casos 1)**. Caso contrário, o npol deve ser colocado sobre o edifício **(caso 2)**. Além disso, se não houver edifício, o npol ainda deve ser registrado, como no caso de lotes, por exemplo **(caso 3)**.

É esta a logica que deve ser seguida para a georreferenciação dos npol?

**1. Números de policia (no muro)**
![image](https://github.com/dgterritorio/RECART/assets/60113889/60ac4883-1ce0-4c20-b3db-d958d6f2fe1e)

**2. Números de policia (no edificio)**
![image](https://github.com/dgterritorio/RECART/assets/60113889/e6b791d1-683e-428d-a6e1-20268fdeda62)

**3. Números de policia (sem edificio)**
![image](https://github.com/dgterritorio/RECART/assets/60113889/a1bf7d77-4340-4408-8a5f-a7f4570fb2a1)

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Respondendo concretamente às questões:

Caso 1: O conceito de propriedade em cartografia não existe por isso colocam o número de polícia na "entrada" ou onde for "visível" a sua "implantação/materialização" (pode ser no muro ou no próprio edifício). O modelo de dados CartTop pretende é que fique bem estabelecida a relação da materialização da localização do número de polícia com o(s) respetivo(s) edifício(s) caso exista(m). Obrigatoriamente, também deve ser estabelecida a relação entre o número de polícia e o respetivo segmento da via rodoviária (que por sua vez estabelece relação com a respetiva **via rodoviária** composta pelo seu nome e restante tipologia).
 
Caso 2:  Aplica-se o mesmo que foi descrito no caso 1.
 
Caso 3:  Avaliar se já tem efetivamente um número de polícia materializado numa porta ou portão de acesso à via pública ou se apenas ainda é um lote dentro de um loteamento!


**Após discutir estes assuntos com interlocutores da administração central e local, de uma forma geral, transmitimos estas indicações:**

O Instituto Nacional de Estatística (INE) a quem agradecemos a ajuda elucida-nos que consideram o lote e o número de polícia opções diferentes, mas complementares na morada. 
Para se ter número de lote teve de existir um Loteamento. O que acontece depois na emissão do Licenciamento é que não existindo número de polícia é utilizado o lote – quando existiu um loteamento prévio.
São utilizadas 2 opções: J.4 Lote (prefixo do edifício) e J.5 Nº Lote (designação do edifício)  
J.6 Número de Porta:
![image](https://github.com/dgterritorio/RECART/assets/46351849/b32e5115-cc3f-4f34-a94a-c7a4d6d9d9c8)


### Diferenças entre Número de Lote e Número de Polícia: 
### Número de Lote:
   - **Definição**: O número de lote é um identificador atribuído a um terreno específico dentro de um loteamento ou subdivisão. Ele é usado para fins de planeamento, registo e identificação de propriedades em documentos oficiais de urbanismo e imobiliários.
   - **Uso**: É frequentemente usado durante as fases iniciais de desenvolvimento imobiliário e pode permanecer em uso até que os lotes sejam construídos e ocupados.
 
### Número de Polícia:
   - **Definição**: O número de polícia, também conhecido como número de porta ou número de rua, é o identificador oficial atribuído a um edifício ou propriedade após a construção, geralmente para facilitar a localização postal e a prestação de serviços públicos.
   - **Uso**: É utilizado para endereçamento postal, entrega de serviços públicos (como eletricidade e água) e por serviços de emergência.
 
### Casos Específicos:
- **Atribuição do Número de Polícia**: Em muitas localidades, o número de polícia é atribuído somente após a conclusão da construção do edifício e pode levar anos, dependendo de fatores burocráticos e de desenvolvimento urbano.
- **Uso Continuado do Número de Lote**: Até que o número de polícia seja oficialmente atribuído, o número de lote continua a ser usado como a principal forma de identificação da propriedade, especialmente em documentos legais e administrativos.
 
### Exemplo de Processo:
**Planeamento e Desenvolvimento**: Durante o desenvolvimento de um novo loteamento, cada parcela de terreno é designada com um número de lote.
**Construção**: Quando um edifício é construído em um desses lotes, ele inicialmente ainda será identificado pelo número de lote.
**Atribuição do Número de Polícia**: Após a conclusão da construção e a aprovação final pelos órgãos municipais, o número de polícia é oficialmente atribuído e substitui o número de lote para fins de endereçamento e identificação pública.

Com interlocutores da administração local a opinião dada é que um lote é uma parcela de terreno, dentro de um loteamento e que é identificada por um número ou uma letra ou uma combinação de ambos. Esta numeração é dada apenas para identificar cada parcela dentro do loteamento nos posteriores processos de licenciamento da edificação. 
Já o número de polícia é dado numa fase posterior e não apenas aos lotes mas a todos os prédios (rústicos ou urbanos) que tenham uma porta ou portão de acesso à via pública. 
Num contexto urbanístico o número de lote nada tem a ver com o número de polícia no entanto, existem proprietários que sempre usaram o número de lote e nunca solicitaram outra numeração. Daí os grandes problemas da numeração de polícia existente em Portugal.
No entanto, e no que diz respeito à cartografia, o número de polícia a recolher pelos produtores deverá ser o número que se encontra no muro, edifício, porta ou portão (que se encontra materializado), independente de ser o número de lote ou de polícia. Qualquer que seja a forma de recolha destes números não é da competência do produtor saber distinguir que tipo de numeração é que está colocada, sendo que muitas vezes é tal a confusão que nem os município sabem se o número veio de um lote ou não. 

Resumindo, o número de lote e o número de polícia são numerações distintas e dadas em momentos diferentes.
 
Portanto, até que o número de polícia seja atribuído, os edifícios podem continuar a ser referidos pelo número de lote, mas isso não os torna sinónimos. O número de lote é um identificador temporário enquanto o número de polícia é o identificador permanente usado para todas as interações oficiais e práticas quotidianas.
 
Concluindo, apesar do número de lote e o número de polícia serem conceitos distintos e apesar destes números não serem intercambiáveis, o modelo de dados CartTop desta cartografia topográfica prevê um número de polícia. Se em fontes auxiliares de dados não existir número de polícia e é utilizado o número de lote este também pode ser escrito no campo de atributo https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/NumeroPolicia.html#go_up_numero que é do tipo texto.

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Esclarecido e Obrigado pela explicação.

Bom trabalho,
