### ISSUE TITLE
No atributo 'valorUtilizacaoAtual', qual a 'Designação' a usar para o valor 8?

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#229]
Para a classe de objetos 'Edificio', atributo 'valorUtilizacaoAtual', para o valor 8, a 'Designação' especificada tem 3 versões diferentes:
 1. 'Outros serviços coletivos, sociais e pessoais': no documento das especificações técnicas (CartTop v2.0.1);
 2. 'Serviços coletivos, sociais e pessoais': no Dicionário de objetos;
 3. 'Serviços coletivos sociais e pessoais': na Base de dados PostgreSQL/PostGIS (esta Designação não tem a virgula).

Qual a 'Designação' que deve ser utilizada?

**Comment by aserronha** [comment]
Bom dia,

Deve ser utilizada a opção "1. 'Outros serviços coletivos, sociais e pessoais': no documento das especificações técnicas (CartTop v2.0.1);"

Obrigado por detetar a incongruência... 
"Estes e outros" pequenos ajustes serão lançados brevemente numa próxima release. 
Na versão de desenvolvimento já se encontra a atualização em:
https://github.com/dgterritorio/RECART/commit/4fdaa4ea7997740e9b28d6b51a956bfddb1cd39a
