### ISSUE TITLE
column "inst_producao_id" referenced in foreign key constraint does not exist

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#23]
Ao correr o recart.ddl, obtém-se o seguinte erro:

psql:recart.ddl:1431: ERROR:  column "inst_producao_id" referenced in foreign key constraint does not exist

Está relacionado com o #19, que foi resolvido, mas não foi retirada a constraint:

https://github.com/dgterritorio/RECART/blob/master/recart.ddl#L1431

**Comment by dgterritorio** [comment]
Corrigido em https://github.com/dgterritorio/RECART/commit/4a6bb7908652f89b7b2f0fbd5bbb5afe0ff3edb9

Obrigado pela indicação.
