### ISSUE TITLE
Omissão dos tipos de artéria Palácios / Cabeço / Mirante / Rego - Listagem de Abreviaturas

### ISSUE THREAD

**Issue by pfteixeira** [dgterritorio/RECART#230]
Boa tarde,

Os tipos de artéria "Palácios" "Cabeço" "Mirante" "Rego" não se encontram na listagem de abreviaturas.
![1_Palácios](https://github.com/user-attachments/assets/6e63ff0d-3ce6-442d-9717-199a8eab5a99)
![2_Cabeço](https://github.com/user-attachments/assets/28aaced2-db14-4b8a-9a44-b83e38e8b15f)
![3_Mirante](https://github.com/user-attachments/assets/d09edd92-b6d4-44d4-b904-dd7070f6a133)
![4_Rego](https://github.com/user-attachments/assets/9bc4822c-b939-440f-9521-34aefc27e8c6)

**Comment by aserronha** [comment]
Boa tarde,
As abreviaturas podem ficar desta forma:

tipoViaRodovC | tipoViaRodovAbv | tipoViaRodovD
342 | PALS | Palácios
343 | CÇO | Cabeço
344 | MITE | Mirante
345 | RGO | Rego

Gostaríamos como nota de reforçar a ideia, para que fique claro, que quando existam dúvidas sobre a designação de uma artéria devem ser contactadas as entidades competentes que neste caso são as Autarquias sobre que tipologia atribuem ao local, se é rua ou outra formulação...

Obrigado!
