### ISSUE TITLE
Delimitação da Linha de Costa (LMPAVE)

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#232]
Boa Tarde, 

Segundo a versão 2x, a Linha de Costa é a linha da máxima preia-mar de águas vivas equinociais (LMPAVE). No nosso entendimento o que significa que corresponde à linha de máximo enchimento das marés.

Deste modo, esta linha não deve corresponder ao 0 hidrográfico, certo? Terá um valor superior. Pois não será a linha que estabelece a fronteira entre a terra e a água como acontecia na versão anterior do modelo de dados.

Estamos a interpretar corretamente? É isto que se pretende?

![image](https://github.com/user-attachments/assets/52acbcc4-1771-48fd-b187-500212bed8c2)

Nota: Sendo que esta informação ainda não nos foi facultada, iremos recolher a linha de costa tendo como base a Cobertura Aerofotográfica.

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Para responder a questões como esta devem passar a consultar a seguinte informação:
https://github.com/dgterritorio/BDNC/tree/main/cartografia2025/Dados_oficiais/Ag%C3%AAncia%20Portuguesa%20do%20Ambiente
