### ISSUE TITLE
Abreviatura de Ecovia em falta.

### ISSUE THREAD

**Issue by ElisabeteReisMuni** [dgterritorio/RECART#233]
Boa tarde,  
É necessário acrescentar ao CatalogoDasViasRodoviariasAbreviaturas a abreviatura de Ecovia.
![Picture1](https://github.com/user-attachments/assets/8bcd9f1d-e346-4c35-96f6-9e33b9214cca)

Atenciosamente,
ER

**Comment by aserronha** [comment]
Bom dia,

Não é necessário acrescentar ao catálogo abreviaturas para Ecovia. A Ecovia é considerado um "caso particular" de uma Ciclovia.

Exemplo de preenchimento do respetivo registo na tabela via_rodov: https://github.com/dgterritorio/RECART/blob/4fdaa4ea7997740e9b28d6b51a956bfddb1cd39a/recart.ddl#L1061

![image](https://github.com/user-attachments/assets/c8b95e82-6074-477e-b39c-c6d6d92f1246)

As especificações técnicas indicam o que a imagem anterior preconiza no preenchimento dos atributos:

![image](https://github.com/user-attachments/assets/bf276469-445d-41d3-8d10-6c006f1f3780)

**Comment by ElisabeteReisMuni** [comment]
Entendido e peço desculpa pelo meu lapso.

Obrigada
