### ISSUE TITLE
Representação de Áreas Artificializadas com a mesma Classificação

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#234]
Boa Tarde, 

**Como devemos proceder relativamente à área artificializada quando existe uma subestação numa zona industrial?**

1. Apenas representa-se a área artificializada referente à zona industrial – ‘_área de equipamentos industriais_’ e o respetivo ponto da subestação no tema elem_assc_eletricidade – ‘_subestação elétrica_’;

2.  Necessário destacar a delimitação da área artificializada para a subestação, mesmo sendo a mesma classificação da área artificializada referente à zona industrial – ‘_área de equipamentos industriais_’ e colocar o respetivo ponto da subestação no tema elem_assc_eletricidade – ‘_subestação elétrica_’;

![image](https://github.com/user-attachments/assets/8d3cba76-2279-4687-9a84-2a522f51df06)

Obrigado,

**Comment by aserronha** [comment]
> Boa Tarde,
> 
> **Como devemos proceder relativamente à área artificializada quando existe uma subestação numa zona industrial?**
> 
> 1. Apenas representa-se a área artificializada referente à zona industrial – ‘_área de equipamentos industriais_’ e o respetivo ponto da subestação no tema elem_assc_eletricidade – ‘_subestação elétrica_’;

> 2. Necessário destacar a delimitação da área artificializada para a subestação, mesmo sendo a mesma classificação da área artificializada referente à zona industrial – ‘_área de equipamentos industriais_’ e colocar o respetivo ponto da subestação no tema elem_assc_eletricidade – ‘_subestação elétrica_’;
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/370422466-8d3cba76-2279-4687-9a84-2a522f51df06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI3NzEsIm5iZiI6MTcyOTU4MjQ3MSwicGF0aCI6Ii82MDExMzg4OS8zNzA0MjI0NjYtOGQzY2JhNzYtMjI3OS00Njg3LTlhODQtMmE1MjJmNTFkZjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5N2FiZTAwMWI2YTRhZWY4NzE5NzliYmViNDBlY2EwMjRjM2FjNGRhM2E5NGY1NmJkOWQxYTExOGY1OGM3NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BLCHlknaFmYmrlvX1_63itDQuCW4Hr28paXcxDfjtpQ)
> 
> Obrigado,

Bom dia,

É necessário destacar dentro da lógica da Regra específica 7.9. devido à particularidade das áreas definirem limites distintos para equipamentos coletivos, instalações de produção, instalações de gestão ambiental e/ou outras infraestruturas. Iremos acrescentar "outras infraestruturas" às Especificações técnicas para ser ainda mais detalhado.

Podem existir recortes de áreas dentro de áreas de forma a garantir que não se sobrepõem geometricamente.

Resumindo, existe(m) a(s) área(s) de equipamentos industriais (Zona Industrial de Amorim) e existe a área de equipamentos industriais com o ponto que caracteriza a Subestação elétrica (Subestação Beiriz, ver exemplo em https://www.dgterritorio.gov.pt/recart/imagens/eElemAssocEletricidade-valorElementoAssociadoElectricidade2-1.jpg) que não se sobrepõem geometricamente.

**Comment by CatarinaGaspar** [comment]
Bom dia

Sim, está esclarecido.

Obrigado,
