### ISSUE TITLE
Representação do Posto Transformação no tema Edificio vs Eletricidade

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#235]
Bom Dia, 

Como devemos proceder nas seguintes situações:

**1-	Os postos de transformação (PTR) embutidos nas paredes devem ser representados em ambos os temas, edificios e elemento associado à eletricidade?**
`a.` Não se representam em nenhum dos temas;
`b.` Apenas se representa no tema elemento associado à eletricidade, dado que não coexiste em um edificio independente;
`c.` Outra opção;

![image](https://github.com/user-attachments/assets/f6c06a3a-41dc-43fa-9412-e66a8d0f310d)

**2-	Os PTR existindo em edificios independentes, adjacentes a outros devem ser representados em ambos os temas, edificio e elemento associado à eletricidade, correto?**
No entanto, para o caso de o poligono do edificio não ter área mínima de representação, segundo as regras, este deve ser eliminado. O PTR pode apenas existir no tema elemento associado à eletricidade e não existir no tema edificio?

![image](https://github.com/user-attachments/assets/15d7e4ae-d60c-492e-a155-18fad44126a3)

Obrigado,

**Comment by aserronha** [comment]
> Bom Dia,
> 
> Como devemos proceder nas seguintes situações:
> 
> **1- Os postos de transformação (PTR) embutidos nas paredes devem ser representados em ambos os temas, edificios e elemento associado à eletricidade?**
`a.` Não se representam em nenhum dos temas; 
`b.` Apenas se representa no tema elemento associado à eletricidade, dado que não coexiste em um edificio independente;
`c.` Outra opção;
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/370618011-f6c06a3a-41dc-43fa-9412-e66a8d0f310d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTQ2NzMsIm5iZiI6MTcyOTY5NDM3MywicGF0aCI6Ii82MDExMzg4OS8zNzA2MTgwMTEtZjZjMDZhM2EtNDFkYy00M2ZhLTk0MTItZTY2YThkMGYzMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MzkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhN2NhNWQxMWQ5MGQ1ODk0NjE0YWI2YWFlNWJiN2E5ZjMxNDc4YzE1MDdlMmI2OTIxNzY0OWExM2E4YzBmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UST71lcLEa4-6cV9Q-oDQ3YxkTeyl0EJGxE451BM27Y)
> 
**resposta: Se a construção for um edifício apenas para o "Posto Transformador" representam-se em ambos os temas: Construções (Edifício) e INFRAESTRUTURAS E SERVIÇOS DE INTERESSE PÚBLICO (Elemento associado de eletricidade). Se o "Posto transformador" coexistir noutro tipo de edifício que já esteja representado de outra forma/utilização deve ser como identificam em 'b'.**

> **2- Os PTR existindo em edificios independentes, adjacentes a outros devem ser representados em ambos os temas, edificio e elemento associado à eletricidade, correto?** No entanto, para o caso de o poligono do edificio não ter área mínima de representação, segundo as regras, este deve ser eliminado. O PTR pode apenas existir no tema elemento associado à eletricidade e não existir no tema edificio?
> 
> ![image](https://private-user-images.githubusercontent.com/60113889/370618409-15d7e4ae-d60c-492e-a155-18fad44126a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTQ2NzMsIm5iZiI6MTcyOTY5NDM3MywicGF0aCI6Ii82MDExMzg4OS8zNzA2MTg0MDktMTVkN2U0YWUtZDYwYy00OTJlLWExNTUtMThmYWQ0NDEyNmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MzkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzQ2ODIxZTRkMGQ2Yjk4NmQwOWY3MjkwZThhNGNiOWUyMzI4Mzg0Yzc3ZmM5ZTY5MTUyY2MyY2Y3NjNiMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yjta14g2RvRmOFzysBGXRhXYlcHlkktBIMQ0YMvFeW4)
> 
**resposta: A abordagem à regra específica 6.6 está correta. O PTR pode apenas existir no tema elemento associado à eletricidade e não existir no tema edificio.**
**Nota: Admitimos que as imagens são da mesma zona mas é de difícil percepção essa análise. Partimos do princípio que os edifícios estão mesmo contíguos.** 

> Obrigado,

**Esclarecido @CatarinaGaspar ?**

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Sim está esclarecido.

Obrigado,
