### ISSUE TITLE
Clarificação de conceitos: Central Fotovoltaica e Painel Solar Fotovoltaico

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#236]
Bom Dia, 

Compreendemos ambos os conceitos e sabemos em que situações se aplicam. No entanto temos deparado com situações que nos têm suscitado duvidas. 

**As situações ilustradas nas imagens abaixo são painéis solar, correto?** 

Os painéis solares aí existentes têm a função de converter a energia solar em energia elétrica, a qual pode ser utilizada para diversos fins, seja diretamente, armazenada ou injetada na rede, nos casos abaixo é usada para a produção agrícola.
![image](https://github.com/user-attachments/assets/0e520f52-5db1-48c7-8706-7f052d56f992)

Obrigado,

**Comment by aserronha** [comment]
Resposta: Se houver evidências que o os blocos de conjunto de painéis são para ser utilizados como microprodução (eletricidade essencialmente produzida para consumo próprio apesar do excedente ser passível de ser entregue a terceiros ou à rede pública) devemos representar esses painéis como descrito no esquema https://www.dgterritorio.gov.pt/recart/imagens/eElemAssocEletricidade-valorElementoAssociadoElectricidade5-3.jpg 

Por outro lado, as centrais solares fotovoltaicas são conjuntos de painéis usados em maior escala com o principal objetivo da eletricidade produzida ser entregue a terceiros ou à rede pública e, como tal, devem representar apenas um ponto que caracteriza a delimitação da área artificializada como descrito no esquema https://www.dgterritorio.gov.pt/recart/imagens/eElemAssocEletricidade-valorElementoAssociadoElectricidade1.2-1.jpg

**Comment by CatarinaGaspar** [comment]
Bom dia, 

Esclarecido. 

Obrigado,

**Comment by aserronha** [comment]
> Bom dia,
> 
> Então no caso de grupo de painéis solares só é necessário o ponto de eletricidade, não se representa qualquer área artificializada. É isso?
> 
> Caso leve área artificializada, devemos representar como área "industrial" na mesma para o NDd2? sendo que não existe a obrigatoriedade de painel solar para este NDd.
> 
> Obrigado,

Boa tarde,

Esperamos que a versão 2.0.2 das Especificações técnicas e os esquemas do "13. Painel solar fotovoltaico" em https://www.dgterritorio.gov.pt/recart/imagens/eConstruPolig-valorTipoConstrucao13-2.jpg e da "1.2 Central fotovoltaica" em https://www.dgterritorio.gov.pt/recart/imagens/eElemAssocEletricidade-valorElementoAssociadoElectricidade1.2-1.jpg ajudem a clarificar a representação destas temáticas quando os painéis estão ou não contidos em Centrais/Parques fotovoltaicos.
