### ISSUE TITLE
Representação de Segmentos de Vias nas Estruturas de Captação de Água

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#237]
Bom Dia, 

#219 

Dado o contexto em que se insere e estando desconetado da restante rede, o segmento pode não ser representado, certo?

![image](https://github.com/user-attachments/assets/f21c9109-2c6d-4a7b-82d4-cc00e9793a04)

Obrigado,

**Comment by aserronha** [comment]
Certo!
