### ISSUE TITLE
recart.dll não funciona em máquinas windows

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#24]
Estava a tentar correr o ficheiro recart.dll em windows e deparei-me com as seguintes dificuldades:

O comando sugerido dá erro:

    psql -U postgres postgres -f recart.ddl

    psql: warning: extra command-line argument "-f" ignored
    psql: warning: extra command-line argument "recart.ddl" ignored

A razão é que, pelo menos em windows não pode haver comandos com "traço" após comandos sem nada. Por isso tive de mudar a ordem para:

```
psql -f recart.ddl -U postgres postgres 
```

Em segundo lugar, ao que parece, o Windows não reconhece o locale pt_PT.UTF-8, pois usa um namespace totalmente diferente (e que não segue qualquer standard...) Assim, para correr em Windows tive de alterar a linha que cria a base de dados para:

```
CREATE DATABASE recart WITH ENCODING 'UTF8' LC_COLLATE='Portuguese_Portugal' LC_CTYPE='Portuguese_Portugal' TEMPLATE='template0';
```

**Comment by dgterritorio** [comment]
Alterado com a indicação dos locale a serem utilizados nos sistemas operativos Windows e Linux
https://github.com/dgterritorio/RECART/commit/89030faf4eb538a97924149c3faa3cb5b1b314ad
