### ISSUE TITLE
Qual a versão da CarTop a utilizar ?

### ISSUE THREAD

**Issue by martabmatos** [dgterritorio/RECART#240]
Boa tarde,

No âmbito da produção cartográfica de um projeto que teve início em 2021 (tendo existido da parte do proprietário do projeto várias alterações) qual a versão da CarTop a utilizar? 

Esta dúvida surge no seguimento do que consta na vossa página em que refere que "A nova versão, designada CartTop v2.0, entra em vigor no dia 1 de Maio de 2024. Os projetos de produção de cartografia topográfica a iniciar a partir desta data devem ser desenvolvidos de acordo com os termos definidos na versão CartTop v2.0."

Agradeço a atenção.
Marta Matos

**Comment by aserronha** [comment]
Bom dia,

Como o projeto teve inicio em 2021 está abrangido pela não obrigatoriedade de utilização da versão 2.0. Compete ao adjudicante decidir se usa a versão em vigor à data de início do trabalho (2021), ou se prefere passar os dados já existentes para a versão 2.0 e concluir o trabalho já nesta versão.

Para a DGT, como entidade homologadora, a utilização da versão 2.0, em vigor desde maio deste ano, é sempre uma opção mais favorável.

**Comment by martabmatos** [comment]
Boa tarde,

Agradeço o esclarecimento.

Marta Matos
