### ISSUE TITLE
Linhas ZigZag em frente aos Parqueamentos

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#241]
Bom dia, 

Entendemos que os parqueamentos devem ser divididos sempre que houver algum tipo de materialização, como pintura ou obstáculo físico.
No caso em questão, trata-se de um único parqueamento, porém com a restrição de não estacionar nas áreas demarcadas pelos zig-zags.

Por esse motivo, fica implícita a obrigatoriedade de dividir os parqueamentos?

![image](https://github.com/user-attachments/assets/6dacf239-1f4d-4e12-8fef-1debe4f2962a)
![image](https://github.com/user-attachments/assets/5865e2fc-1b29-4d02-8d31-839a68441b20)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Cada caso é um caso. Neste caso concreto é aceitável representar apenas uma área de Parqueamento.

Situações como esta é aceitável representar de qualquer das formas o(s) Parqueamento(s) em https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/InfraTransRodov.html#page_valorTipoInfraTransRodov desde que os atributos sejam coerentes. 
Relembramos que a representação de várias áreas (https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/AreaInfraTransRodov.html) podem ser relacionadas com o mesmo Parqueamento. 

Já respondemos a essas questões e este esquema elucida que por vezes pode representar-se de uma ou outra forma:
https://www.dgterritorio.gov.pt/recart/imagens/eInfraTransRodov-valorTipoInfraTransRodov3-1.jpg
