### ISSUE TITLE
Equipamento Coletivo – Campo de Golfe

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#242]
Bom dia, 

O valor 'Campo de Golfe' do equipamento coletivo deve ser associado ao edificio dentro dessa área ou exclusivamente à tabela de áreas artificializadas (equip_util_coletiva_id)? 

Levantamos essa questão porque o valor 'Campo de Golfe' não se refere exatamente a um edifício, mas sim a uma área, seguindo a mesma lógica aplicada a parques e jardins. Da mesma forma, não vinculamos esse valor ao tema 'edifício', mas apenas à área artificializada.

![image](https://github.com/user-attachments/assets/f226b2c0-9229-425b-a826-0d1f32d09b1c)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Se forem edifícios de apoio ao Campo de Golfe devem fazer parte do Equipamento. Outros edifícios que estejam contidos no Campo de Golfe que eventualmente não façam parte do Equipamento não é necessário estabelecer relação.

O mesmo se aplica a outras Infraestruturas/Equipamentos.
