### ISSUE TITLE
tabela"valor_tipo_servico_infra_trans_rodov"

### ISSUE THREAD

**Issue by socart** [dgterritorio/RECART#25]
Boa Tarde, 

1 - À semelhança das outras tabelas que estabelecem relações, acho que o nome da tabela "valor_tipo_servico_infra_trans_rodov" deveria ser lig_valor_tipo_servico_infra_trans_rodov.

Obrigada,

**Comment by dgterritorio** [comment]
Concordamos, já foi alterado.
Todas as tabelas que ligam outras duas tabelas começam por "lig_".
Obrigado.
