### ISSUE TITLE
Tabelas de Dominio sem correspondência de Campos

### ISSUE THREAD

**Issue by socart** [dgterritorio/RECART#26]
Boa Tarde, 

Na versão do modelo de dados disponibilizado a 16.12.2019, não encontramos os campos onde usar as tabelas de dominio: 

- "valor_prop_gravidade"
-"valor_origem"
-"valor_metodo_aquis"
-"valor_elemento_associado_rede_agua"

Relativamente a esta última, a tabela correcta é "valor_elemento_associado_agua.

Obrigada,

**Comment by dgterritorio** [comment]
Foi feita a remoção dessas tabelas de códigos antigas sem correspondência no modelo actual.

https://github.com/dgterritorio/RECART/commit/704ea43655fe6f1bdcabfa977bf69976edb59797
