### ISSUE TITLE
QGIS e relações "many to many"

### ISSUE THREAD

**Issue by geotoz** [dgterritorio/RECART#30]
Boa tarde,
A chave primária das tabelas de ligação para estabelecer relações many-to-many, como por exemplo, lig_valor_utilizacao_atual_edificio, deverá ser a composição do identificador do edificio com o identificador da tabela valor_utilizacao_atual. Não só esta alteração tornará mais "correta" a base de dados, como permitirá ao QGIS implementar as relações nos formulários, uma vez que existe esta imposição no software:
"Avoid using multiple fields in the primary key in a pivot table. QGIS assumes a single primary key so a constraint like constraint airports_airlines_pkey primary key (airport_fk, airline_fk) will not work."

Ver: https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/attribute_table.html#introducing-1-n-relations
Obrigado.

**Comment by dgterritorio** [comment]
Existe uma incongruência entre o que refere e a citação que faz.
De qualquer modo a estrutura de duas tabelas de ligação foi alterada para permitir a utilização dos formulários em QGIS.
https://github.com/dgterritorio/RECART/commit/6b28354e1525096eead640ab38367740bac82e45
