### ISSUE TITLE
valorAreasAgricolasFlorestaisMatos

### ISSUE THREAD

**Issue by asalvaterra** [dgterritorio/RECART#31]
Boa tarde,
relativamente à lista valor AreasAgricolasFlorestaisMatos,

 os valores 1.1; 1.2; 1.3; 1.4; 1.5; 4.1.1; 4.1.2; 4.1.3; 4.1.4; 4.1.5; 4.1.6; 4.1.7; 4.2.1; 4.2.2; 4.2.3 só constam parao NdD2. Não deveriam também constar para o Ndd1?

Obrigada

Ana Salvaterra

**Comment by aserronha** [comment]
Bom dia,
A opção por não detalhar o nível de detalhe 1 foi deliberada.
Entendeu-se que a informação referente à ocupação do solo não é muito relevante na cartografia topográfica, uma vez que já está representada na cartografia temática Carta de Uso e Ocupação do Solo (COS). A informação desta carta pode ser utilizada como fonte de dados para o nível de detalhe 2.
Como o nível de detalhe 1 não tem uma fonte de dados equivalente, entendeu-se que deve ser mais genérico, ficando as classes mais detalhadas como opcionais.

**Comment by asalvaterra** [comment]
Faz sentido. Obrigada pelo esclarecimento.

Cumprimentos

Ana Salvaterra
