### ISSUE TITLE
Poste telefónico

### ISSUE THREAD

**Issue by asalvaterra** [dgterritorio/RECART#32]
Boa tarde,

o poste telefónico não é obrigatório para nenhum Nível de Detalhe?

Obrigada

Ana Salvaterra

**Comment by aserronha** [comment]
Boa tarde,

Na versão 1.0 por causa de algumas questões técnicas não foi introduzido, mas na versão 1.1 vai ser obrigatório para o NdD1 apenas.
O objeto teve pequenas reformulações que vão ser disponibilizadas brevemente aqui no dicionário de objetos e de seguida nas especificações técnicas v1.1.
