### ISSUE TITLE
Gestão de versões no Git(hub)

### ISSUE THREAD

**Issue by ricardodepinho** [dgterritorio/RECART#33]
Constatando esta ultima alteração:
https://github.com/dgterritorio/RECART/tree/master/versoes/v1.1
Devo recomendar a leitura:
https://help.github.com/pt/github/administering-a-repository/about-releases
As versões se baseiam em tags Git, que marcam um ponto específico no histórico do seu repositório.
https://help.github.com/pt/github/administering-a-repository/managing-releases-in-a-repository

**Comment by dgterritorio** [comment]
Fizemos a alteração.

https://github.com/dgterritorio/RECART/releases/tag/v1.1

Obrigado

**Comment by ricardodepinho** [comment]
Bom trabalho. Parabéns!
