### ISSUE TITLE
Infraestrutura de transporte rodoviário

### ISSUE THREAD

**Issue by geotoz** [dgterritorio/RECART#34]
Na tabela Infraestrutura de transporte rodoviário, o atributo valor_tipo_servico encontra-se presente nesta tabela, por outro lado, existe uma tabela de ligação denominada iig_valor_tipo_servico_infra_trans_rodov que se contrariam.
Obrigado

**Comment by dgterritorio** [comment]
Corrigido.
https://github.com/dgterritorio/RECART/commit/f8e2666f6b093b7c144b673ff23e01af69d1a469

Obrigado pela colaboração.
