### ISSUE TITLE
campos não obrigatórios nas tabelas: inst_producao e equip_util_coletiva

### ISSUE THREAD

**Issue by socart** [dgterritorio/RECART#35]
Bom dia, 

Existem as seguintes disparidades entre a estrutura do modelo de dados (v1.1) e ET:

1 – O campo “_descricao_da_funcao”_ na tabela **inst_producao**, nas ET não é de preenchimento obrigatório, mas na BD aparece como tal.
 ![inst_producao1](https://user-images.githubusercontent.com/60113889/81174617-10ee2700-8f9a-11ea-83fe-3f2c2bdf5446.png)

2- O campo “_ponto_de_contacto_” na tabela **equip_util_coletiva**, nas ET não é de preenchimento obrigatório, mas na BD aparece como tal.

![equip_coletiva](https://user-images.githubusercontent.com/60113889/81174738-472ba680-8f9a-11ea-9d23-27a1d87ee1ea.png)

Obrigado,

**Comment by dgterritorio** [comment]
Corrigido em https://github.com/dgterritorio/RECART/commit/00c83d921f0a9abe8d610c00c7f169219182cf15
Este atributos são apenas para utilizar na fase de exploração.
Obrigado pela colaboração.
