### ISSUE TITLE
Falta tabela ligacaoEquipUtilColetiva_AreasArtificializadas 

### ISSUE THREAD

**Issue by socart** [dgterritorio/RECART#36]
Bom dia, 

Na nova versão 1.1 do modelo de dados está em falta a tabela de ligação que estabelece a relação de muitos para um entre a tabela equipamento de utilização coletiva e as áreas artificializadas.

Por exemplo dentro de uma área artificializada de "Equipamentos de educação" podem existir vários edificios que compõem uma escola, ou nestas situações como deveria ficar?

![tab_lig](https://user-images.githubusercontent.com/60113889/81175170-f7011400-8f9a-11ea-843e-e522c6cfa876.png)

Bom trabalho,

**Comment by dgterritorio** [comment]
Estivemos a reavaliar esta relação e:

Parte-se do princípio que um equipamento de utilização coletiva é composto por 1 ou mais edifícios e 0 ou mais áreas artificializadas. 

Tal como está, a existir a relação entre os equipamentos de utilização coletiva  e as áreas artificializadas, esta está definida através do atributo "equip_util_coletiva_id" da tabela  areas_artificializadas. Esta solução permite ter 0 ou várias áreas associadas ao equipamento.

Quanto ao equipamento, por exemplo o Hospital de Santa Maria, pode ter ainda vários tipologias definidas através do atributo valorTipoEquipamentoColetivo [1..*] . 

Considerou-se também que normalmente estes equipamentos a terem área, ela é bem definida, através de muros, cercas ou vias de transportes, correspondendo aos limites do poligono da área artificializada, e que isso corresponde a apenas um equipamento de grandes dimensões.

Assim a base de dados mantem-se como está e foram corrigidas as relações no ficheiro JSON e UML em https://github.com/dgterritorio/RECART/commit/6723767359b2d462768b90b6c6d41dcb9859f2a4.

Obrigado pela colaboração.
