### ISSUE TITLE
lig_valor_tipo_servico_infra_trans_rodov

### ISSUE THREAD

**Issue by geotoz** [dgterritorio/RECART#37]
Boa tarde,

Na tabela infra_trans_rodov, está presente o campo valor_tipo_servido, por outro lado existe a tabela de ligação lig_valor_tipo_servico_infra_trans_rodov. Qual é a versão final, é a que se refere à relação um para muitos, ou a que estebelece a relação de muitos para muitos através da tabela de ligação supracitada?

Obrigado.

**Comment by aserronha** [comment]
Boa tarde,

Isso já foi corrigido na versão de desenvolvimento https://github.com/dgterritorio/RECART/blob/master/recart.ddl quando fechámos a “issue” a semana passada. Pode ver aqui: https://github.com/dgterritorio/RECART/commit/f8e2666f6b093b7c144b673ff23e01af69d1a469

A correção de bugs na v1.1 não vai acontecer. Em breve vai ser feita uma nova release v1.1.1 para corrigir este e outros bugs entre o documento das especificações técnicas v1.1 e a BD.
