### ISSUE TITLE
relação segmento via com limite rodovia

### ISSUE THREAD

**Issue by asalvaterra** [dgterritorio/RECART#39]
![segvia](https://user-images.githubusercontent.com/62557275/82822833-58334d80-9e9e-11ea-8222-49b4fa3b33a2.JPG)

No exemplo anexado, a dúvida que se coloca é a seguinte:

Como se faz a ligação do segmento de via ao limite da via, sendo que para cada segmento de via teremos que ter dois limites relacionados?

Na tabela de relações disponibilizada em:
http://www.dgterritorio.gov.pt/recart/RELACOES/relacoes.html 
não existe obrigatoriedade na ligação entre o segmento de via e o limite de rodovia. Foi um erro de preenchimento ou não existe, mesmo, essaobrigatoriedade?

Obrigada

Ana Salvaterra

**Comment by aserronha** [comment]
Respostas da DGT:

Resposta à 1ª questão:
Não é necessário haver sempre 1 ou 2 limites relacionados com o segmento da via rodoviária até porque existe a regra de representação dos limites apenas de acordo com a largura da via (NdD1>1m e NdD2>5m). 
A ligação ao segmento da via rodoviária (não obrigatória) pode ser feita apenas com a linha amarela que na imagem diz "limite" e com "um bocadinho" de linha azul que está com ??? ... ou então pode também ser estabelecida relação (não obrigatória) apenas com a o bocado de linha amarela "limite". O bocado azul de "Separador " tem de estar "partido" adequadamente (1 ou 2 vezes na zona de ???) dependendo se se considerou que um desses bocadinhos estará relacionado com o que na imagem (a rosa) diz "segmento de via".

Resposta à 2ª questão:
É necessário "partir" adequadamente o "Segmento da via rodoviária" e a "Via rodoviária - Limite".... mas não é obrigatório estabelecer a relação entre ambos nas tabelas da BD apesar da BD permitir que essas relações possam ser feitas.
