### ISSUE TITLE
Catálogo das vias rodoviárias (Abreviaturas)

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#42]
No Catálogo das vias rodoviárias (Abreviaturas) para o "tipoViaRodovD" = Vivenda, o valor para "tipoViaRodovAbv" está vazio. Os CTT, no seu manual de endereçamento, recomendam o valor "VV". Como os restantes valores do referido manual já estão presentes neste Catálogo, este valor também poderia ser contemplado.

**Comment by aserronha** [comment]
Boa tarde caro Aurélio,

Agradecemos o comentário mas gostaríamos de informar que o que interessa desta componentes generalizada de endereços são as que tenham correspondência com as vias rodoviárias do objeto 'Segmento da via rodoviária', ou seja, do catálogo as componentes que vão interessar são: "Componente do endereço" = "Tipo de artéria" .

A "Componente do endereço" = "Tipo de Porta" que refere, achamos que não se adequa à tipologia a associar ao 'Segmento da via rodoviária'.

Ficou com dúvidas quanto a este esclarecimento?

De qualquer das formas vamos avaliar com o Instituto Nacional de Estatística (INE) o porquê de não constar esse valor...

**Comment by anvpires** [comment]
Concordo com o que refere, mas a minha observação está relacionada com a lista de abrevisturas constante em
https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html
que inclui no elemento 247, tipoViaRodovD = Vivenda, para o qual a abreviatura segerida pelos CTT é VV, ou seja, tipoViaRodovAbv = VV

**Comment by aserronha** [comment]
Boa tarde!
Se fizer refresh à lista poderá ver que já foi inserido VV. 
Agradecemos e antes de encerrar esta "issue" aproveito para informar que já contactámos o INE para saber se foi um lapso e para confirmar se também utilizam VV. Assim que tivermos essa resposta documentamos aqui e encerramos esta notificação.
Muito obrigado, em nome da equipa da DGT!

**Comment by aserronha** [comment]
Boa tarde, não obtivemos resposta até hoje e por isso decidimos encerrar esta issue sendo que VV = tipoViaRodovAbv para Vivenda, na lista de abreviaturas.
