### ISSUE TITLE
Definição de Edifício

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#43]
Para normalizar, a definição de "Edifício" devia ser exatamente a que consta do Decreto Regulamentar n.º 5/2019, de 27 de setembro, também ele da responsabilidade da DGT: 
_Um edifício é uma construção permanente, dotada de acesso independente, coberta, limitada por paredes exteriores ou paredes-meeiras que vão das fundações à cobertura, destinada a utilização humana ou a outros fins._

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Agradecemos desde já o seu contributo.

Achamos prudente manter a definição de Edifício que temos na versão atual das Especificações Técnicas (ET) de Cartografia Topográfica.

Não é possível estabelecer uma relação direta entre estas especificações e o Decreto Regulamentar n.º 5/2019, de 27 de setembro. Este decreto fixa exclusivamente conceitos técnicos nos domínios do ordenamento do território e do urbanismo e as especificações de cartografia são mais transversais e pretendem  servir múltiplas finalidades. 

Além de que o DR 5/2019 tem outros conceitos relacionados com o edifício, para além do Edifício propriamente dito, nomeadamente Edificação e Edifício Anexo.  

Nas ET de Cartografia Topográfica todos estes conceitos estão incluídos no objeto Edifício, logo a definição nas especificações tem que ser mais abrangente. As definições das ET de cartografia topográfica são transversais e tiveram como base o INSPIRE Registry: https://inspire.ec.europa.eu/theme/bu. A título de exemplo podemos indicar o telheiro, que segundo o Inspire é considerado edifício (quanto à sua forma) e que não encaixa na definição de edifício do DR 5/2019.

A utilização da cartografia no âmbito do ordenamento do território e o urbanismo terá de passar necessariamente por um  mapeamento adequado do objeto Edifício destas ET para, por exemplo, Edifício, Edificação ou Edifício Anexo, tal como previsto no DR 5/2019.
