### ISSUE TITLE
Elemento "barreira"

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#44]
Quando pretendemos adicionar um elemento à "barreira", ocorre um erro:
'ERROR: Invalid geometry type only linestring or polygon are accepted!
CONTEXT: PL/pgSQL function trigger_linestring_polygon_validation() line 6 at RAISE
![erro_barreira](https://user-images.githubusercontent.com/60008526/106164589-0c018100-6182-11eb-9f4f-61a7c85902f6.png)

A única forma de o fazer é desativar o trigger, o que não é funcional.

**Comment by dgterritorio** [comment]
Corrigido em https://github.com/dgterritorio/RECART/commit/442034b8d595429a04828cc71f98bcfb32be8571

Obrigado pela colaboração.

**Comment by SrNetoChan** [comment]
@dgterritorio, embora compreenda que não queiram lançar demasiadas versões, acho que seria pertinente que este tipo correcção de erros, que não implicam mudanças no modelo de dados em si, fosse publicada o quanto antes numa nova versão, ou mesmo apenas como um patch à versão existente. Caso contrário continuaremos-nos a deparar-nos com os mesmos problemas várias vezes. Para além disso, nem toda a gente vai ver os issues fechados do github :-)
