### ISSUE TITLE
Especificidade de "Outro" (Ponto de Interesse)

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#45]
Na pág. 112 do documento CartTop-V1.1, para uniformizar e ser específico, o valor "13 Outro" devia ser alterado para "13 Outro - Ponto de Interesse" à semelhança do que acontece com os restantes, nomeadamente "Outro - Local Nomeado", "Outro - Administração Pública", "Outros - Serviços" "Outro - transportes", "Outro - saúde", etc.

Ainda em relação ao documento CartTop-V1.1, existe uma gralha, não referida na atual Errata, no topo da pág. 75, na apresentação do Tema "[08] INFRAESTRUTURAS E SERVIÇOS DE INTERESSE PÚBLICO" a definição apresentada é a do Tema "[07] OCUPAÇÃO DO SOLO" (Cobertura física e biológica do território, incluindo superfícies artificiais, áreas agrícolas, florestas e áreas seminaturais).

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Agradecemos desde já o seu contributo.

A DGT aceitou a uniformização do valor "13 Outro" para "13 Outro - Ponto de Interesse". A alteração a este valor terá efeito na próxima versão das especificações técnicas e da base de dados.

Em relação ao documento agradecemos a deteção da gralha e iremos corrigir na próxima versão da Errata.

**Comment by dgterritorio** [comment]
Alterado em https://github.com/dgterritorio/RECART/commit/18a44269f5f08972ea39c35575fbccc124ca7d10#diff-c482a25172dea236ecb1bd4a76f940459d20473d8cb3576fd12aac5b5bc4f0bd
