### ISSUE TITLE
Cabo de Telecomunicações

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#46]
De forma semelhante ao que acontece com a Entidade "Cabo Elétrico", também poderia existir a Entidade "Cabo de Telecomunicações", já que existem PDMs que incluem na sua Carta de Infraestruturas a rede de telecomunicações, nomeadamente a rede de fibra ótica.

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Agradecemos mais uma vez pelo seu contributo.

Os objetos e respetivos atributos nas normas e especificações técnicas de cartografia topográfica resultam de um compromisso que permite que esta cartografia seja passível de ser produzida e que responda à maioria das utilizações.

No entanto, a utilização desta cartografia para um determinado fim específico poderá ser insuficiente. Nestas circunstâncias terá que se recorrer a outras fontes de dados.

A cartografia topográfica não pode ter em consideração todas as especificidades inerentes às várias cartografias temáticas específicas que os utilizadores necessitam. Vão sempre existir objetos, atributos e inúmeros valores que não estão contemplados nestas normas e que resultam do compromisso acima referido.

A DGT, no futuro, poderá vir a prever a criação de extensões ao modelo existente, de acordo com regras a definir. Estas extensões permitiriam enquadrar as eventuais lacunas que não tenham sido previstas neste modelo base.

**Comment by anvpires** [comment]
Partilho do entendimento de que contemplar regras de extensão ao modelo fomenta a abrangência e a longevidade destas normas. Este é, seguramente, um dos requisitos mais relevantes a incluir na evolução destas normas.
