### ISSUE TITLE
Número de Polícia / Número de Edifício

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#47]
A definição de "Número de Polícia" na CartTop inclui o caso de "recintos", mas se o recinto não possuir qualquer edifício e possuir um portão com uma simples caixa postal, o Número de Polícia não pode ser registado uma vez que este é atributo da Entidade "Edifício", ou seja, só se podem registar Números de Polícia como atributo de Edifícios (os Números de Polícia não estão georreferenciados). Correto?

Embora o termo "Número de Polícia" seja vulgarmente utilizado, atendendo à Lei n.º 76/2013, que estabelece o regime jurídico das autarquias locais, na alínea tt) do n.º 1 do artigo 33.º refere que compete à câmara municipal "estabelecer as regras de numeração dos edifícios", a designação mais adequada seria "Número de Edifício". Se a competência das Câmaras Municipais é atribuir "Números de Edifício" (há muitos Regulamentos Municipais sobre este assunto que referem "Numeração de Edifícios")  e se no modelo CartTop este Número é atributo da entidade "Edifício" porque não designá-lo por "Número de Edifício"?. Que explicação existe para que este Número seja "de Polícia" e que relação tem com a Polícia?
E a definição deste atributo podia passar a ter no final "vulgarmente designado por Número de Polícia".

Por curiosidade, a  Portaria 5690 de 1928 (já revogada) refere que "as embarcações à vela tenham marcado nas velas o seu número de polícia": https://dre.pt/application/file/a/603590

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Vou transcrever as respostas da DGT às suas questões.

Quanto à primeira questão podemos dizer que sim, correto, os números de polícia apenas são registados como atributos dos edifícios e este atributo é apenas obrigatório para o NdD1.
Esta opção foi deliberada de forma a simplificar o modelo e a aquisição deste tipo de informação.

Quanto à segunda questão, considerando que o termo “Número de Polícia” é um termo de utilização mais generalizada e transversal , consideramos mais adequado manter esta designação, apesar de nem todos os números de polícia estarem representados neste tipo de cartografia.

Concluindo, gostaríamos de acrescentar que existe a necessidade de consolidar o modelo nesta fase mas admitimos num futuro próximo rever esta modelação sabendo da mais valia de uma relação entre o número de polícia (que não seja apenas atributo de Edifício) e por exemplo o tema dos Transportes (Transporte rodoviário).
