### ISSUE TITLE
Posto de abastecimento de combustíveis

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#48]
Na lista de valores "ValorTipoInfraTransRodov", para o caso "8 Posto de abastecimento de combustíveis", uma vez que contempla não só o fornecimento de combustíveis como de energia a Descrição mais apropriada seria "8 Posto de abastecimento".

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Percebemos o reparo mas vamos manter esta designação porque são termos de uso comum e descrito na legislação como Posto de Abastecimento de Combustíveis (PAC). Ver: https://www.dgeg.gov.pt/pt/areas-setoriais/energia/combustiveis/licenciamento/postos-de-abastecimento-de-combustiveis-pac/ 

O que acontece é que por vezes em muitos PAC já existe também "Abastecimento elétrico" e o modelo permite que seja introduzida mais essa valência no atributo "valorTipoServiço" de multiplicidade [1..n] onde é possível discriminar se existe "abastecimento de combustível" e também "abastecimento elétrico", entre outros serviços que constam na lista de códigos.

Para evitar confusões, existe no '[09.01] Mobiliário Urbano e sinalização' o valor #16 com a descrição "Posto de carregamento elétrico" que contempla estes "postos" em lugares de estacionamentos reservados ou semelhantes.
