### ISSUE TITLE
Câmara de visita (Telecomunicações)

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#49]
No 'valorElementoAssociadoTelecomunicacoes' sugere-se acrescentar valor 'Câmara de visita' (Compartimento que permite aceder à conduta ou à tubagem de rede de telcomunicações), tal como acontece com o 'valorElementoAssociadoAgua'.

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Já foi discutido em conjunto com a Direção Regional do Ordenamento do Território da Região Autónoma da Madeira esta inclusão e enquanto eles procederam a essa inclusão já na sua primeira versão 1.0 das Especificações Técnicas (ET) em 12 de março 2021:
https://irig.madeira.gov.pt/index.php/recursos/utilitarios 
... a DGT irá proceder a essa inclusão já na próxima versão das ET.
