### ISSUE TITLE
Caixa de eletricidade / Caixa de telecomunicações

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#50]
Sugere-se acrescentar o valor 'Caixa' à lista 'valorElementoAssociadoElectricidade' e 'valorElementoAssociadoTelecomunicacoes' para representar as caixas que se encontram na via pública, de dimesões próximas de 1mX1mX0,3m. Definição: Instalação sobre o solo que inclui equipamento de ligação e de derivação de cabos condutores.
Exemplo:
![caixa](https://user-images.githubusercontent.com/8429292/109291090-701a7200-7820-11eb-8a5e-659255ea81b2.jpg)

**Comment by aserronha** [comment]
A resposta é a mesma da issue #49
