### ISSUE TITLE
Individualizar "Farmácia"

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#51]
Atendendo à relevância social da Farmácia e tendo em consideração que as Câmaras Municipais emitem certidões para fundamentar os processos de transferência da localização de Farmácias ao abrigo da Portaria n.º 352/2012, de 30 de outubro, sugere-se que "Farmácia" seja individualizada, acrescentado o valor '2.4 Farmácia' em 'valorTipoEquipamentoColetivo' e ajustando a definição de '2.3 Outro-saúde' (retirar a referencia feita às farmácias).

As certidões camarárias acima mencionadas visam assegurar o preenchimento dos requisitos respeitantes à distância previstas: 1) Distância mínima de 350 m entre farmácias, contados, em linha reta, dos limites exteriores das farmácias; 2) Distância mínima de 100 m entre a farmácia e uma extensão de saúde, um centro de saúde ou um estabelecimento hospitalar, contados, em linha reta, dos respetivos limites exteriores, salvo em localidades com menos de 4000 habitantes.

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Esta questão ainda será avaliada na próxima versão das Especificações Técnicas.

**Comment by aserronha** [comment]
Caro Aurélio Pires,

Agradecemos desde já o seu contributo.
A sua questão foi avaliada. Achámos prudente não individualizar a Farmácia nas Especificações Técnicas (ET) de Cartografia Topográfica v2.0.
Não é possível estabelecer uma relação direta entre estas especificações e qualquer Portaria. As especificações de cartografia são mais transversais e pretendem servir múltiplas finalidades.
As farmácias serão inclusivamente ajustadas à utilização atual do Edifício como “Pequena loja”. No(s) nome(s) é possível obter essa informação e a partir daí pode explorar os dados como entender sabendo que as farmácias são elementos que integram a base de dados numa lógica de não individualizar em particular as farmácias em detrimento de qualquer outro estabelecimento de atividade comercial.

Cumprimentos.
