### ISSUE TITLE
Garagem

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#52]
O objeto garagem só está modelado como elemento "Associado à residência" caso 'valorUtilizacaoAtual' seja 'Habitação'. E para os casos em que o 'valorUtilizaçãoAtual' for outro que não 'Habitação' (por exemplo, 'Alojamento e restauração', ou 'Serviços') como é classificado um edifício isolado cuja utilização é garagem?

Uma possibilidade seria incluir no 'valorFormaEdificio' o valor "Garagem", à semelhança do que acontece com "Telheiro" (existe no 'valorFormaEdificio' e que pode estar 'Associado à residência' caso 'valorUtilizacaoAtual' seja 'Habitação').

Ou o mais adequado é, para estes casos, usar o valor 'Parque de estacionamento em edifício' para 'valorUtilizacaoAtual'?

E como classificar uma arrecadação afeta a um Edifício com 'valorUtilizacaoAtual' igual a 'Alojamento e restauração', ou 'Serviços'?

**Comment by aserronha** [comment]
Caro Aurélio Pires,

No dicionário de objetos, em Edifício: https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html  já tem as respostas às suas dúvidas nas "Observações".

A garagem e arrecadação não são edifícios com uma "forma característica" e como tal não se encaixa na forma, no que foi preconizado tendo como base o modelo INSPIRE.

Nessas circunstâncias todo o tipo de garagens e arrecadações que não sejam 'Associado à residência' não são discriminadas e são edifícios sem forma e sem utilização. O 'valorUtilizacaoAtual' pode ficar "nulo", ou seja, não é estabelecida relação entre a geometria e a utilização nesses edifícios.

As eventuais extensões ao modelo, no futuro, poderão solucionar estes e outros casos em que faça sentido acrescentar valor ao modelo base.

**Comment by aserronha** [comment]
Gostaríamos de acrescentar que, caso se trate de um edifício para estacionamento público eventualmente associado a algum tipo de serviço (por exemplo, 'Alojamento e restauração', ou 'Serviços'), o 'valorUtilizacaoAtual' poderá também assumir o valor 'Parque de estacionamento em edifício'. Para o caso de simples garagens individuais, caso não estejam associadas à residência, o 'valorUtilizacaoAtual' deve ficar "nulo".
