### ISSUE TITLE
Dicionario de objectos desactualizado - relações das infraestruturas ferroviarias

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#53]
O dicionário de objectos não parece estar actualizado para o tema dos transportes ferroviários

Nas relações existe uma ligação chamada ligacaoAreaInfraTransFerrovInfraTransFerrov que aparentemente foi eliminada e substituida por um campo na tabela das areas de infraestruturas ferroviarias:

https://github.com/dgterritorio/RECART/blob/v1.1.2/recart.ddl#L861

No entanto no respectivo objecto o dicionario nao esta actualizado

https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/AreaInfraTransFerrov.html

**Comment by dgterritorio** [comment]
Não é possível fazer uma correspondência directa entre o catálogo e a base de dados, apenas parcial.

Na base de dados implementamos relações de diversas formas, consoante a multiplicidade, seja através de atributos na tabela ou tabelas de ligação.

Neste caso, a relação entre  "area_infra_trans_ferrov" e "infra_trans_ferrov" [0..*]->[1]  é implementada através do atributo "infra_trans_ferrov_id" em "area_infra_trans_ferrov".
Explicitar este atributo no catálogo obrigava a explicitar também, noutros casos, as tabelas e atributos de ligação, assim como atributos com multiplicidade N que são implementados em tabelas externas.

Esperamos ter esclarecido.
