### ISSUE TITLE
Infraestruturas de Transporte aéreo - não existe relações explicitas

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#54]
Aparentemente, não existem relações explicitas entre a areas de infraestrutura e a infraestrutura de transporte aero. Não sei se é propositado ou não. Mas não me parece coerente com os restantes objectos de transportes, como o do transporte ferroviario e rodoviario.

**Comment by dgterritorio** [comment]
A razão de termos optado pela ligação no caso dos transportes rodoviários e ferroviários tem a ver com a fragmentação e dimensão dessas áreas, como estacionamentos na rua,  zonas para paragem de transportes públicos, apeadeiros, etc.
A existência de ligação permite identificar a tipologia da infraestrutura dessas áreas e a sua designação em conjunto, como, por exemplo, "Estacionamento da Rua Artilharia Um".

Essa fragmentação não existe nos transportes aéreos, marítimos ou por cabo, ou existindo é menos relevante devido à grande dimensão dessas áreas.

A decisão foi ponderada, balanceando a complexidade do modelo e o considerado mais importante.
