### ISSUE TITLE
Dúvida - Multiplicidade segmento de via ferroviária - via ferroviária

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#55]
Da forma como está estruturado o modelo, aparentemente a relação entre os Segmentos de via ferroviária e a via ferroviária é de n para m.

No entanto, pode o mesmo segmento pertencer a mais do que uma via ferroviária?
No caso dos segmentos de via rodoviária esta relação faz sentido, no entanto, no caso das vias ferroviárias parece-me que se estará a complicar sem necessidade. Ou isto é imposição do INSPIRE?

**Comment by dgterritorio** [comment]
Esta relação de um segmento pertencer a mais que uma via ferroviária é efectivamente necessária.
Verificamos isso, por exemplo, no Metro do Porto (Linhas A, B, C, etc.),  onde várias linhas partilham os mesmos segmentos em muitos casos.

**Comment by SrNetoChan** [comment]
Obrigado pela resposta!
