### ISSUE TITLE
Dúvida: Passagem superior / Passagem inferior

### ISSUE THREAD

**Issue by anvpires** [dgterritorio/RECART#68]
Nos esquemas seguintes, que estão no Dicionário de objetos, qual o critério usado para classificar a passagem que está a cor azul escuro, a da figura da esquerda como "Passagem superior" e a da direita como "Passagem inferior"?

![ObraArte-valorTipoObraArte](https://user-images.githubusercontent.com/8429292/117420489-8d04ad00-af15-11eb-8ebb-6bfdd51d8ff1.jpg)

**Comment by aserronha** [comment]
Agradecemos a exposição da dúvida no github ao invés de envio de documentos.

A diferença está na própria definição. Ver em: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Obra%20de%20arte)/ObraArte.html#page_valorTipoObraArte 

Há situações mais difíceis de classificar no âmbito de uma produção com fins (apenas) cartográficos. Como estas especificações são mais abrangentes e procuram uma maior multi-funcionalidade podemos dizer que aqui fomos um bocadinho mais exigentes. Neste caso concreto, a diferença reside no **sobre** (figura da esquerda "Passagem superior") e **sob** (figura da direita "Passagem inferior") da **importância** das vias de comunicação que se cruzam desniveladamente.

Por vezes nem sempre é fácil dissociar as exigências cartográficas e/ou temáticas.

No léxico da engenharia civil (vias de comunicação) não há dúvidas e as obras de arte estão catalogadas. 
No léxico das Infraestruturas de Portugal existem muitas classificações desta temática:
https://www.infraestruturasdeportugal.pt/pt-pt/negocios-e-servicos/lexico/p

**Comment by aserronha** [comment]
Aguardamos algum comentário da sua parte para sabermos se podemos encerrar a _issue_.

**Comment by aserronha** [comment]
Obrigado pela identificação do erro. Iremos tomar as medidas necessárias para a sua correção na próxima versão das especificações técnicas.
