### ISSUE TITLE
Escadaria - Construção Poligonal vs Via em escada

### ISSUE THREAD

**Issue by asalvaterra** [dgterritorio/RECART#71]
Boa tarde,
A via em Escada se tiver largura para serem representados os seus limites (Via rodoviária - Limite), esses limites coincidirão com dois dos lados do polígono (se o polígono tiver área para ser representado) que terá que se representar  na entidade Construção Poligonal, certo?

**Comment by aserronha** [comment]
Boa tarde,

Exatamente, se simultaneamente as escadarias forem uma via de comunicação então são essas as condições da representação da "Via rodoviária - Limite", "Segmento da via rodoviária" -> 'Via em escada' e "Construção poligonal" -> 'Escadaria'.
Existem também bastantes escadas/escadarias que não são vias de comunicação que basta representar, se tiverem dimensões, na "Construção poligonal" -> 'Escadaria'.
