### ISSUE TITLE
Áreas Artificializadas - Equipamentos industriais

### ISSUE THREAD

**Issue by MartaValenteMuni** [dgterritorio/RECART#72]
Quando temos parques industriais estes devem ser apenas uma área geral ou devem ser áreas individualizadas por indústria, de forma a que seja possível relacionar com a Instalação de Produção correta? Sendo apenas uma área para X fábricas, não é possível relacionar com as Instalações de Produção existentes.
![duvida_Pq_industrial](https://user-images.githubusercontent.com/60008526/120350938-54c77300-c2f7-11eb-8fda-5544f521c9fe.png)

Quando temos indústrias isoladas, devemos ter também uma área ártificializada?
 
![duvida_fabrica](https://user-images.githubusercontent.com/60008526/120350973-5c871780-c2f7-11eb-897e-11bc528f0cab.png)

**Comment by dgterritorio** [comment]
Partindo da definição do nosso modelo que uma instalação de produção só pode ter uma atividade, com zero ou mais áreas artificializadas e zero ou mais edifícios,

Um parque industrial não pode ser uma instalação de produção, é sim um conjunto de instalações de produção, a não ser que a atividade industrial no parque seja sempre a mesma, por exemplo armazéns.

Relativamente à segunda questão, não é necessário existir uma área artificializada para uma instalação de produção, pode ser constituída só por edifícios, se não existir uma nenhuma área envolvente delimitada.
