### ISSUE TITLE
Representação do Objecto Mina

### ISSUE THREAD

**Issue by socart** [dgterritorio/RECART#75]
Boa Tarde, 

Como deve ser representada esta mina?

1-	Dado que não existem instalações de apoio, não se estabelece a ligação à tabela de inst_producao?
2-	Apenas deve ser representado as áreas de exploração no tema das áreas artificializadas com a classificação de “Equipamentos Industriais”? 
3-	Ou a lógica a seguir é a mesma dos cemitérios (equip_coletivo), isto é, cria-se o registo na tabela inst_producao e depois estabelecesse a ligação ao tema das áreas artificializadas? 
4-	Podemos representar várias áreas artificializadas com o mesmo nome e tendo o mesmo identificador de inst_producao?

![image](https://user-images.githubusercontent.com/60113889/122565286-32935c00-d03e-11eb-95f5-8e34518a1da0.png)

Obrigado,

**Comment by aserronha** [comment]
Obrigado pela exposição de dúvidas nesta plataforma.

1 - Se não existem construções não se estabelece nenhuma ligação.
2 - Cada área pode ser representada individualmente com a classificação de Equipamentos Industriais como descrito em https://www.dgterritorio.gov.pt/recart/OCUPA%C3%87%C3%83O%20DO%20SOLO/AreasArtificializadas.html 

3 - Não diria por lógica, mas por paralelismo, cada área de exploração da Mina pode conter sempre o mesmo identificador dessa Instalação de produção (Mina) que obrigatoriamente tem de ter um nome. Cada área artificializada (individualizada) pode não ter nome. 
4 - Anteriormente já se respondeu a esta questão, ou seja, o mesmo identificador de inst_producao pode estar em cada área artificializada já que estamos perante a mesma Mina (esta sim tem que ter nome).

**Comment by socart** [comment]
Boa tarde, 

Só para confirmar, então podemos criar o registo na tabela inst_producao: Minas da Barrosa e usar esse identificador para todas estas áreas artificializadas?

Se não soubéssemos o nome da mina, criávamos o registo mesmo assim na tabela de inst_produção para não se perder esta informação, à semelhança do que está exposto no dicionário de objectos para o caso da pedreira? 

Obrigado,

**Comment by aserronha** [comment]
Resposta à questão 1: Exatamente (se corresponderem todos os polígonos à mesma inst_ptoducao)

Resposta à questão 2: Exatamente (a obrigatoriedade do nome neste modelo exige um trabalho complementar, ou de campo, porque na maioria dos casos desses objetos com esta exigência, o nome existe).
