### ISSUE TITLE
Representação do objecto Áreas Artificializadas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#76]
Boa Tarde, 

Quando uma área artificializada é separada por uma via de comunicação, como deve ser representada? Uma única área ou o facto de passar a estrada obriga ao desenho de duas áreas como ilustrado na imagem seguinte?

![image](https://user-images.githubusercontent.com/60113889/122814582-510e8700-d2cc-11eb-9d3f-1fe2db324cc6.png)

Obrigado,

**Comment by aserronha** [comment]
A imagem está a ilustrar bem e é mesmo isso que se pretende. Uma via rodoviária de atravessamento obriga à divisão de uma eventual área, em duas áreas que eventualmente podem conter o mesmo identificador da instalação/equipamento, etc.
