### ISSUE TITLE
Representação do Objeto Central Eólica

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#77]
Bom Dia, 
1-	O que deve ser representado como central eólica? 
2-	Devemos entender central eólica como a delimitação de parque eólico?
3-	Como proceder quando não obtemos a informação de quais são os limites dos parques éolicos? 

![image](https://user-images.githubusercontent.com/60113889/123053204-8f569400-d3fb-11eb-86ff-ef35e7ecc291.png)

Obrigado,

**Comment by aserronha** [comment]
Respostas:

1- O que deve ser representado como central eólica?
Resposta: A área oficial delimitadora do parque eólico (se existir). Deixa de ser obrigatória a sua representação na fase de aquisição de dados (ver que já não existe X em:
https://www.dgterritorio.gov.pt/recart/INFRAESTRUTURAS%20E%20SERVI%C3%87OS%20DE%20INTERESSE%20P%C3%9ABLICO/ElemAssocEletricidade.html#page_valorElementoAssociadoElectricidade 

2- Devemos entender central eólica como a delimitação de parque eólico? 
Resposta: Sim.

3- Como proceder quando não obtemos a informação de quais são os limites dos parques éolicos? 
Resposta: Na fase de produção deixa de ser obrigatório esta aquisição. Se por algum motivo se adquirirem estes dados só deverá acontecer se existirem limites físicos ou informação oficial paraserem representados como áreas.
Continua a ser obrigatório colocar na "zona envolvente", o topónimo do Parque eólico (ou central eólica), no objeto [[02.01] Designação local](https://www.dgterritorio.gov.pt/recart/TOPON%C3%8DMIA/DesignacaoLocal.html) com o [valorLocalNomeado](https://www.dgterritorio.gov.pt/recart/TOPON%C3%8DMIA/DesignacaoLocal.html#page_valorLocalNomeado) 15 'Outro - Local nomeado'
