### ISSUE TITLE
Catálogo das vias rodoviárias (Abreviaturas)-Omissão

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#79]
Bom dia, 

Temos dois tipos de artérias que não constas na listagem de abreviaturas "Cantinho" e "Quelho".

![cantinho](https://user-images.githubusercontent.com/60113889/124961260-25520780-e015-11eb-83a2-c54278966ded.png)

![image](https://user-images.githubusercontent.com/60113889/125114607-16855680-e0e2-11eb-9228-530eaf304202.png)

Quando possível, agradecíamos que fosse acrescentado mais estes registos à listagem.

Obrigado,

**Comment by aserronha** [comment]
Atualização efetuada. Ver em:
https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/CatalogoDasViasRodoviariasAbreviaturas.html
