### ISSUE TITLE
Representação dos objetos Antena, Torre e Estação de Emissão ou Recepção

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#80]
Bom dia, 

A representação dos objetos Antena, Torre e Estação de Emissão ou Receção está conforme se pretende? 

A nossa dúvida é quando representamos a torre como ponto no tema dos edifícios, se também temos de estabelecer ligação à tabela da instalação produção e classificar com o valor 10 – Estação de emissão ou recepção.

![image](https://user-images.githubusercontent.com/60113889/124467069-4275a480-dd8f-11eb-8216-146ee84e1194.png)

![image](https://user-images.githubusercontent.com/60113889/124467162-6507bd80-dd8f-11eb-8db4-00210f2a4e25.png)

Obrigado,

**Comment by aserronha** [comment]
A situação apresentada é semelhante ao esclarecimento efetuado em: https://github.com/dgterritorio/RECART/issues/75

Se os exemplos apresentados forem de facto uma 'Estação de emissão ou receção' é necessário preencher com um "nome verdadeiro", o que exige um trabalho complementar, ou de campo, porque na maioria destes casos, como já referimos, este nome existe.
