### ISSUE TITLE
Representação dos objetos rampas e escadarias em passagem pedonal

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#83]
Bom dia, 
Nestas situações apenas deve ser classificado passagem pedonal, correto? 
Não é necessário representar as escadarias ou rampas? 
Ou deve ser representado os objetos rampa e escadarias nestas situações?

![image](https://user-images.githubusercontent.com/60113889/126287670-96c6e23d-68dc-4850-95ad-54b8fe33ba52.png)

Obrigado,

**Comment by aserronha** [comment]
Toda a infraestrutura deve ser representada apenas como passagem pedonal em https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Obra%20de%20arte)/ObraArte.html#page_valorTipoObraArte

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 
Nas passagens pedonais, como as ilustradas na imagem abaixo, devemos:
![image](https://user-images.githubusercontent.com/60113889/142011034-381e7138-60f4-4b53-861b-a55127f196f9.png)

a)	Sempre que seja uma via de ligação entre segmentos deve-se representar o seg_via_rodov, correto?

b)	Quando não são em escadas, como deve ser classificado o seg_via_rodov quanto ao atributo “valor_tipo_troco”?  Plena via ou trilho?


Obrigado,

**Comment by aserronha** [comment]
a) Correto

b) Quando não são em escadas... pode ser uma "Plena via" ou "Trilho". Não pode ser dada uma resposta direta.

**Comment by CatarinaGaspar** [comment]
Entendido, obrigado.
