### ISSUE TITLE
Representação do objeto Lancil

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#84]
Bom dia, 

**1- O que deve ser representado como lancil?**

Da pesquisa que foi feita concluímos que existem vários tipos de lancil:
![image](https://user-images.githubusercontent.com/60113889/126287865-d791c981-7cac-4ddd-b859-bc091e62ccf7.png)

**2- Devem ser adquiridos todos os tipos?**

**3- Segue alguns exemplos de que temos dúvidas se são para adquirir:**

![image](https://user-images.githubusercontent.com/60113889/126288105-753894ed-7057-4ee9-8d3e-ecd9eea8cd6c.png)

![image](https://user-images.githubusercontent.com/60113889/126288679-3e7b6117-0a09-47ba-8917-88ea1db77749.png)

![image](https://user-images.githubusercontent.com/60113889/126288895-9c197e78-1f09-414a-82eb-4f00e10a1cc7.png)

Obrigado,

**Comment by aserronha** [comment]
O lancil não é de aquisição obrigatória. 
Se o lancil for adquirido, por imposição do dono de obra, devem recolher todos os tipos de configuração.

**Comment by CatarinaGaspar** [comment]
Entendido. 
Sim o proprietário quer que seja adquirido mais este objeto em concreto.

Obrigado pelo esclarecimento.
