### ISSUE TITLE
Classificação de edifícios associados a estaleiros de obras

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#85]
Bom dia, 

Como classificar os edifícios associados aos estaleiros de obras quanto ao ValorUtilizaçaoAtual? 
Poderá ser 7.3 – Outros-Serviços?

![image](https://user-images.githubusercontent.com/60113889/126290158-a7899d5f-00d8-42b9-a6d7-4ec46ea4acf5.png)

Obrigado,

**Comment by aserronha** [comment]
Não. 
Deve ser classificado como 3 - Indústria em https://www.dgterritorio.gov.pt/recart/CONSTRU%C3%87%C3%95ES/Edificio.html#page_valorUtilizacaoAtual 
 
Indústria é o conjunto das actividades que visam a manipulação e transformação de matérias-primas para a produção de bens de consumo.


Quanto à divisão dos 3 setores da economia:
 
- o primário, compreende as atividades ligadas à natureza, como sejam a agricultura, a silvicultura, as pescas, a pecuária, a caça ou as indústrias extrativas;

- o secundário, onde são englobadas as atividades industriais transformadoras, a construção, a produção de energia;

- o terciário (ou dos serviços), que engloba o comércio, o turismo, os transportes e as atividades financeiras.

**Comment by CatarinaGaspar** [comment]
Obrigado pelo esclarecimento.
