### ISSUE TITLE
Classificação de vias rurais e privadas

### ISSUE THREAD

**Issue by OscarMCardoso** [dgterritorio/RECART#86]
Bom dia,

Na seguinte situação temos a amarelo uma via nacional facilmente identificada em termos de nome. A questão é: é para marcar?
Vias agrícolas - acesso a campos, "terra batida", como os a norte das figuras em anexo? 
Vias de acesso a residências com portão, como acesso único à residência, ou seja privado?
Vias e acesso a fábricas são para marcar, como acesso único à fábrica, ou seja privado?

Se a resposta for sim, e são para marcar, como é definido o nome dessas mesmas vias e restantes atributos?
![1](https://user-images.githubusercontent.com/87970647/126958029-3e1f3883-7790-40fe-840b-3b4567acab24.JPG)
![2](https://user-images.githubusercontent.com/87970647/126958037-286f642b-a858-4296-b403-828bc8e464d6.JPG)

Obrigado

**Comment by aserronha** [comment]
Na seguinte situação temos a amarelo uma via nacional facilmente identificada em termos de nome. A questão é: é para marcar? Resposta: Sim, é para adquirir.

Vias agrícolas - acesso a campos, "terra batida", como os a norte das figuras em anexo? 
Resposta: São para recolher. Os ‘Segmento da via rodoviária’ recolhem-se sempre e consoante o nível de detalhe, sendo que a recolha dos seus limites depende da largura da via  (ver regras nas especificações técnicas para esse efeito).

Vias de acesso a residências com portão, como acesso único à residência, ou seja privado? 
Resposta: São para recolher, com exceção das vias dentro dos logradouros da habitação que não são para recolher. O atributo onde se define a restrição de acesso de cada via (https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#page_valorRestricaoAcesso ), não é de preenchimento obrigatório  na fase de produção (porque não tem X nem para o NdD1 nem para o NdD2). Quanto às vias de acesso pode consultar as definições e os esquemas de representação em https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#page_valorTipoTrocoRodoviario . 

Vias e acesso a fábricas são para marcar, como acesso único à fábrica, ou seja privado? 
Resposta: Ver os esquemas de vias de acesso em https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#page_valorTipoTrocoRodoviario . 

Se a resposta for sim, e são para marcar, como é definido o nome dessas mesmas vias e restantes atributos? 
Resposta: Se a via rodoviária não tiver nome simplesmente recolhem-se mas não se estabelece a relação entre a tabela geográfica ‘Segmento da via rodoviária’ e a tabela alfanumérica ‘Via rodoviária’ dos nomes.
