### ISSUE TITLE
Lisatagem Abreviaturas - Recanto

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#87]
Boa tarde, 

Apesar de estar contemplado o tipo de artéria "Recanto" na listagem de abreviaturas, esta não tem correspondência de nenhuma abreviatura no campo  "tipo_via_rodov_abv".

Associamos este registo mesmo assim? 
ou é necessário ser criado a abreviatura? - sugestão RCT

![image](https://user-images.githubusercontent.com/60113889/127002757-7221752b-fa29-4f08-b04e-26ec54ea2b26.png)

Obrigado,

**Comment by aserronha** [comment]
Podem enviar-nos uma fotografia duma placa de toponímia com 'Recanto'? 
É que nas listagens que temos do INE não existe essa abreviatura mas nos dados dos CTT sim, e como tal, se for possível, agradecemos essa documentação na resposta a este comentário.

Obrigado.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Esta é a melhor imagem que consigo:

**Recanto do Forno**
![image](https://user-images.githubusercontent.com/60113889/127031468-c433c837-1c1a-4ec2-af53-17975fca92fa.png)

Obrigado,

**Comment by aserronha** [comment]
Feito!
Procurámos a abreviatura utilizada pelos CTT mas como não encontrámos seguimos a vossa sugestão.

**Comment by CatarinaGaspar** [comment]
Obrigado,
