### ISSUE TITLE
Marcação de portão com corrente

### ISSUE THREAD

**Issue by martabmatos** [dgterritorio/RECART#88]
Boa tarde,
Quando surgem acessos de vias vedados somente com uma corrente (imagem) faz-se a marcação de portão (se tiver as dimensões mínimas)? ou só se marca a via como acesso privado?

![Portao_Cadeado](https://user-images.githubusercontent.com/88499637/128370917-495412cb-7da9-4672-b919-036cf27e0061.jpg)

Agradeço a atenção.
Marta

**Comment by aserronha** [comment]
Uma corrente não é um portão logo não se adquire como "Portão". Apenas não se representa nada.

A "via rodoviária" é adquirida e quanto ao facto de ser acesso privado, esse é um atributo que não é de preenchimento obrigatório, ou seja, sem X, como se pode ver aqui: https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#page_valorRestricaoAcesso
