### ISSUE TITLE
Incoerência em Cota (?pleno vs plena?) armazenamento 

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#89]
Para a tabela agua_lentica, o modelo SQL descrito no ddl cria uma coluna do typo boolean com o "nome cota_plena_armazenamento", no entanto, o ficheiro JSON descreve um atributo chamado cotaPlenoArmazenamento.

Na tabela SegViaRodov, o modelo SQL descrito no DDL cria uma coluna chamada "valor_caract_fisica_rodov". O ficheiro JSON descreve o mesmo atributo com o nome valor_caract_fisica_via_rodov.

Na tabela de AreaTrabalho, segundo o modelo SQL tem os atributos nome_proprietario, nome_produtor. O ficheiro JSON tem nome_do_proprietario, nome_do_produtor.

**Comment by dgterritorio** [comment]
Foram resolvidas as incongruências em https://github.com/dgterritorio/RECART/commit/2abf1670bb055b7bf91760f1336dac6abddcfe22

Obrigado pela colaboração.
