### ISSUE TITLE
Nota_Conduta_de_agua

### ISSUE THREAD

**Issue by philosadelphos** [dgterritorio/RECART#9]
No seguinte processo de catalogação de condutas:
 RECART/objectos/INFRAESTRUTURAS E SERVIÇOS DE INTERESSE PÚBLICO/CondutaDeAgua.json 
Do consegui compreender, penso que não está previsto um campo para o material da conduta (da minha experiência profissional em infraestruturas hidráulicas, conhecer este atributo é importante para gestão/manutenção do imobilizado). 
Cumprimentos

**Comment by dgterritorio** [comment]
Este atributo não se enquadra nas especificações técnicas desta cartografia topográfica, baseada nas normas INSPIRE. No contexto da directiva INSPIRE este atributo é apenas considerado nas extensões ao modelo (Utilities).
Cumprimentos

**Comment by aureliopires** [comment]
Na pág 117 do CartTop-V1.0 (28.06.2019), para o 'VALORUTILIZACAOATUAL' o código 7.2 está repetido: "Serviços de utilização coletiva" e "Outros - Serviços".
