### ISSUE TITLE
Temática AreasArtificializadas - Sobreposição entre Areas

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#90]
Bom dia, 

Podem-nos confirmar que não se pode sobrepor áreas artificializadas: "áreas em construção" e outra por exemplo "equipamentos industriais"?

![image](https://user-images.githubusercontent.com/60113889/129179756-9752ff85-cfb4-4efb-a53c-58e748b1b4e8.png)

Obrigado,

**Comment by DGTmarisa** [comment]
Nas observações das “Áreas artificializadas” é referido que:

As áreas definidas como “Áreas artificializadas” devem ser únicas (sem “recortes” e sem “buracos”) caso tenham a mesma classificação e intersetem outro elemento pontual ou linear. 

As “Áreas artificializadas” não podem estar sobrepostas. Quando a classificação não é a mesma pode recorrer-se ao artificio dos “buracos”.
