### ISSUE TITLE
Ortos e MDT - Obrigatório incluir no projeto para Homologação?

### ISSUE THREAD

**Issue by martabmatos** [dgterritorio/RECART#91]
Boa tarde,
Num projeto para homologação em nD1 relativa a uma via rodoviária com uma extensão de cerca 17 km e uma largura de área de trabalho de 50 metros é obrigatório a apresentação, no projeto final, dos Ortos e do Modelo Digital do Terreno? Ou só se apresenta se o cliente pretender homologar estas peças também?

Obrigada

**Comment by DGTmarisa** [comment]
A informação vetorial pode ser adquirida individualmente por Tema, com as seguintes particularidades:
- "Infraestruturas e serviços de interesse público" pressupõe a aquisição dos temas "Construções" e "Ocupação do solo";
- "Altimetria" pressupõe a produção do Modelo Digital do Terreno (MDT).

A decisão sobre quais os Temas a adquirir cabe ao proprietário, assim como a opção de incluir no projeto a produção de ortofotos.

Para efeitos de Homologação, a Cartografia Topográfica Vetorial e a Cartografia Topográfica de Imagem são processos independentes. Para a submissão de cartografia para homologação deverá ser usada a plataforma:
https://homologacao.dgterritorio.gov.pt

Para mais informação deverá contactar homologação@dgterritorio.pt
