### ISSUE TITLE
Representação dos Segmentos de Linhas Ferreas em Desuso

### ISSUE THREAD

**Issue by CatarinaGaspar** [dgterritorio/RECART#93]
Boa Tarde, 

No seguimento de uma questão colocada anteriormente, a DGT respondeu-nos que os segmentos das vias férreas em desuso devem ser representados na mesma e que esta questão ia ser analisada/ revista para próxima versão das normas técnicas. 

Questionamos se nestes casos o tratamento que é dado é o mesmo como se a linha ferrea estivesse funcional, isto é, além da sua representação geométrica, também é necessário a sua caraterização, a associação do nome da linha, bem como a geração dos seus nós de transporte férreo, inclusive os nós de paragem e de passagem de nível?

![image](https://user-images.githubusercontent.com/60113889/130459343-d9dc88c6-40c6-41f9-9956-c7c42bb8db32.png)

Obrigado,

**Comment by dgterritorio** [comment]
Os segmentos de linha férrea em desuso são tratados da mesma forma que as linhas funcionais.  Como refere a definição, um segmento de linha férrea em desuso já não é utilizada, mas não está a ser ou não foi desmantelada, mantendo todas as suas características.

**Comment by CatarinaGaspar** [comment]
Obrigado,

**Comment by MartaValenteMuni** [comment]
Bom dia,

Como se classifica relativamente a segmentos da via férrea desmantelados, uma vez que já não se mantém as características?

**Comment by aserronha** [comment]
Viva,

A resposta já foi dada anteriormente.

Um "Segmento da via-férrea" representa-se sempre geometricamente. Quanto à sua classificação no atributo [valorEstadoLinhaFerrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html#page_valorEstadoLinhaFerrea), nesta fase de produção não é pedido ao produtor para especificar o estado, exceção feita quando existem vias em construção!

**Comment by MartaValenteMuni** [comment]
Apenas verificámos uma resposta relativamente às vias em desuso. Peço desculpa pela duplicação.

Mas como são atribuídas as características se o segmento da via férrea se encontra desmantelado e já não existem carris?

**Comment by aserronha** [comment]
Se já não existem carris não se representa nada.

Nesta primeira fase de produção pretendeu-se indicar com o auxílio de um x (obrigatório) o que é para representar apenas e o que é para simultaneamente representar e classificar (valores obrigatórios em cada atributo).

Como sabemos que na fase de produção nem sempre é fácil avaliar determinadas características dos objetos quanto aos seus atributos, este é um bom exemplo em que se pretende apenas que o produtor represente apenas o que existe no terreno e não se pretende que o produtor avalie simultaneamente se está ou não em desuso, desmantelado, funcional, etc. Sendo assim, só é exigida essa classificação no atributo [valorEstadoLinhaFerrea](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20ferrovi%C3%A1rio)/SegViaFerrea.html#page_valorEstadoLinhaFerrea) quando a via está em construção...

Existe uma fase de produção dos dados e é aqui que consiste estas Especificações Técnicas (ET). A forma como os dados podem ser complementados fogem do âmbito destas ET na chamada fase de exploração dos dados.
