### ISSUE TITLE
Seccionamento de projeto (Área de Trabalho)

### ISSUE THREAD

**Issue by martabmatos** [dgterritorio/RECART#94]
Boa tarde,

Gostaria de obter esclarecimento sobre Homologação de Ortofotomapas.

No Manual refere que "Os dados da Cartografia Topográfica não estão sujeitos a qualquer tipo de seccionamento excetuando, e apenas quando a dimensão da área de trabalho (“Área de trabalho”) o justificar por razões de manuseamento da informação, os dados matriciais relativos ao modelo digital do terreno e aos ortofotos."

Dadas as características de um projeto que estamos a trabalhar (uma faixa de +/- 60m ao longo de 17Km de uma estrada) se se pode usar para efeitos de homologação das ortofotos e do MDT o seccionamento que se junta em anexo (seccionamento.gpkg)?

Agradeço a atenção.
Marta

[seccionamento.zip](https://github.com/dgterritorio/RECART/files/7085530/seccionamento.zip)
?

**Comment by dgterritorio** [comment]
Os seccionamentos que devem ser usados constam da página da DGT em:

https://www.dgterritorio.gov.pt/cartografia/cartografia-topografica/normas-especificacoes-tecnicas

Para cada NdD:
https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/SeccionaNdD1.rar


https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/SeccionaNdD2.rar
