### ISSUE TITLE
Sobreposição de albufeiras com outros objetos

### ISSUE THREAD

**Issue by aserronha** [dgterritorio/RECART#96]
Os objetos visíveis são sempre representados (a partir da informação visual disponível) mesmo que contidos dentro da Albufeira e isso acontecerá muitas vezes porque pretende-se que a recolha seja efetuada, sempre que possível, pelo Nível de pleno armazenamento (NPA). 

Deve-se confirmar se não existem lapsos, junto da Agência Portuguesa do Ambiente (APA) e se o valor apresentado de NPA está de facto correto porque por vezes as cotas são determinadas em fase de projeto e podem surgir incongruências, por exemplo, uma alteração na fase de execução pode não ter sido reportada. Caso a APA indique que este é o valor correto, então é este valor que deve ser usado e representado:

![image](https://user-images.githubusercontent.com/46351849/133645678-64b64c65-22eb-4ca0-b420-ae351f126021.png)

**Comment by CatarinaGaspar** [comment]
Boa tarde,

Seguimos a sugestão dada pela DGT e tentamos via email (07-09-2021) e por telefone diversas vezes confirmar junto da APA se as cotas de NPA apresentadas no site estavam corretas e até ao momento não conseguimos obter qualquer resposta.

Dado que estamos a fechar o projeto em questão iremos usar as cotas de NPA indicadas pela APA e reportar no relatório de produção estas situações.

Em relação aos elementos visíveis dentro das albufeiras serem representados, questionamos o seguinte:

a)	Estes elementos entram na geração das curvas ou apagam-se? 
b)	Ou como devemos proceder?

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

As curvas de nível têm de ser representadas de acordo com as Especificações Técnicas (ET), refletindo a orografia do território. A forma como elas são obtidas, por restituição direta, levantamento topográfico, geração automática, é uma opção do produtor. É da responsabilidade dele assegurar que as curvas ficam aderentes ao terreno, logo ele é que tem de saber escolher os objetos que devem entrar na sua geração automática, se for esse o método seguido. De acordo com o respondido anteriormente, o NPA não deve ser tido em conta já que se representa tudo o que for visível, o que inclui orografia. Logo se determinado objeto visível é considerado relevante para gerar curvas de nível, também o será se ficar abaixo no NPA.

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

O que referem é o nosso entendimento no processo de obtenção das curvas de nível, pois estas têm de refletir a orografia do terreno. A nossa confusão era o facto de existirem elementos dentro e abaixo do NPA, pois estamos mais familiarizados com a representação destes objetos como eles existem no terreno. Mas este assunto está esclarecido.

No entanto deparamo-nos com outra questão que é relativamente à classificação dos eixos de hidrografia quanto ao atributo “fictício” (ver imagem abaixo). 
a)	Devemos considerar fictício desde a linha do NPA até ao eixo do rio (linha a verde)?
b)	Devemos considerar fictício desde a margem do rio até ao eixo do rio (linha a amarelo)?


![fiticio](https://user-images.githubusercontent.com/60113889/134408663-2755a080-23db-49ec-9c69-cece7a09655a.png)

Obrigado,

**Comment by aserronha** [comment]
Boa tarde,

Vamos tentar interpretar as vossas dúvidas. 

Onde têm escrito Npa, o objeto é uma Água lêntica (Albufeira) que foi adquirida pelo Npa e quando assim é, a recolha da Água lêntica é feita pelo Npa. Esse é o limite da única "massa de água" a representar. Como tal, deixa de existir qualquer outra "massa de água no terreno", seja ela "Água lêntica no terreno" ou "Curso de água área no terreno" . Posto isto, são recolhidos todos os outros objetos visíveis. 

Esperemos que esta imagem do dicionário seja interpretada de forma que ou só existe Água lêntica ou só existe Curso de água - área https://www.dgterritorio.gov.pt/recart/imagens/eCursoDeAguaEixo3.jpg Como tal, o curso de água - área só começa a ser representado quando terminar a representação da água lêntica pelo Npa.

Respondendo depois concretamente às questões, como o que têm representado como "massa de água no terreno" não existe, porque já existe representado a Água lêntica (Albufeira adquirida pelo NPA) então como têm em a) Devem considerar fictício desde a linha do NPA até ao eixo do rio (linha a verde).

**Comment by CatarinaGaspar** [comment]
Bom dia, 

A interpretação que fizeram foi a correta. 
Estamos esclarecidos quanto a este assunto.

Obrigado,

**Comment by CatarinaGaspar** [comment]
Boa Tarde, 

Para vossa reflecção:

Em vez de ser representado geometricamente o objeto “agua_lentica” pelo NPA, não se poderia representar pelo plano de água e ser criado um campo na tabela com a informação do NPA?

Esta alteração ajudava a simplificar o trabalho, quer a nível da aquisição da informação, quer em posterior processamento.

Obrigado,

**Comment by aserronha** [comment]
Bom dia,

Nas novas especificações técnicas v2 tivemos em linha de conta esta issue e o objetivo é representar a “Água lêntica” tendo em consideração os indícios da presença da água no momento da representação. Só se porventura esta representação coincidir com o nível pleno de armazenamento (NPA) é que o atributo “cotaPlenaArmazenamento” assume o valor verdadeiro.
