### ISSUE TITLE
Objectos e classificações não obrigatórias

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/RECART#99]
As dúvidas deste issue report vêm da análise de um relatório na componente Consistência do domínio com os seguinte erros:

![image](https://user-images.githubusercontent.com/3607161/138784480-5dfbb2ba-8e58-44cb-b2ad-686994b04340.png)

Gostaria de obter esclarecimento em relação a como proceder em casos de objectos previstos no modelo, mas não obrigatório para o nível de detalhe respectivo. Por exemplo, objectos de elementos associados à agua, como furos (6), camaras de visita (10) e sumidoros (11), estão previstos no modelo, mas não são obrigatórios para nenhum dos níveis de detalhe. Mas se forem recolhidos, podem ou não ser incluídos na base de dados? 

Se podem ser incluídos, a que se refere estes erros? 

![image](https://user-images.githubusercontent.com/3607161/138783786-59a2f25f-26d2-4a41-a0b4-9f455400e792.png)

Se não podem ser incluídos, qual o sentido de estarem previstos no modelo?

De igual forma, existem determinadas classificações não obrigatórias que também levantam dúvidas de como proceder. Por exemplo, nos edifícios, o ValorCondiçãoConstante prevê a classificação "Funcional", que não é obrigatória de indicar. No entanto, ficamos sem perceber se podemos ou não usá-la. A nosso entender, já que existe no modelo, achamos que faz sentido, no entanto o relatório de erros parece ter uma opinião contrária. O mesmo acontece com o ValorEstadoViaRodov, que tem multiplicidade 1 no entanto usar o valor 'Funcional' levantou erros no relatório.

Obrigado e bom trabalho

**Comment by aserronha** [comment]
@SrNetoChan compreendemos as dúvidas porque a abrangência deste modelo serve múltiplos propósitos.

Para efeitos de homologação, não é considerado como erro a representação de objectos ou utilização de atributos não obrigatórios nas Especificações Técnicas. Esta opção foi suportada pelas solicitações das empresas justificando que os clientes pretendem mais informação do que a prevista no modelo obrigatório e pelo facto de não querermos que a cartografia homologada seja muito diversa da que se usa efectivamente no dia-a-dia.

No âmbito da Homologação temos o cuidado de tentar diferenciar alguns atributos que consideramos mais suscetíveis. Assim, alguns objectos ou atributos identificados na análise automática não são considerados erro mas, dada a importância de alguns atributos como o “Funcional”, para estes, no relatório de Homologação segue uma anotação em que se chama a atenção para esse aspecto. 

A coerência dos dados num momento futuro em que os queiramos usar estará baseado no modelo obrigatório. 

Agora quanto à questão, primeiro tem de se olhar para a multiplicidade em abstrato, considerando os fenómenos no mundo real.
Uma estrada tem sempre apenas um dos estados definidos, não fazendo sentido ter vários nem não ter nenhum, mas devido às opções de produção dessa informação, apenas um valor da lista de códigos é permitido.
Na maior parte dos casos este campo vai estar vazio, o que obriga a que, embora a multiplicidade do objeto seja 1, o campo na base de dados possa ser nulo.

Referência:
[https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorEstadoViaRodov](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#go_up_valorEstadoViaRodov)
